<script lang="ts">
import {getAssets} from '@awc-ui/showcase-kit/design';
import Screen from '$lib/screens/Screen.svelte';
import TextControl from '$lib/editor/TextControl.svelte';
import SelectControl from '$lib/editor/SelectControl.svelte';
import {colorOf,layerFromAsset,LIVE_COMPONENTS,createLayer} from '@awc-ui/pictor-model';
import {route} from '$lib/routes';
import {document} from '$lib/document'; import {t} from '$lib/showcase'; import {navigate} from '$lib/router'; import Link from '$lib/components/Link.svelte';
let query: any = ''; const setQuery = (value: any) => query = typeof value === "function" ? value(query) : value;
let kind: any = 'all'; const setKind = (value: any) => kind = typeof value === "function" ? value(kind) : value;
let limit: any = 24; const setLimit = (value: any) => limit = typeof value === "function" ? value(limit) : value;
$: assets = getAssets().filter(asset => (kind === 'all' || asset.kind === kind) && asset.name.toLowerCase().includes(query.toLowerCase()));
$: insert = (layer: ReturnType<typeof createLayer>) => { $document.commitLayers('create', layers => [...layers, layer], [layer.id]); $document.setTool('select'); navigate(route.editor()); };
</script>
<Screen title={$t('The possibility library')} subtitle={$t('Good ideas deserve great ingredients. Add any asset directly to your canvas.')}> <section class="pictor-section"><div class="pictor-section__head"><div><span class="pictor-eyebrow">{$t('BUILT WITH AWC')}</span><h2>{$t('Components you can actually touch.')}</h2></div><span class="pictor-muted">{$t('Insert, compose, then try them in Present.')}</span></div><div class="pictor-live-library">{#each LIVE_COMPONENTS as item}<md-card variant="outlined"><span class="material-symbols-outlined" aria-hidden="true">{item.icon}</span><h3>{$t(item.name)}</h3><p>{$t(item.description)}</p><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="tonal" icon="add" on:click={() => insert(createLayer('component', { x: 16, y: 10, w: 17, h: item.id === 'awc:card' ? 14 : 5 }, { name: item.name, componentId: item.id, fill: '#BEE7AA' }))}>{$t('Add to canvas')}</md-button></md-card>{/each}</div></section> <section class="pictor-section" data-asset-library><div class="pictor-section__head"><h2>{$t('Collect a little inspiration')}</h2><span class="pictor-muted">{assets.length} {$t('assets')}</span></div><div class="pictor-library-filters"><TextControl live label={$t('Search library')} value={query} onValue={value => { setQuery(value); setLimit(24); }}></TextControl><SelectControl label={$t('Asset type')} value={kind} onValue={value => { setKind(value); setLimit(24); }} options={[{ value: 'all', label: $t('All assets') }, { value: 'image', label: $t('Images') }, { value: 'color', label: $t('Colors') }, { value: 'text-style', label: $t('Typography') }, { value: 'component', label: $t('Components') }]}></SelectControl></div><div class="pictor-library-grid">{#each assets.slice(0, limit) as asset}<md-card variant="outlined" class="pictor-library-card"><Link href={route.asset(asset.id)} class="pictor-library-preview" aria-label={$t('View {name}', {name: asset.name})}>{#if asset.art}<img src={asset.art.src} alt={$t(asset.art.altKey)} loading="lazy" />{:else}<svg viewBox="0 0 300 200" aria-hidden="true"><rect width="300" height="200" fill={colorOf(asset.color, '#E6EBDC')}></rect>{#if asset.kind === 'text-style'}<text x="30" y="136" font-size="96" font-family="Georgia,serif" fill="#203D35">Aa</text>{/if}</svg>{/if}</Link><div class="pictor-library-meta"><div><Link href={route.asset(asset.id)}><strong>{asset.name}</strong></Link><span>{$t(asset.kindKey)}</span></div><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-icon-button icon="add_circle" aria-label={$t('Add {name} to canvas', {name: asset.name})} on:click={() => insert(layerFromAsset(asset))}></md-icon-button></div></md-card>{/each}</div>{#if !assets.length}<div class="pictor-empty"><span class="material-symbols-outlined" aria-hidden="true">search_off</span><h3>{$t('No ingredients found')}</h3><p>{$t('Try a different name or asset type.')}</p></div>{:else}{#if assets.length > limit}<div class="pictor-library-more"><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="outlined" icon="expand_more" on:click={() => setLimit(value => value + 24)}>{$t('Explore more assets')}</md-button></div>{/if}{/if}</section> <svelte:fragment slot="aside"><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="tonal" icon="arrow_outward" on:click={() => navigate(route.editor())}>{$t('Back to studio')}</md-button></svelte:fragment></Screen>
