<script lang="ts">
import {editIcon,fileById,getFiles,getProjects,getTotals,getViewer,recentFiles,sharedFiles} from '@awc-ui/showcase-kit/design';
import Screen from '$lib/screens/Screen.svelte';
import ChoiceTabs from '$lib/editor/ChoiceTabs.svelte';
import TextControl from '$lib/editor/TextControl.svelte';
import {documentSvg} from '@awc-ui/pictor-model';
import {route} from '$lib/routes';
import {document} from '$lib/document'; import {t} from '$lib/showcase'; import {navigate} from '$lib/router'; import Link from '$lib/components/Link.svelte';
$: viewer = getViewer();
$: totals = getTotals();
$: projects = getProjects();
let view: any = 'recent'; const setView = (value: any) => view = typeof value === "function" ? value(view) : value;
let query: any = ''; const setQuery = (value: any) => query = typeof value === "function" ? value(query) : value;
$: currentFile = fileById($document.fileId);
$: files = (() => (view === 'shared' ? sharedFiles() : recentFiles(12)).filter(file => file.name.toLowerCase().includes(query.toLowerCase())).slice(0, 8))();
$: entries = $document.history.entries.slice(0, $document.history.index).slice(-4).reverse();
$: preview = (fileId: string) => `data:image/svg+xml,${encodeURIComponent(documentSvg($document.layersForFile(fileId), $t))}`;
$: metrics = [
    { label: $t('Projects'), value: totals.projects, icon: 'folder_open' },
    { label: $t('Design files'), value: totals.files, icon: 'draft' },
    { label: $t('Layers'), value: getFiles().reduce((count, file) => count + $document.layersForFile(file.id).length, 0), icon: 'layers' },
    { label: $t('Components'), value: totals.components, icon: 'deployed_code' },
    { label: $t('Assets'), value: totals.assets, icon: 'interests' },
  ];
</script>
<Screen title={$t('Your creative space')} subtitle={$t('The things you\'re making, and the possibilities ahead.')}> <div class="pictor-profile" data-profile> <section class="pictor-profile-identity" aria-label={$t('Your profile')}> <div class="pictor-profile-identity__person"><md-avatar src={viewer.art.src} name={viewer.displayName} label={$t(viewer.art.altKey)} size="large"></md-avatar><div><span class="pictor-profile-eyebrow">{$t('YOUR CORNER OF PICTOR')}</span><h2>{viewer.displayName}</h2><p>@{viewer.handle} <span aria-hidden="true">·</span> {$t('A little curiosity goes a long way.')}</p></div></div> <div class="pictor-profile-identity__art" aria-hidden="true"><svg viewBox="0 0 210 140"><circle cx="67" cy="70" r="49" fill="#BEE7AA"></circle><rect x="82" y="20" width="89" height="100" rx="44" fill="none" stroke="#C2BBF3" stroke-width="20" transform="rotate(30 125 70)"></rect><circle cx="174" cy="113" r="11" fill="#F2AAA7"></circle></svg><span>{$t('ROOM FOR YOUR NEXT BIG IDEA')}</span></div> </section> <section class="pictor-profile-metrics" aria-label={$t('Workspace library overview')}>{#each metrics as metric}<div class="pictor-profile-metric"><span class="material-symbols-outlined" aria-hidden="true">{metric.icon}</span><strong>{$t.formatNumber(metric.value)}</strong><span>{metric.label}</span></div>{/each}</section> {#if currentFile}<md-card class="pictor-profile-resume" variant="outlined"><Link class="pictor-profile-resume__preview" href={route.editor()} aria-label={$t('Continue editing {name}', {name: currentFile.name})}><img src={preview(currentFile.id)} alt={$t('{name} current canvas', {name: currentFile.name})} /></Link><div class="pictor-profile-resume__copy"><span class="pictor-profile-eyebrow">{$t('RIGHT WHERE YOU LEFT OFF')}</span><h2>{currentFile.name}</h2><p>{$t('Your canvas is waiting. Pick up a detail, follow an idea, or take the whole thing somewhere new.')}</p><div class="pictor-profile-resume__details"><span><span class="material-symbols-outlined" aria-hidden="true">layers</span>{$document.layers.length} {$t('editable layers')}</span><span><span class="material-symbols-outlined" aria-hidden="true">history</span>{$document.history.index} {$t('reversible edits')}</span></div><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="filled" icon="arrow_forward" on:click={() => navigate(route.editor())}>{$t('Continue designing')}</md-button></div></md-card>{/if} <div class="pictor-profile-workspace"> <section class="pictor-profile-files"><div class="pictor-profile-section-head"><div><span class="pictor-profile-eyebrow">{$t('KEEP YOUR MOMENTUM')}</span><h2>{$t('Your design files')}</h2></div><ChoiceTabs label={$t('Profile file view')} value={view} onValue={setView} options={[{ value: 'recent', label: $t('Recent') }, { value: 'shared', label: $t('With others') }]}></ChoiceTabs></div><TextControl live label={$t('Find a design file')} value={query} onValue={setQuery}></TextControl> <div class="pictor-profile-file-list">{#each files as file}<Link href={route.file(file.id)} class="pictor-profile-file"><img src={preview(file.id)} alt="" loading="lazy" /><div><strong>{file.name}</strong><span>{projects.find(project => project.id === file.projectId)?.name} <span aria-hidden="true">·</span> {$document.layersForFile(file.id).length} {$t('layers')}</span></div><md-chip label={$t(file.stateKey)}></md-chip><span class="material-symbols-outlined pictor-profile-file__arrow" aria-hidden="true">arrow_outward</span></Link>{/each}</div>{#if !files.length}<div class="pictor-profile-empty"><span class="material-symbols-outlined" aria-hidden="true">search_off</span><h3>{$t('No designs in this view')}</h3><p>{$t('Try another name or return to your recent files.')}</p><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="text" on:click={() => { setQuery(''); setView('recent'); }}>{$t('Show recent files')}</md-button></div>{/if} </section> <aside class="pictor-profile-sidebar"> <md-card class="pictor-profile-activity" variant="outlined"><div class="pictor-profile-section-head"><h2>{$t('A little progress')}</h2><span class="material-symbols-outlined" aria-hidden="true">history</span></div><p class="pictor-profile-note">{$t('Recent changes on your current canvas.')}</p>{#if entries.length}<ol>{#each entries as entry}<li><span class="material-symbols-outlined" aria-hidden="true">{editIcon(entry.kind)}</span><div><strong>{$t(entry.labelKey)}</strong><span>{entry.after[0]?.name ?? entry.before[0]?.name ?? $t('Canvas')}</span></div></li>{/each}</ol>{:else}<div class="pictor-profile-first-step"><span class="material-symbols-outlined" aria-hidden="true">draw</span><p>{$t('Every good idea starts with a first move.')}</p><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="text" on:click={() => navigate(route.editor())}>{$t('Make your first edit')}</md-button></div>{/if}</md-card> <md-card class="pictor-profile-saved" variant="filled"><span class="material-symbols-outlined" aria-hidden="true">{#if $document.saveStatus === 'unavailable'}{'cloud_off'}{:else}{'check_circle'}{/if}</span><h3>{#if $document.saveStatus === 'unavailable'}{$t('Keep a copy of your work')}{:else}{$t('Your ideas stay with you.')}{/if}</h3><p>{#if $document.saveStatus === 'unavailable'}{$t('Export your current canvas to keep it beyond this session.')}{:else}{$t('Your canvases and their history are saved in this browser, ready for your next visit.')}{/if}</p><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="text" icon={$document.saveStatus === 'unavailable' ? 'download' : 'save'} on:click={() => { if ($document.saveStatus === 'unavailable') {
    navigate(route.editor());
    setTimeout(() => window.dispatchEvent(new Event('pictor:export')), 120);
}
else
    $document.save(); }}>{#if $document.saveStatus === 'unavailable'}{$t('Export a copy')}{:else}{$t('Save workspace')}{/if}</md-button></md-card> <Link class="pictor-profile-library-link" href={route.assets()}><span class="material-symbols-outlined" aria-hidden="true">interests</span><div><strong>{$t('A new ingredient?')}</strong><span>{$t('Explore your creative library')}</span></div><span class="material-symbols-outlined" aria-hidden="true">arrow_forward</span></Link> </aside> </div> </div> <svelte:fragment slot="aside"><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="tonal" icon="arrow_outward" on:click={() => navigate(route.editor())}>{$t('Open the studio')}</md-button></svelte:fragment></Screen>
