import type { Entry } from '../index';

/** Accordion demo strings. Keys are namespaced by the component slug
 *  (`accordion.*`). Shared verbs (e.g. `settings`) are reused from
 *  `common.ts` — not redefined here. `en-US` values are byte-identical to
 *  the original hard-coded story text so play() and visual baselines hold. */
export const messages: Record<string, Entry> = {
  // ── Section / item headlines ──────────────────────────────
  'accordion.account': { 'en-US': 'Account', 'ar-SA': 'الحساب', 'he-IL': 'חשבון', 'ja-JP': 'アカウント', 'de-DE': 'Konto', 'fr-FR': 'Compte', 'zh-CN': '账户' },
  'accordion.notifications': { 'en-US': 'Notifications', 'ar-SA': 'الإشعارات', 'he-IL': 'התראות', 'ja-JP': '通知', 'de-DE': 'Benachrichtigungen', 'fr-FR': 'Notifications', 'zh-CN': '通知' },
  'accordion.billing': { 'en-US': 'Billing', 'ar-SA': 'الفوترة', 'he-IL': 'חיוב', 'ja-JP': '請求', 'de-DE': 'Abrechnung', 'fr-FR': 'Facturation', 'zh-CN': '账单' },
  'accordion.profile': { 'en-US': 'Profile', 'ar-SA': 'الملف الشخصي', 'he-IL': 'פרופיל', 'ja-JP': 'プロフィール', 'de-DE': 'Profil', 'fr-FR': 'Profil', 'zh-CN': '个人资料' },
  'accordion.security': { 'en-US': 'Security', 'ar-SA': 'الأمان', 'he-IL': 'אבטחה', 'ja-JP': 'セキュリティ', 'de-DE': 'Sicherheit', 'fr-FR': 'Sécurité', 'zh-CN': '安全' },
  'accordion.integrations': { 'en-US': 'Integrations', 'ar-SA': 'التكاملات', 'he-IL': 'אינטגרציות', 'ja-JP': '連携', 'de-DE': 'Integrationen', 'fr-FR': 'Intégrations', 'zh-CN': '集成' },
  'accordion.shipping': { 'en-US': 'Shipping', 'ar-SA': 'الشحن', 'he-IL': 'משלוח', 'ja-JP': '配送', 'de-DE': 'Versand', 'fr-FR': 'Expédition', 'zh-CN': '配送' },
  'accordion.review': { 'en-US': 'Review', 'ar-SA': 'المراجعة', 'he-IL': 'סקירה', 'ja-JP': '確認', 'de-DE': 'Überprüfung', 'fr-FR': 'Récapitulatif', 'zh-CN': '确认' },
  'accordion.personalInfo': { 'en-US': 'Personal info', 'ar-SA': 'المعلومات الشخصية', 'he-IL': 'פרטים אישיים', 'ja-JP': '個人情報', 'de-DE': 'Persönliche Daten', 'fr-FR': 'Informations personnelles', 'zh-CN': '个人信息' },
  'accordion.currentPlan': { 'en-US': 'Current plan', 'ar-SA': 'الخطة الحالية', 'he-IL': 'התוכנית הנוכחית', 'ja-JP': '現在のプラン', 'de-DE': 'Aktueller Tarif', 'fr-FR': 'Forfait actuel', 'zh-CN': '当前套餐' },
  'accordion.paymentMethod': { 'en-US': 'Payment method', 'ar-SA': 'طريقة الدفع', 'he-IL': 'אמצעי תשלום', 'ja-JP': '支払い方法', 'de-DE': 'Zahlungsmethode', 'fr-FR': 'Moyen de paiement', 'zh-CN': '支付方式' },
  'accordion.subscriptionDetails': { 'en-US': 'Subscription details', 'ar-SA': 'تفاصيل الاشتراك', 'he-IL': 'פרטי המנוי', 'ja-JP': 'サブスクリプションの詳細', 'de-DE': 'Abodetails', 'fr-FR': 'Détails de l\'abonnement', 'zh-CN': '订阅详情' },
  'accordion.available': { 'en-US': 'Available', 'ar-SA': 'متاح', 'he-IL': 'זמין', 'ja-JP': '利用可能', 'de-DE': 'Verfügbar', 'fr-FR': 'Disponible', 'zh-CN': '可用' },
  'accordion.comingSoon': { 'en-US': 'Coming soon', 'ar-SA': 'قريباً', 'he-IL': 'בקרוב', 'ja-JP': '近日公開', 'de-DE': 'Demnächst', 'fr-FR': 'Bientôt disponible', 'zh-CN': '即将推出' },
  'accordion.whatsNew': { 'en-US': 'What\'s new', 'ar-SA': 'ما الجديد', 'he-IL': 'מה חדש', 'ja-JP': '新着情報', 'de-DE': 'Neuigkeiten', 'fr-FR': 'Nouveautés', 'zh-CN': '新功能' },
  'accordion.knownIssues': { 'en-US': 'Known issues', 'ar-SA': 'المشكلات المعروفة', 'he-IL': 'תקלות ידועות', 'ja-JP': '既知の問題', 'de-DE': 'Bekannte Probleme', 'fr-FR': 'Problèmes connus', 'zh-CN': '已知问题' },
  'accordion.roadmap': { 'en-US': 'Roadmap', 'ar-SA': 'خارطة الطريق', 'he-IL': 'מפת דרכים', 'ja-JP': 'ロードマップ', 'de-DE': 'Roadmap', 'fr-FR': 'Feuille de route', 'zh-CN': '路线图' },
  'accordion.accountProfile': { 'en-US': 'Account & profile', 'ar-SA': 'الحساب والملف الشخصي', 'he-IL': 'חשבון ופרופיל', 'ja-JP': 'アカウントとプロフィール', 'de-DE': 'Konto & Profil', 'fr-FR': 'Compte et profil', 'zh-CN': '账户与个人资料' },
  'accordion.billingSubscription': { 'en-US': 'Billing & subscription', 'ar-SA': 'الفوترة والاشتراك', 'he-IL': 'חיוב ומנוי', 'ja-JP': '請求とサブスクリプション', 'de-DE': 'Abrechnung & Abo', 'fr-FR': 'Facturation et abonnement', 'zh-CN': '账单与订阅' },

  // ── Supporting text ───────────────────────────────────────
  'accordion.emailPassword': { 'en-US': 'Email & password', 'ar-SA': 'البريد وكلمة السر', 'he-IL': 'אימייל וסיסמה', 'ja-JP': 'メールとパスワード', 'de-DE': 'E-Mail & Passwort', 'fr-FR': 'E-mail et mot de passe', 'zh-CN': '邮箱和密码' },
  'accordion.emailPassword2fa': { 'en-US': 'Email, password, 2FA.', 'ar-SA': 'البريد، كلمة السر، المصادقة الثنائية.', 'he-IL': 'אימייל, סיסמה, אימות דו-שלבי.', 'ja-JP': 'メール、パスワード、2 段階認証。', 'de-DE': 'E-Mail, Passwort, 2FA.', 'fr-FR': 'E-mail, mot de passe, 2FA.', 'zh-CN': '邮箱、密码、双重认证。' },
  'accordion.emailDigestPush': { 'en-US': 'Email digest, push.', 'ar-SA': 'ملخص بريدي، إشعارات فورية.', 'he-IL': 'תקציר במייל, התראות דחיפה.', 'ja-JP': 'メール要約、プッシュ。', 'de-DE': 'E-Mail-Zusammenfassung, Push.', 'fr-FR': 'Résumé par e-mail, push.', 'zh-CN': '邮件摘要、推送。' },
  'accordion.availableInV2': { 'en-US': 'Available in v2.0', 'ar-SA': 'متاح في الإصدار 2.0', 'he-IL': 'זמין בגרסה 2.0', 'ja-JP': 'v2.0 で利用可能', 'de-DE': 'Verfügbar in v2.0', 'fr-FR': 'Disponible dans la v2.0', 'zh-CN': 'v2.0 中提供' },
  'accordion.respAccountSupporting': { 'en-US': 'Email, password, two-factor authentication', 'ar-SA': 'البريد الإلكتروني، كلمة السر، المصادقة الثنائية', 'he-IL': 'אימייל, סיסמה, אימות דו-שלבי', 'ja-JP': 'メール、パスワード、二段階認証', 'de-DE': 'E-Mail, Passwort, Zwei-Faktor-Authentifizierung', 'fr-FR': 'E-mail, mot de passe, authentification à deux facteurs', 'zh-CN': '邮箱、密码、双重身份验证' },
  'accordion.respNotifSupporting': { 'en-US': 'Email digest · Push · In-app', 'ar-SA': 'ملخص بريدي · إشعارات فورية · داخل التطبيق', 'he-IL': 'תקציר במייל · דחיפה · באפליקציה', 'ja-JP': 'メール要約 · プッシュ · アプリ内', 'de-DE': 'E-Mail-Zusammenfassung · Push · In-App', 'fr-FR': 'Résumé par e-mail · Push · In-app', 'zh-CN': '邮件摘要 · 推送 · 应用内' },

  // ── Wizard step headlines ─────────────────────────────────
  'accordion.step1': { 'en-US': 'Step 1: Personal information', 'ar-SA': 'الخطوة 1: المعلومات الشخصية', 'he-IL': 'שלב 1: פרטים אישיים', 'ja-JP': 'ステップ 1: 個人情報', 'de-DE': 'Schritt 1: Persönliche Daten', 'fr-FR': 'Étape 1 : Informations personnelles', 'zh-CN': '第 1 步：个人信息' },
  'accordion.step2': { 'en-US': 'Step 2: Shipping address', 'ar-SA': 'الخطوة 2: عنوان الشحن', 'he-IL': 'שלב 2: כתובת למשלוח', 'ja-JP': 'ステップ 2: 配送先住所', 'de-DE': 'Schritt 2: Lieferadresse', 'fr-FR': 'Étape 2 : Adresse de livraison', 'zh-CN': '第 2 步：收货地址' },
  'accordion.step3': { 'en-US': 'Step 3: Review', 'ar-SA': 'الخطوة 3: المراجعة', 'he-IL': 'שלב 3: סקירה', 'ja-JP': 'ステップ 3: 確認', 'de-DE': 'Schritt 3: Überprüfung', 'fr-FR': 'Étape 3 : Récapitulatif', 'zh-CN': '第 3 步：确认' },

  // ── Body copy ─────────────────────────────────────────────
  'accordion.accountBody': { 'en-US': 'Update your email address, change your password, manage two-factor authentication.', 'ar-SA': 'حدّث عنوان بريدك الإلكتروني، وغيّر كلمة السر، وأدر المصادقة الثنائية.', 'he-IL': 'עדכן את כתובת האימייל, שנה סיסמה ונהל אימות דו-שלבי.', 'ja-JP': 'メールアドレスの更新、パスワードの変更、2 段階認証の管理を行えます。', 'de-DE': 'Aktualisieren Sie Ihre E-Mail-Adresse, ändern Sie Ihr Passwort und verwalten Sie die Zwei-Faktor-Authentifizierung.', 'fr-FR': 'Modifiez votre adresse e-mail, changez votre mot de passe et gérez l\'authentification à deux facteurs.', 'zh-CN': '更新您的邮箱地址、更改密码、管理双重认证。' },
  'accordion.notificationsBody': { 'en-US': 'Email digest, in-app banners, mobile push.', 'ar-SA': 'ملخص بريدي، لافتات داخل التطبيق، إشعارات الجوال.', 'he-IL': 'תקציר במייל, באנרים באפליקציה, התראות בנייד.', 'ja-JP': 'メール要約、アプリ内バナー、モバイルプッシュ。', 'de-DE': 'E-Mail-Zusammenfassung, In-App-Banner, mobile Push-Nachrichten.', 'fr-FR': 'Résumé par e-mail, bannières in-app, notifications mobiles.', 'zh-CN': '邮件摘要、应用内横幅、移动推送。' },
  'accordion.notificationsBodyShort': { 'en-US': 'Email, push, in-app.', 'ar-SA': 'البريد، الإشعارات الفورية، داخل التطبيق.', 'he-IL': 'אימייל, דחיפה, באפליקציה.', 'ja-JP': 'メール、プッシュ、アプリ内。', 'de-DE': 'E-Mail, Push, In-App.', 'fr-FR': 'E-mail, push, in-app.', 'zh-CN': '邮件、推送、应用内。' },
  'accordion.billingBody': { 'en-US': 'Plan, invoices, payment method on file.', 'ar-SA': 'الخطة، الفواتير، وسيلة الدفع المحفوظة.', 'he-IL': 'תוכנית, חשבוניות, אמצעי תשלום שמור.', 'ja-JP': 'プラン、請求書、登録済みの支払い方法。', 'de-DE': 'Tarif, Rechnungen, hinterlegte Zahlungsmethode.', 'fr-FR': 'Forfait, factures, moyen de paiement enregistré.', 'zh-CN': '套餐、发票、已保存的支付方式。' },
  'accordion.profileBody': { 'en-US': 'Display name, avatar, bio.', 'ar-SA': 'الاسم الظاهر، الصورة الرمزية، النبذة.', 'he-IL': 'שם תצוגה, תמונת פרופיל, אודות.', 'ja-JP': '表示名、アバター、自己紹介。', 'de-DE': 'Anzeigename, Avatar, Bio.', 'fr-FR': 'Nom d\'affichage, avatar, bio.', 'zh-CN': '显示名称、头像、简介。' },
  'accordion.securityBody': { 'en-US': 'Password, sessions, devices.', 'ar-SA': 'كلمة السر، الجلسات، الأجهزة.', 'he-IL': 'סיסמה, הפעלות, מכשירים.', 'ja-JP': 'パスワード、セッション、デバイス。', 'de-DE': 'Passwort, Sitzungen, Geräte.', 'fr-FR': 'Mot de passe, sessions, appareils.', 'zh-CN': '密码、会话、设备。' },
  'accordion.keepOneAccountBody': { 'en-US': 'Try to close every panel — you can\'t close the last one.', 'ar-SA': 'حاول إغلاق كل لوحة — لا يمكنك إغلاق الأخيرة.', 'he-IL': 'נסה לסגור כל פאנל — אי אפשר לסגור את האחרון.', 'ja-JP': 'すべてのパネルを閉じてみてください — 最後の 1 つは閉じられません。', 'de-DE': 'Versuchen Sie, alle Bereiche zu schließen — den letzten können Sie nicht schließen.', 'fr-FR': 'Essayez de fermer tous les panneaux — impossible de fermer le dernier.', 'zh-CN': '试着关闭每个面板 — 最后一个无法关闭。' },
  'accordion.planInvoices': { 'en-US': 'Plan & invoices.', 'ar-SA': 'الخطة والفواتير.', 'he-IL': 'תוכנית וחשבוניות.', 'ja-JP': 'プランと請求書。', 'de-DE': 'Tarif & Rechnungen.', 'fr-FR': 'Forfait et factures.', 'zh-CN': '套餐和发票。' },
  'accordion.personalInfoBody': { 'en-US': 'First name, last name, DOB.', 'ar-SA': 'الاسم الأول، اسم العائلة، تاريخ الميلاد.', 'he-IL': 'שם פרטי, שם משפחה, תאריך לידה.', 'ja-JP': '名、姓、生年月日。', 'de-DE': 'Vorname, Nachname, Geburtsdatum.', 'fr-FR': 'Prénom, nom, date de naissance.', 'zh-CN': '名、姓、出生日期。' },
  'accordion.shippingBody': { 'en-US': 'Address & delivery preferences.', 'ar-SA': 'العنوان وتفضيلات التوصيل.', 'he-IL': 'כתובת והעדפות משלוח.', 'ja-JP': '住所と配送設定。', 'de-DE': 'Adresse & Lieferpräferenzen.', 'fr-FR': 'Adresse et préférences de livraison.', 'zh-CN': '地址和配送偏好。' },
  'accordion.orderSummary': { 'en-US': 'Order summary.', 'ar-SA': 'ملخص الطلب.', 'he-IL': 'סיכום הזמנה.', 'ja-JP': '注文の概要。', 'de-DE': 'Bestellübersicht.', 'fr-FR': 'Récapitulatif de la commande.', 'zh-CN': '订单摘要。' },
  'accordion.clickToExpand': { 'en-US': 'Click to expand.', 'ar-SA': 'انقر للتوسيع.', 'he-IL': 'לחץ להרחבה.', 'ja-JP': 'クリックで展開。', 'de-DE': 'Zum Aufklappen klicken.', 'fr-FR': 'Cliquez pour développer.', 'zh-CN': '点击展开。' },
  'accordion.cantSeeMe': { 'en-US': 'You can\'t see me.', 'ar-SA': 'لا يمكنك رؤيتي.', 'he-IL': 'אינך יכול לראות אותי.', 'ja-JP': 'あなたには私が見えません。', 'de-DE': 'Du kannst mich nicht sehen.', 'fr-FR': 'Vous ne pouvez pas me voir.', 'zh-CN': '你看不见我。' },
  'accordion.darkModeBody': { 'en-US': 'Dark mode landed in 1.2 along with system-preference auto-detection.', 'ar-SA': 'وصل الوضع الداكن في الإصدار 1.2 مع الاكتشاف التلقائي لتفضيلات النظام.', 'he-IL': 'מצב כהה הושק בגרסה 1.2 יחד עם זיהוי אוטומטי של העדפות המערכת.', 'ja-JP': 'ダークモードは 1.2 で、システム設定の自動検出とともに追加されました。', 'de-DE': 'Der Dunkelmodus kam in 1.2 zusammen mit der automatischen Erkennung der Systemeinstellungen.', 'fr-FR': 'Le mode sombre est arrivé en 1.2, avec la détection automatique des préférences système.', 'zh-CN': '深色模式在 1.2 版本中随系统偏好自动检测一同推出。' },
  'accordion.knownIssuesBody': { 'en-US': 'Tabs flicker briefly when switching themes mid-animation.', 'ar-SA': 'تومض علامات التبويب لحظياً عند تبديل السمة أثناء الحركة.', 'he-IL': 'הכרטיסיות מהבהבות לרגע בעת החלפת ערכת נושא באמצע אנימציה.', 'ja-JP': 'アニメーション中にテーマを切り替えるとタブが一瞬ちらつきます。', 'de-DE': 'Tabs flackern kurz, wenn das Theme mitten in der Animation gewechselt wird.', 'fr-FR': 'Les onglets clignotent brièvement lors du changement de thème en pleine animation.', 'zh-CN': '在动画过程中切换主题时，标签页会短暂闪烁。' },
  'accordion.roadmapBody': { 'en-US': 'Q3 we ship the redesigned settings shell.', 'ar-SA': 'في الربع الثالث نُطلق واجهة الإعدادات المُعاد تصميمها.', 'he-IL': 'ברבעון השלישי נשיק את מעטפת ההגדרות המעוצבת מחדש.', 'ja-JP': '第 3 四半期に、再設計した設定シェルをリリースします。', 'de-DE': 'Im 3. Quartal veröffentlichen wir die neu gestaltete Einstellungsoberfläche.', 'fr-FR': 'Au T3, nous lançons l\'interface des paramètres repensée.', 'zh-CN': '我们将在第三季度发布重新设计的设置外壳。' },
  'accordion.respAccountBody': { 'en-US': 'Manage your sign-in credentials, recovery email, and security keys. Changes take effect on every signed-in device after the next page load.', 'ar-SA': 'أدر بيانات تسجيل الدخول، وبريد الاسترداد، ومفاتيح الأمان. تسري التغييرات على كل جهاز مُسجَّل الدخول بعد التحميل التالي للصفحة.', 'he-IL': 'נהל את פרטי ההתחברות, אימייל השחזור ומפתחות האבטחה. השינויים ייכנסו לתוקף בכל מכשיר מחובר לאחר טעינת העמוד הבאה.', 'ja-JP': 'サインイン情報、復旧用メール、セキュリティキーを管理します。変更は次回のページ読み込み後、サインイン中のすべてのデバイスに反映されます。', 'de-DE': 'Verwalten Sie Ihre Anmeldedaten, die Wiederherstellungs-E-Mail und Sicherheitsschlüssel. Änderungen werden auf jedem angemeldeten Gerät nach dem nächsten Laden der Seite wirksam.', 'fr-FR': 'Gérez vos identifiants de connexion, votre e-mail de récupération et vos clés de sécurité. Les modifications prennent effet sur chaque appareil connecté au prochain chargement de page.', 'zh-CN': '管理您的登录凭据、恢复邮箱和安全密钥。更改将在下次页面加载后对每台已登录设备生效。' },
  'accordion.respNotifBody': { 'en-US': 'Choose which events trigger a notification on each channel. Critical security alerts cannot be disabled.', 'ar-SA': 'اختر الأحداث التي تُطلق إشعاراً على كل قناة. لا يمكن تعطيل تنبيهات الأمان الحرجة.', 'he-IL': 'בחר אילו אירועים מפעילים התראה בכל ערוץ. לא ניתן לבטל התראות אבטחה קריטיות.', 'ja-JP': '各チャネルで通知を発生させるイベントを選択します。重要なセキュリティ警告は無効にできません。', 'de-DE': 'Wählen Sie, welche Ereignisse auf jedem Kanal eine Benachrichtigung auslösen. Kritische Sicherheitswarnungen können nicht deaktiviert werden.', 'fr-FR': 'Choisissez les événements qui déclenchent une notification sur chaque canal. Les alertes de sécurité critiques ne peuvent pas être désactivées.', 'zh-CN': '选择在每个渠道触发通知的事件。关键安全警报无法禁用。' },
  'accordion.respBillingBody': { 'en-US': 'View past invoices, update your payment method, or change your plan. Cancellations apply at the end of the current billing cycle.', 'ar-SA': 'اعرض الفواتير السابقة، أو حدّث وسيلة الدفع، أو غيّر خطتك. تسري الإلغاءات في نهاية دورة الفوترة الحالية.', 'he-IL': 'צפה בחשבוניות קודמות, עדכן את אמצעי התשלום או שנה תוכנית. ביטולים ייכנסו לתוקף בסוף מחזור החיוב הנוכחי.', 'ja-JP': '過去の請求書の表示、支払い方法の更新、プランの変更ができます。解約は現在の請求サイクルの終了時に適用されます。', 'de-DE': 'Sehen Sie sich frühere Rechnungen an, aktualisieren Sie Ihre Zahlungsmethode oder ändern Sie Ihren Tarif. Kündigungen werden zum Ende des aktuellen Abrechnungszeitraums wirksam.', 'fr-FR': 'Consultez vos factures passées, mettez à jour votre moyen de paiement ou changez de forfait. Les résiliations prennent effet à la fin du cycle de facturation en cours.', 'zh-CN': '查看过往发票、更新支付方式或更改套餐。取消将在当前账单周期结束时生效。' },
};
