import type { Entry } from '../index';

/** Per-component demo strings for the Dialog stories. Shared verbs
 *  (save, cancel, delete) live in `common.ts` and are reused via
 *  `t(locale, '<verb>')` — only dialog-specific copy is defined here.
 *  The Localization and RTL stories intentionally showcase the component's
 *  own `locale`/`dir` handling with fixed-language content, so they are NOT
 *  routed through this catalog. */
export const messages: Record<string, Entry> = {
  // ── Trigger buttons ──────────────────────────────────────────────
  'dialog.openDialog': { 'en-US': 'Open Dialog', 'ar-SA': 'فتح مربع الحوار', 'he-IL': 'פתיחת דו-שיח', 'ja-JP': 'ダイアログを開く', 'de-DE': 'Dialog öffnen', 'fr-FR': 'Ouvrir la boîte de dialogue', 'zh-CN': '打开对话框' },
  'dialog.openBasic': { 'en-US': 'Open Basic Dialog', 'ar-SA': 'فتح مربع حوار أساسي', 'he-IL': 'פתיחת דו-שיח בסיסי', 'ja-JP': '基本ダイアログを開く', 'de-DE': 'Basisdialog öffnen', 'fr-FR': 'Ouvrir la boîte de dialogue de base', 'zh-CN': '打开基本对话框' },
  'dialog.deleteDialogBtn': { 'en-US': 'Delete Dialog', 'ar-SA': 'مربع حوار الحذف', 'he-IL': 'דו-שיח מחיקה', 'ja-JP': '削除ダイアログ', 'de-DE': 'Löschdialog', 'fr-FR': 'Boîte de dialogue de suppression', 'zh-CN': '删除对话框' },
  'dialog.warningDialogBtn': { 'en-US': 'Warning Dialog', 'ar-SA': 'مربع حوار التحذير', 'he-IL': 'דו-שיח אזהרה', 'ja-JP': '警告ダイアログ', 'de-DE': 'Warndialog', 'fr-FR': 'Boîte de dialogue d\'avertissement', 'zh-CN': '警告对话框' },
  'dialog.customSvgIcon': { 'en-US': 'Custom SVG Icon', 'ar-SA': 'أيقونة SVG مخصصة', 'he-IL': 'סמל SVG מותאם אישית', 'ja-JP': 'カスタム SVG アイコン', 'de-DE': 'Benutzerdefiniertes SVG-Symbol', 'fr-FR': 'Icône SVG personnalisée', 'zh-CN': '自定义 SVG 图标' },
  'dialog.termsConditionsBtn': { 'en-US': 'Terms & Conditions', 'ar-SA': 'الشروط والأحكام', 'he-IL': 'תנאים והגבלות', 'ja-JP': '利用規約', 'de-DE': 'Geschäftsbedingungen', 'fr-FR': 'Conditions générales', 'zh-CN': '条款和条件' },
  'dialog.openFullscreen': { 'en-US': 'Open Full-screen Dialog', 'ar-SA': 'فتح مربع حوار بملء الشاشة', 'he-IL': 'פתיחת דו-שיח במסך מלא', 'ja-JP': '全画面ダイアログを開く', 'de-DE': 'Vollbild-Dialog öffnen', 'fr-FR': 'Ouvrir la boîte de dialogue plein écran', 'zh-CN': '打开全屏对话框' },
  'dialog.openBtn': { 'en-US': 'Open', 'ar-SA': 'فتح', 'he-IL': 'פתיחה', 'ja-JP': '開く', 'de-DE': 'Öffnen', 'fr-FR': 'Ouvrir', 'zh-CN': '打开' },
  'dialog.closeExternal': { 'en-US': 'Close (external)', 'ar-SA': 'إغلاق (خارجي)', 'he-IL': 'סגירה (חיצוני)', 'ja-JP': '閉じる（外部）', 'de-DE': 'Schließen (extern)', 'fr-FR': 'Fermer (externe)', 'zh-CN': '关闭（外部）' },
  'dialog.nonDismissibleBtn': { 'en-US': 'Non-dismissible Dialog', 'ar-SA': 'مربع حوار غير قابل للإغلاق', 'he-IL': 'דו-שיח שלא ניתן לסגירה', 'ja-JP': '閉じられないダイアログ', 'de-DE': 'Nicht schließbarer Dialog', 'fr-FR': 'Boîte de dialogue non fermable', 'zh-CN': '不可关闭的对话框' },
  'dialog.openDark': { 'en-US': 'Open Dark Dialog', 'ar-SA': 'فتح مربع حوار داكن', 'he-IL': 'פתיחת דו-שיח כהה', 'ja-JP': 'ダークダイアログを開く', 'de-DE': 'Dunklen Dialog öffnen', 'fr-FR': 'Ouvrir la boîte de dialogue sombre', 'zh-CN': '打开深色对话框' },
  'dialog.openAccessible': { 'en-US': 'Open Accessible Dialog', 'ar-SA': 'فتح مربع حوار متاح للوصول', 'he-IL': 'פתיחת דו-שיח נגיש', 'ja-JP': 'アクセシブルなダイアログを開く', 'de-DE': 'Barrierefreien Dialog öffnen', 'fr-FR': 'Ouvrir la boîte de dialogue accessible', 'zh-CN': '打开无障碍对话框' },
  'dialog.dangerStyleBtn': { 'en-US': 'Danger Style', 'ar-SA': 'نمط الخطر', 'he-IL': 'סגנון סכנה', 'ja-JP': '危険なスタイル', 'de-DE': 'Gefahren-Stil', 'fr-FR': 'Style danger', 'zh-CN': '危险样式' },
  'dialog.customShapeBtn': { 'en-US': 'Custom Shape', 'ar-SA': 'شكل مخصص', 'he-IL': 'צורה מותאמת אישית', 'ja-JP': 'カスタム形状', 'de-DE': 'Benutzerdefinierte Form', 'fr-FR': 'Forme personnalisée', 'zh-CN': '自定义形状' },

  // ── Dialog headlines ─────────────────────────────────────────────
  'dialog.discardDraft': { 'en-US': 'Discard draft?', 'ar-SA': 'تجاهل المسودة؟', 'he-IL': 'לבטל את הטיוטה?', 'ja-JP': '下書きを破棄しますか？', 'de-DE': 'Entwurf verwerfen?', 'fr-FR': 'Supprimer le brouillon ?', 'zh-CN': '放弃草稿？' },
  'dialog.deleteFile': { 'en-US': 'Delete file?', 'ar-SA': 'حذف الملف؟', 'he-IL': 'למחוק את הקובץ?', 'ja-JP': 'ファイルを削除しますか？', 'de-DE': 'Datei löschen?', 'fr-FR': 'Supprimer le fichier ?', 'zh-CN': '删除文件？' },
  'dialog.connectionLost': { 'en-US': 'Connection lost', 'ar-SA': 'انقطع الاتصال', 'he-IL': 'החיבור אבד', 'ja-JP': '接続が切断されました', 'de-DE': 'Verbindung verloren', 'fr-FR': 'Connexion perdue', 'zh-CN': '连接已断开' },
  'dialog.starItem': { 'en-US': 'Star this item?', 'ar-SA': 'تمييز هذا العنصر بنجمة؟', 'he-IL': 'לסמן פריט זה בכוכב?', 'ja-JP': 'このアイテムにスターを付けますか？', 'de-DE': 'Dieses Element mit Stern markieren?', 'fr-FR': 'Marquer cet élément d\'une étoile ?', 'zh-CN': '为该项目加星标？' },
  'dialog.termsOfService': { 'en-US': 'Terms of Service', 'ar-SA': 'شروط الخدمة', 'he-IL': 'תנאי השירות', 'ja-JP': '利用規約', 'de-DE': 'Nutzungsbedingungen', 'fr-FR': 'Conditions d\'utilisation', 'zh-CN': '服务条款' },
  'dialog.editProfile': { 'en-US': 'Edit profile', 'ar-SA': 'تعديل الملف الشخصي', 'he-IL': 'עריכת פרופיל', 'ja-JP': 'プロフィールを編集', 'de-DE': 'Profil bearbeiten', 'fr-FR': 'Modifier le profil', 'zh-CN': '编辑个人资料' },
  'dialog.confirmAction': { 'en-US': 'Confirm action', 'ar-SA': 'تأكيد الإجراء', 'he-IL': 'אישור פעולה', 'ja-JP': '操作を確認', 'de-DE': 'Aktion bestätigen', 'fr-FR': 'Confirmer l\'action', 'zh-CN': '确认操作' },
  'dialog.controlled': { 'en-US': 'Controlled dialog', 'ar-SA': 'مربع حوار متحكَّم به', 'he-IL': 'דו-שיח מבוקר', 'ja-JP': '制御されたダイアログ', 'de-DE': 'Gesteuerter Dialog', 'fr-FR': 'Boîte de dialogue contrôlée', 'zh-CN': '受控对话框' },
  'dialog.acceptTermsHeadline': { 'en-US': 'Accept terms to continue', 'ar-SA': 'اقبل الشروط للمتابعة', 'he-IL': 'קבל את התנאים כדי להמשיך', 'ja-JP': '続行するには規約に同意してください', 'de-DE': 'Bedingungen akzeptieren, um fortzufahren', 'fr-FR': 'Acceptez les conditions pour continuer', 'zh-CN': '接受条款以继续' },
  'dialog.darkMode': { 'en-US': 'Dark Mode', 'ar-SA': 'الوضع الداكن', 'he-IL': 'מצב כהה', 'ja-JP': 'ダークモード', 'de-DE': 'Dunkelmodus', 'fr-FR': 'Mode sombre', 'zh-CN': '深色模式' },
  'dialog.deleteProject': { 'en-US': 'Delete project?', 'ar-SA': 'حذف المشروع؟', 'he-IL': 'למחוק את הפרויקט?', 'ja-JP': 'プロジェクトを削除しますか？', 'de-DE': 'Projekt löschen?', 'fr-FR': 'Supprimer le projet ?', 'zh-CN': '删除项目？' },
  'dialog.dangerZone': { 'en-US': 'Danger zone', 'ar-SA': 'منطقة الخطر', 'he-IL': 'אזור סכנה', 'ja-JP': '危険ゾーン', 'de-DE': 'Gefahrenbereich', 'fr-FR': 'Zone dangereuse', 'zh-CN': '危险区域' },

  // ── Body copy ────────────────────────────────────────────────────
  'dialog.playgroundBody': { 'en-US': 'This is the dialog body content. It can contain any text, forms, or other elements.', 'ar-SA': 'هذا هو محتوى نص مربع الحوار. يمكن أن يحتوي على أي نص أو نماذج أو عناصر أخرى.', 'he-IL': 'זהו תוכן גוף הדו-שיח. הוא יכול להכיל טקסט, טפסים או רכיבים אחרים.', 'ja-JP': 'これはダイアログの本文コンテンツです。テキスト、フォーム、その他の要素を含めることができます。', 'de-DE': 'Dies ist der Inhalt des Dialogtexts. Er kann beliebigen Text, Formulare oder andere Elemente enthalten.', 'fr-FR': 'Ceci est le contenu du corps de la boîte de dialogue. Il peut contenir du texte, des formulaires ou d\'autres éléments.', 'zh-CN': '这是对话框正文内容。它可以包含任何文本、表单或其他元素。' },
  'dialog.discardBody': { 'en-US': 'Your unsaved changes will be lost. This action cannot be undone.', 'ar-SA': 'ستفقد التغييرات غير المحفوظة. لا يمكن التراجع عن هذا الإجراء.', 'he-IL': 'השינויים שלא נשמרו יאבדו. לא ניתן לבטל פעולה זו.', 'ja-JP': '保存されていない変更は失われます。この操作は元に戻せません。', 'de-DE': 'Ihre nicht gespeicherten Änderungen gehen verloren. Diese Aktion kann nicht rückgängig gemacht werden.', 'fr-FR': 'Vos modifications non enregistrées seront perdues. Cette action est irréversible.', 'zh-CN': '未保存的更改将丢失。此操作无法撤消。' },
  'dialog.deleteFileBody': { 'en-US': 'This file will be permanently removed from your device. This action cannot be undone.', 'ar-SA': 'سيُزال هذا الملف نهائيًا من جهازك. لا يمكن التراجع عن هذا الإجراء.', 'he-IL': 'קובץ זה יוסר לצמיתות מהמכשיר שלך. לא ניתן לבטל פעולה זו.', 'ja-JP': 'このファイルはお使いのデバイスから完全に削除されます。この操作は元に戻せません。', 'de-DE': 'Diese Datei wird dauerhaft von Ihrem Gerät entfernt. Diese Aktion kann nicht rückgängig gemacht werden.', 'fr-FR': 'Ce fichier sera définitivement supprimé de votre appareil. Cette action est irréversible.', 'zh-CN': '此文件将从您的设备中永久删除。此操作无法撤消。' },
  'dialog.connectionLostBody': { 'en-US': 'Unable to reach the server. Please check your internet connection and try again.', 'ar-SA': 'تعذّر الوصول إلى الخادم. يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى.', 'he-IL': 'לא ניתן להגיע לשרת. אנא בדוק את חיבור האינטרנט שלך ונסה שוב.', 'ja-JP': 'サーバーに接続できません。インターネット接続を確認して、もう一度お試しください。', 'de-DE': 'Der Server ist nicht erreichbar. Bitte überprüfen Sie Ihre Internetverbindung und versuchen Sie es erneut.', 'fr-FR': 'Impossible de joindre le serveur. Veuillez vérifier votre connexion Internet et réessayer.', 'zh-CN': '无法连接到服务器。请检查您的网络连接后重试。' },
  'dialog.starBody': { 'en-US': 'This item will be added to your favorites.', 'ar-SA': 'ستتم إضافة هذا العنصر إلى المفضلة لديك.', 'he-IL': 'פריט זה יתווסף למועדפים שלך.', 'ja-JP': 'このアイテムはお気に入りに追加されます。', 'de-DE': 'Dieses Element wird zu Ihren Favoriten hinzugefügt.', 'fr-FR': 'Cet élément sera ajouté à vos favoris.', 'zh-CN': '该项目将被添加到您的收藏夹。' },
  'dialog.termsIntro': { 'en-US': 'By using this application, you agree to the following terms and conditions. Please read them carefully before proceeding.', 'ar-SA': 'باستخدامك هذا التطبيق، فإنك توافق على الشروط والأحكام التالية. يرجى قراءتها بعناية قبل المتابعة.', 'he-IL': 'השימוש באפליקציה זו מהווה הסכמה לתנאים ולהגבלות הבאים. אנא קרא אותם בעיון לפני שתמשיך.', 'ja-JP': 'このアプリケーションを使用することにより、以下の利用規約に同意したものとみなされます。続行する前に注意深くお読みください。', 'de-DE': 'Durch die Nutzung dieser Anwendung stimmen Sie den folgenden Geschäftsbedingungen zu. Bitte lesen Sie sie sorgfältig durch, bevor Sie fortfahren.', 'fr-FR': 'En utilisant cette application, vous acceptez les conditions générales suivantes. Veuillez les lire attentivement avant de continuer.', 'zh-CN': '使用本应用程序即表示您同意以下条款和条件。请在继续之前仔细阅读。' },
  'dialog.updateProfile': { 'en-US': 'Update your profile information below.', 'ar-SA': 'قم بتحديث معلومات ملفك الشخصي أدناه.', 'he-IL': 'עדכן את פרטי הפרופיל שלך למטה.', 'ja-JP': '以下でプロフィール情報を更新してください。', 'de-DE': 'Aktualisieren Sie unten Ihre Profilinformationen.', 'fr-FR': 'Mettez à jour vos informations de profil ci-dessous.', 'zh-CN': '在下方更新您的个人资料信息。' },
  'dialog.eventBody': { 'en-US': 'Click the buttons or press Escape to see events.', 'ar-SA': 'انقر على الأزرار أو اضغط على Escape لرؤية الأحداث.', 'he-IL': 'לחץ על הכפתורים או הקש Escape כדי לראות אירועים.', 'ja-JP': 'ボタンをクリックするか、Escape キーを押すとイベントが表示されます。', 'de-DE': 'Klicken Sie auf die Schaltflächen oder drücken Sie Escape, um Ereignisse anzuzeigen.', 'fr-FR': 'Cliquez sur les boutons ou appuyez sur Échap pour voir les événements.', 'zh-CN': '点击按钮或按 Escape 键即可查看事件。' },
  'dialog.eventLogEmpty': { 'en-US': 'Open, close, or escape the dialog to see events…', 'ar-SA': 'افتح مربع الحوار أو أغلقه أو اخرج منه لرؤية الأحداث…', 'he-IL': 'פתח, סגור או צא מהדו-שיח כדי לראות אירועים…', 'ja-JP': 'ダイアログを開く、閉じる、または Escape で閉じるとイベントが表示されます…', 'de-DE': 'Öffnen, schließen oder verlassen Sie den Dialog, um Ereignisse anzuzeigen…', 'fr-FR': 'Ouvrez, fermez ou quittez la boîte de dialogue pour voir les événements…', 'zh-CN': '打开、关闭或退出对话框即可查看事件…' },
  'dialog.controlledBody': { 'en-US': 'This dialog\'s state is controlled by external buttons. You can open and close it from outside.', 'ar-SA': 'تُتحكَّم حالة مربع الحوار هذا بواسطة أزرار خارجية. يمكنك فتحه وإغلاقه من الخارج.', 'he-IL': 'מצב הדו-שיח נשלט על ידי כפתורים חיצוניים. ניתן לפתוח ולסגור אותו מבחוץ.', 'ja-JP': 'このダイアログの状態は外部のボタンによって制御されます。外部から開閉できます。', 'de-DE': 'Der Zustand dieses Dialogs wird über externe Schaltflächen gesteuert. Sie können ihn von außen öffnen und schließen.', 'fr-FR': 'L\'état de cette boîte de dialogue est contrôlé par des boutons externes. Vous pouvez l\'ouvrir et la fermer de l\'extérieur.', 'zh-CN': '此对话框的状态由外部按钮控制。您可以从外部打开和关闭它。' },
  'dialog.nonDismissibleBody': { 'en-US': 'You must accept the terms before proceeding. Clicking the scrim will not close this dialog.', 'ar-SA': 'يجب عليك قبول الشروط قبل المتابعة. لن يؤدي النقر على الخلفية المعتمة إلى إغلاق مربع الحوار.', 'he-IL': 'עליך לקבל את התנאים לפני שתמשיך. לחיצה על הרקע המעומעם לא תסגור דו-שיח זה.', 'ja-JP': '続行する前に規約に同意する必要があります。スクリムをクリックしてもこのダイアログは閉じません。', 'de-DE': 'Sie müssen die Bedingungen akzeptieren, bevor Sie fortfahren. Ein Klick auf den Scrim schließt diesen Dialog nicht.', 'fr-FR': 'Vous devez accepter les conditions avant de continuer. Cliquer sur l\'arrière-plan ne fermera pas cette boîte de dialogue.', 'zh-CN': '您必须先接受条款才能继续。点击遮罩层不会关闭此对话框。' },
  'dialog.darkBody': { 'en-US': 'This dialog uses dark theme tokens for a dark appearance.', 'ar-SA': 'يستخدم مربع الحوار هذا رموز السمة الداكنة للحصول على مظهر داكن.', 'he-IL': 'דו-שיח זה משתמש באסימוני ערכת נושא כהה לקבלת מראה כהה.', 'ja-JP': 'このダイアログはダークテーマのトークンを使用して暗い外観にしています。', 'de-DE': 'Dieser Dialog verwendet Dark-Theme-Tokens für ein dunkles Erscheinungsbild.', 'fr-FR': 'Cette boîte de dialogue utilise des jetons de thème sombre pour un aspect sombre.', 'zh-CN': '此对话框使用深色主题令牌以呈现深色外观。' },
  'dialog.deleteProjectBody': { 'en-US': 'This will permanently delete the project "My App" and all associated data.', 'ar-SA': 'سيؤدي هذا إلى حذف المشروع "My App" وجميع البيانات المرتبطة به نهائيًا.', 'he-IL': 'פעולה זו תמחק לצמיתות את הפרויקט "My App" ואת כל הנתונים המשויכים אליו.', 'ja-JP': 'これにより、プロジェクト "My App" と関連するすべてのデータが完全に削除されます。', 'de-DE': 'Dadurch werden das Projekt "My App" und alle zugehörigen Daten dauerhaft gelöscht.', 'fr-FR': 'Cette action supprimera définitivement le projet "My App" et toutes les données associées.', 'zh-CN': '此操作将永久删除项目 "My App" 及所有相关数据。' },
  'dialog.dangerBody': { 'en-US': 'This action is destructive and cannot be reversed.', 'ar-SA': 'هذا الإجراء تدميري ولا يمكن التراجع عنه.', 'he-IL': 'פעולה זו הרסנית ולא ניתן לבטלה.', 'ja-JP': 'この操作は破壊的で、元に戻すことはできません。', 'de-DE': 'Diese Aktion ist destruktiv und kann nicht rückgängig gemacht werden.', 'fr-FR': 'Cette action est destructive et irréversible.', 'zh-CN': '此操作具有破坏性，无法撤消。' },
  'dialog.unsavedPreview': { 'en-US': 'Unsaved changes will be lost.', 'ar-SA': 'ستفقد التغييرات غير المحفوظة.', 'he-IL': 'השינויים שלא נשמרו יאבדו.', 'ja-JP': '保存されていない変更は失われます。', 'de-DE': 'Nicht gespeicherte Änderungen gehen verloren.', 'fr-FR': 'Les modifications non enregistrées seront perdues.', 'zh-CN': '未保存的更改将丢失。' },

  // ── Action buttons ───────────────────────────────────────────────
  'dialog.confirm': { 'en-US': 'Confirm', 'ar-SA': 'تأكيد', 'he-IL': 'אישור', 'ja-JP': '確認', 'de-DE': 'Bestätigen', 'fr-FR': 'Confirmer', 'zh-CN': '确认' },
  'dialog.discard': { 'en-US': 'Discard', 'ar-SA': 'تجاهل', 'he-IL': 'מחיקה', 'ja-JP': '破棄', 'de-DE': 'Verwerfen', 'fr-FR': 'Supprimer', 'zh-CN': '放弃' },
  'dialog.dismiss': { 'en-US': 'Dismiss', 'ar-SA': 'إغلاق', 'he-IL': 'סגירה', 'ja-JP': '閉じる', 'de-DE': 'Schließen', 'fr-FR': 'Ignorer', 'zh-CN': '忽略' },
  'dialog.retry': { 'en-US': 'Retry', 'ar-SA': 'إعادة المحاولة', 'he-IL': 'נסה שוב', 'ja-JP': '再試行', 'de-DE': 'Wiederholen', 'fr-FR': 'Réessayer', 'zh-CN': '重试' },
  'dialog.starAction': { 'en-US': 'Star', 'ar-SA': 'تمييز بنجمة', 'he-IL': 'סימון בכוכב', 'ja-JP': 'スターを付ける', 'de-DE': 'Mit Stern markieren', 'fr-FR': 'Marquer d\'une étoile', 'zh-CN': '加星标' },
  'dialog.decline': { 'en-US': 'Decline', 'ar-SA': 'رفض', 'he-IL': 'דחייה', 'ja-JP': '拒否', 'de-DE': 'Ablehnen', 'fr-FR': 'Refuser', 'zh-CN': '拒绝' },
  'dialog.accept': { 'en-US': 'Accept', 'ar-SA': 'قبول', 'he-IL': 'אישור', 'ja-JP': '同意する', 'de-DE': 'Akzeptieren', 'fr-FR': 'Accepter', 'zh-CN': '接受' },
  'dialog.close': { 'en-US': 'Close', 'ar-SA': 'إغلاق', 'he-IL': 'סגירה', 'ja-JP': '閉じる', 'de-DE': 'Schließen', 'fr-FR': 'Fermer', 'zh-CN': '关闭' },
  'dialog.iAccept': { 'en-US': 'I Accept', 'ar-SA': 'أوافق', 'he-IL': 'אני מסכים', 'ja-JP': '同意します', 'de-DE': 'Ich stimme zu', 'fr-FR': 'J\'accepte', 'zh-CN': '我接受' },
  'dialog.ok': { 'en-US': 'OK', 'ar-SA': 'موافق', 'he-IL': 'אישור', 'ja-JP': 'OK', 'de-DE': 'OK', 'fr-FR': 'OK', 'zh-CN': '确定' },

  // ── Form field labels ────────────────────────────────────────────
  'dialog.name': { 'en-US': 'Name', 'ar-SA': 'الاسم', 'he-IL': 'שם', 'ja-JP': '名前', 'de-DE': 'Name', 'fr-FR': 'Nom', 'zh-CN': '姓名' },
  'dialog.email': { 'en-US': 'Email', 'ar-SA': 'البريد الإلكتروني', 'he-IL': 'אימייל', 'ja-JP': 'メール', 'de-DE': 'E-Mail', 'fr-FR': 'E-mail', 'zh-CN': '电子邮件' },
  'dialog.bio': { 'en-US': 'Bio', 'ar-SA': 'نبذة', 'he-IL': 'אודות', 'ja-JP': '自己紹介', 'de-DE': 'Biografie', 'fr-FR': 'Bio', 'zh-CN': '简介' },
};
