import type { Entry } from '../index';

/** Per-component demo strings for the Side Sheet stories. Shared verbs
 *  (save, cancel, settings) live in `common.ts` and are reused via
 *  `t(locale, '<verb>')` — only side-sheet-specific copy is defined here.
 *  Documentation/CSS-showcase stories (Customization, CSSParts, WideSheet,
 *  Accessibility) and the static RTL / Localization demos are intentionally
 *  left untranslated, mirroring the Bottom Sheet catalog. */
export const messages: Record<string, Entry> = {
  // ── Trigger buttons ──────────────────────────────────────────────
  'sideSheet.openSideSheet': { 'en-US': 'Open Side Sheet', 'ar-SA': 'فتح الورقة الجانبية', 'he-IL': 'פתיחת גיליון צדי', 'ja-JP': 'サイドシートを開く', 'de-DE': 'Side Sheet öffnen', 'fr-FR': 'Ouvrir la feuille latérale', 'zh-CN': '打开侧边动作条' },
  'sideSheet.openModalSheet': { 'en-US': 'Open Modal Sheet', 'ar-SA': 'فتح الورقة الحوارية', 'he-IL': 'פתיחת גיליון מודאלי', 'ja-JP': 'モーダルシートを開く', 'de-DE': 'Modales Sheet öffnen', 'fr-FR': 'Ouvrir la feuille modale', 'zh-CN': '打开模态动作条' },
  'sideSheet.openWithBack': { 'en-US': 'Open with Back', 'ar-SA': 'فتح مع زر الرجوع', 'he-IL': 'פתיחה עם חזרה', 'ja-JP': '戻るボタン付きで開く', 'de-DE': 'Mit Zurück öffnen', 'fr-FR': 'Ouvrir avec retour', 'zh-CN': '打开（含返回）' },
  'sideSheet.openDetached': { 'en-US': 'Open Detached', 'ar-SA': 'فتح المنفصلة', 'he-IL': 'פתיחת מנותק', 'ja-JP': '分離を開く', 'de-DE': 'Losgelöst öffnen', 'fr-FR': 'Ouvrir détachée', 'zh-CN': '打开分离式' },
  'sideSheet.openStartSide': { 'en-US': 'Open Start Side', 'ar-SA': 'فتح جهة البداية', 'he-IL': 'פתיחה בצד ההתחלה', 'ja-JP': '開始側を開く', 'de-DE': 'Startkante öffnen', 'fr-FR': 'Ouvrir côté début', 'zh-CN': '从起始侧打开' },
  'sideSheet.openWithActions': { 'en-US': 'Open with Actions', 'ar-SA': 'فتح مع الإجراءات', 'he-IL': 'פתיחה עם פעולות', 'ja-JP': 'アクション付きで開く', 'de-DE': 'Mit Aktionen öffnen', 'fr-FR': 'Ouvrir avec actions', 'zh-CN': '打开（含操作）' },
  'sideSheet.openWithDividers': { 'en-US': 'Open with Dividers', 'ar-SA': 'فتح مع الفواصل', 'he-IL': 'פתיחה עם קווים מפרידים', 'ja-JP': '仕切り付きで開く', 'de-DE': 'Mit Trennlinien öffnen', 'fr-FR': 'Ouvrir avec séparateurs', 'zh-CN': '打开（含分隔线）' },
  'sideSheet.openInDarkTheme': { 'en-US': 'Open in Dark Theme', 'ar-SA': 'فتح في السمة الداكنة', 'he-IL': 'פתיחה בערכת נושא כהה', 'ja-JP': 'ダークテーマで開く', 'de-DE': 'Im dunklen Design öffnen', 'fr-FR': 'Ouvrir en thème sombre', 'zh-CN': '以深色主题打开' },
  'sideSheet.openScrollableSheet': { 'en-US': 'Open Scrollable Sheet', 'ar-SA': 'فتح الورقة القابلة للتمرير', 'he-IL': 'פתיחת גיליון הניתן לגלילה', 'ja-JP': 'スクロール可能なシートを開く', 'de-DE': 'Scrollbares Sheet öffnen', 'fr-FR': 'Ouvrir la feuille défilable', 'zh-CN': '打开可滚动动作条' },
  'sideSheet.openFilters': { 'en-US': 'Open Filters', 'ar-SA': 'فتح الفلاتر', 'he-IL': 'פתיחת מסננים', 'ja-JP': 'フィルターを開く', 'de-DE': 'Filter öffnen', 'fr-FR': 'Ouvrir les filtres', 'zh-CN': '打开筛选器' },
  'sideSheet.viewDetails': { 'en-US': 'View Details', 'ar-SA': 'عرض التفاصيل', 'he-IL': 'הצגת פרטים', 'ja-JP': '詳細を表示', 'de-DE': 'Details anzeigen', 'fr-FR': 'Voir les détails', 'zh-CN': '查看详情' },
  'sideSheet.startFlow': { 'en-US': 'Start Flow', 'ar-SA': 'بدء التدفق', 'he-IL': 'התחלת תהליך', 'ja-JP': 'フローを開始', 'de-DE': 'Ablauf starten', 'fr-FR': 'Démarrer le flux', 'zh-CN': '开始流程' },
  'sideSheet.openNonDismissible': { 'en-US': 'Open Non-Dismissible', 'ar-SA': 'فتح غير القابلة للإغلاق', 'he-IL': 'פתיחה ללא אפשרות סגירה', 'ja-JP': '閉じられないシートを開く', 'de-DE': 'Nicht schließbar öffnen', 'fr-FR': 'Ouvrir non fermable', 'zh-CN': '打开不可关闭' },
  'sideSheet.openNoCloseButton': { 'en-US': 'Open (No Close Button)', 'ar-SA': 'فتح (بدون زر إغلاق)', 'he-IL': 'פתיחה (ללא כפתור סגירה)', 'ja-JP': '開く（閉じるボタンなし）', 'de-DE': 'Öffnen (ohne Schließen-Schaltfläche)', 'fr-FR': 'Ouvrir (sans bouton de fermeture)', 'zh-CN': '打开（无关闭按钮）' },
  'sideSheet.openCustomHeadline': { 'en-US': 'Open Custom Headline', 'ar-SA': 'فتح بعنوان مخصص', 'he-IL': 'פתיחה עם כותרת מותאמת', 'ja-JP': 'カスタム見出しで開く', 'de-DE': 'Mit benutzerdefinierter Überschrift öffnen', 'fr-FR': 'Ouvrir avec titre personnalisé', 'zh-CN': '打开自定义标题' },
  'sideSheet.openDetachedWithActions': { 'en-US': 'Open Detached with Actions', 'ar-SA': 'فتح المنفصلة مع الإجراءات', 'he-IL': 'פתיחת מנותק עם פעולות', 'ja-JP': 'アクション付き分離シートを開く', 'de-DE': 'Losgelöst mit Aktionen öffnen', 'fr-FR': 'Ouvrir détachée avec actions', 'zh-CN': '打开分离式（含操作）' },

  // ── Sheet headlines ──────────────────────────────────────────────
  'sideSheet.filters': { 'en-US': 'Filters', 'ar-SA': 'عوامل التصفية', 'he-IL': 'מסננים', 'ja-JP': 'フィルター', 'de-DE': 'Filter', 'fr-FR': 'Filtres', 'zh-CN': '筛选器' },
  'sideSheet.details': { 'en-US': 'Details', 'ar-SA': 'التفاصيل', 'he-IL': 'פרטים', 'ja-JP': '詳細', 'de-DE': 'Details', 'fr-FR': 'Détails', 'zh-CN': '详情' },
  'sideSheet.subcategory': { 'en-US': 'Subcategory', 'ar-SA': 'فئة فرعية', 'he-IL': 'תת-קטגוריה', 'ja-JP': 'サブカテゴリー', 'de-DE': 'Unterkategorie', 'fr-FR': 'Sous-catégorie', 'zh-CN': '子类别' },
  'sideSheet.options': { 'en-US': 'Options', 'ar-SA': 'خيارات', 'he-IL': 'אפשרויות', 'ja-JP': 'オプション', 'de-DE': 'Optionen', 'fr-FR': 'Options', 'zh-CN': '选项' },
  'sideSheet.navigation': { 'en-US': 'Navigation', 'ar-SA': 'التنقل', 'he-IL': 'ניווט', 'ja-JP': 'ナビゲーション', 'de-DE': 'Navigation', 'fr-FR': 'Navigation', 'zh-CN': '导航' },
  'sideSheet.sidebar': { 'en-US': 'Sidebar', 'ar-SA': 'الشريط الجانبي', 'he-IL': 'סרגל צד', 'ja-JP': 'サイドバー', 'de-DE': 'Seitenleiste', 'fr-FR': 'Barre latérale', 'zh-CN': '侧边栏' },
  'sideSheet.darkSheet': { 'en-US': 'Dark Sheet', 'ar-SA': 'الورقة الداكنة', 'he-IL': 'גיליון כהה', 'ja-JP': 'ダークシート', 'de-DE': 'Dunkles Sheet', 'fr-FR': 'Feuille sombre', 'zh-CN': '深色动作条' },
  'sideSheet.longContent': { 'en-US': 'Long Content', 'ar-SA': 'محتوى طويل', 'he-IL': 'תוכן ארוך', 'ja-JP': '長いコンテンツ', 'de-DE': 'Langer Inhalt', 'fr-FR': 'Contenu long', 'zh-CN': '长内容' },
  'sideSheet.notifications': { 'en-US': 'Notifications', 'ar-SA': 'الإشعارات', 'he-IL': 'התראות', 'ja-JP': '通知', 'de-DE': 'Benachrichtigungen', 'fr-FR': 'Notifications', 'zh-CN': '通知' },
  'sideSheet.requiredAction': { 'en-US': 'Required Action', 'ar-SA': 'إجراء مطلوب', 'he-IL': 'פעולה נדרשת', 'ja-JP': '必須の操作', 'de-DE': 'Erforderliche Aktion', 'fr-FR': 'Action requise', 'zh-CN': '必需操作' },
  'sideSheet.themeEditor': { 'en-US': 'Theme Editor', 'ar-SA': 'محرر السمات', 'he-IL': 'עורך ערכות נושא', 'ja-JP': 'テーマエディター', 'de-DE': 'Design-Editor', 'fr-FR': 'Éditeur de thème', 'zh-CN': '主题编辑器' },
  'sideSheet.orderNumber': { 'en-US': 'Order #12345', 'ar-SA': 'الطلب #12345', 'he-IL': 'הזמנה #12345', 'ja-JP': '注文 #12345', 'de-DE': 'Bestellung #12345', 'fr-FR': 'Commande #12345', 'zh-CN': '订单 #12345' },
  'sideSheet.editProfile': { 'en-US': 'Edit Profile', 'ar-SA': 'تعديل الملف الشخصي', 'he-IL': 'עריכת פרופיל', 'ja-JP': 'プロフィールを編集', 'de-DE': 'Profil bearbeiten', 'fr-FR': 'Modifier le profil', 'zh-CN': '编辑个人资料' },

  // ── Body copy ────────────────────────────────────────────────────
  'sideSheet.playgroundBody': { 'en-US': 'This is secondary content inside the side sheet. It can contain form controls, filters, detail views, or any supplementary information.', 'ar-SA': 'هذا محتوى ثانوي داخل الورقة الجانبية. يمكن أن يحتوي على عناصر تحكم في النماذج أو فلاتر أو طرق عرض تفصيلية أو أي معلومات إضافية.', 'he-IL': 'זהו תוכן משני בתוך הגיליון הצדי. הוא יכול לכלול פקדי טפסים, מסננים, תצוגות פירוט או כל מידע משלים.', 'ja-JP': 'これはサイドシート内の補足コンテンツです。フォームコントロール、フィルター、詳細ビュー、その他の補足情報を含めることができます。', 'de-DE': 'Dies ist sekundärer Inhalt innerhalb des Side Sheets. Er kann Formularelemente, Filter, Detailansichten oder beliebige zusätzliche Informationen enthalten.', 'fr-FR': 'Ceci est un contenu secondaire à l\'intérieur de la feuille latérale. Il peut contenir des contrôles de formulaire, des filtres, des vues détaillées ou toute information complémentaire.', 'zh-CN': '这是侧边动作条内的辅助内容。它可以包含表单控件、筛选器、详情视图或任何补充信息。' },
  'sideSheet.scrollDown': { 'en-US': 'Scroll down for more content.', 'ar-SA': 'مرّر لأسفل لمزيد من المحتوى.', 'he-IL': 'גלול מטה לתוכן נוסף.', 'ja-JP': 'さらにコンテンツを表示するには下にスクロールしてください。', 'de-DE': 'Scrollen Sie nach unten für mehr Inhalt.', 'fr-FR': 'Faites défiler vers le bas pour plus de contenu.', 'zh-CN': '向下滚动以查看更多内容。' },
  'sideSheet.moreBelow': { 'en-US': 'More content below the fold.', 'ar-SA': 'المزيد من المحتوى أسفل الصفحة.', 'he-IL': 'תוכן נוסף מתחת לקו הקיפול.', 'ja-JP': '折り返し部分の下にさらにコンテンツがあります。', 'de-DE': 'Weiterer Inhalt unterhalb des sichtbaren Bereichs.', 'fr-FR': 'Plus de contenu sous la ligne de flottaison.', 'zh-CN': '更多内容在折叠区域下方。' },
  'sideSheet.mainContent': { 'en-US': 'Main Content', 'ar-SA': 'المحتوى الرئيسي', 'he-IL': 'תוכן ראשי', 'ja-JP': 'メインコンテンツ', 'de-DE': 'Hauptinhalt', 'fr-FR': 'Contenu principal', 'zh-CN': '主要内容' },
  'sideSheet.standardInline': { 'en-US': 'The standard side sheet coexists inline with the page content, separated by a vertical divider.', 'ar-SA': 'تتعايش الورقة الجانبية القياسية ضمن محتوى الصفحة، مفصولة بفاصل رأسي.', 'he-IL': 'הגיליון הצדי הרגיל מתקיים לצד תוכן העמוד, מופרד בקו מפריד אנכי.', 'ja-JP': '標準のサイドシートは、垂直の仕切りで区切られてページコンテンツとインラインで共存します。', 'de-DE': 'Das Standard-Side-Sheet steht inline neben dem Seiteninhalt, getrennt durch eine vertikale Trennlinie.', 'fr-FR': 'La feuille latérale standard coexiste en ligne avec le contenu de la page, séparée par un séparateur vertical.', 'zh-CN': '标准侧边动作条与页面内容并列显示，由垂直分隔线隔开。' },
  'sideSheet.filterByCategory': { 'en-US': 'Filter by category, date, status, and more.', 'ar-SA': 'التصفية حسب الفئة والتاريخ والحالة والمزيد.', 'he-IL': 'סינון לפי קטגוריה, תאריך, סטטוס ועוד.', 'ja-JP': 'カテゴリー、日付、ステータスなどで絞り込みます。', 'de-DE': 'Filtern Sie nach Kategorie, Datum, Status und mehr.', 'fr-FR': 'Filtrez par catégorie, date, statut, et plus encore.', 'zh-CN': '按类别、日期、状态等进行筛选。' },
  'sideSheet.modalBody': { 'en-US': 'Modal side sheets overlay the page with a scrim. They trap focus and lock body scroll.', 'ar-SA': 'تُغطّي الأوراق الجانبية الحوارية الصفحة بحاجب. وتحصر التركيز وتُقفل تمرير الصفحة.', 'he-IL': 'גיליונות צד מודאליים מכסים את העמוד ברקע מוצל. הם לוכדים את הפוקוס ונועלים את גלילת העמוד.', 'ja-JP': 'モーダルサイドシートはスクリムでページを覆います。フォーカスをトラップし、本文のスクロールをロックします。', 'de-DE': 'Modale Side Sheets überlagern die Seite mit einem Schleier. Sie fangen den Fokus ein und sperren das Scrollen der Seite.', 'fr-FR': 'Les feuilles latérales modales recouvrent la page d\'un voile. Elles capturent le focus et verrouillent le défilement de la page.', 'zh-CN': '模态侧边动作条使用遮罩覆盖页面。它们会捕获焦点并锁定页面滚动。' },
  'sideSheet.scrimOrEscape': { 'en-US': 'Click the scrim or press Escape to dismiss.', 'ar-SA': 'انقر على الحاجب أو اضغط Escape للإغلاق.', 'he-IL': 'לחץ על הרקע המוצל או הקש Escape כדי לסגור.', 'ja-JP': 'スクリムをクリックするか、Escape キーを押して閉じます。', 'de-DE': 'Klicken Sie auf den Schleier oder drücken Sie Escape zum Schließen.', 'fr-FR': 'Cliquez sur le voile ou appuyez sur Échap pour fermer.', 'zh-CN': '点击遮罩或按 Escape 键关闭。' },
  'sideSheet.backNavBody': { 'en-US': 'This modal sheet has a back button for in-sheet navigation.', 'ar-SA': 'تحتوي هذه الورقة الحوارية على زر رجوع للتنقل داخل الورقة.', 'he-IL': 'לגיליון מודאלי זה יש כפתור חזרה לניווט בתוך הגיליון.', 'ja-JP': 'このモーダルシートには、シート内ナビゲーション用の戻るボタンがあります。', 'de-DE': 'Dieses modale Sheet hat eine Zurück-Schaltfläche für die Navigation innerhalb des Sheets.', 'fr-FR': 'Cette feuille modale dispose d\'un bouton de retour pour la navigation au sein de la feuille.', 'zh-CN': '此模态动作条带有用于表内导航的返回按钮。' },
  'sideSheet.detachedBody': { 'en-US': 'Detached sheets have rounded corners and a 16px margin from the viewport edge.', 'ar-SA': 'تتميز الأوراق المنفصلة بزوايا مستديرة وهامش 16px من حافة إطار العرض.', 'he-IL': 'לגיליונות מנותקים יש פינות מעוגלות ושוליים של 16px מקצה אזור התצוגה.', 'ja-JP': '分離シートには角丸があり、ビューポートの端から 16px の余白があります。', 'de-DE': 'Losgelöste Sheets haben abgerundete Ecken und einen Abstand von 16px zum Rand des Ansichtsfensters.', 'fr-FR': 'Les feuilles détachées ont des coins arrondis et une marge de 16px par rapport au bord de la fenêtre.', 'zh-CN': '分离式动作条具有圆角，并与视口边缘保持 16px 的间距。' },
  'sideSheet.startSideBody': { 'en-US': 'This sheet slides in from the inline-start edge (left in LTR, right in RTL).', 'ar-SA': 'تنزلق هذه الورقة من حافة البداية المنطقية (يسارًا في LTR، يمينًا في RTL).', 'he-IL': 'גיליון זה נכנס מקצה ההתחלה הלוגי (שמאל ב-LTR, ימין ב-RTL).', 'ja-JP': 'このシートは論理的な開始端からスライドインします（LTR では左、RTL では右）。', 'de-DE': 'Dieses Sheet gleitet von der logischen Startkante herein (links bei LTR, rechts bei RTL).', 'fr-FR': 'Cette feuille glisse depuis le bord de début logique (gauche en LTR, droite en RTL).', 'zh-CN': '此动作条从行内起始边缘滑入（LTR 时在左侧，RTL 时在右侧）。' },
  'sideSheet.selectFilters': { 'en-US': 'Select the filters you want to apply.', 'ar-SA': 'حدد الفلاتر التي تريد تطبيقها.', 'he-IL': 'בחר את המסננים שברצונך להחיל.', 'ja-JP': '適用するフィルターを選択してください。', 'de-DE': 'Wählen Sie die Filter aus, die Sie anwenden möchten.', 'fr-FR': 'Sélectionnez les filtres que vous souhaitez appliquer.', 'zh-CN': '选择您想要应用的筛选器。' },
  'sideSheet.bothDividers': { 'en-US': 'Both top and bottom dividers are visible.', 'ar-SA': 'الفاصلان العلوي والسفلي كلاهما مرئي.', 'he-IL': 'הקווים המפרידים העליון והתחתון גלויים שניהם.', 'ja-JP': '上部と下部の両方の仕切りが表示されています。', 'de-DE': 'Sowohl die obere als auch die untere Trennlinie sind sichtbar.', 'fr-FR': 'Les séparateurs supérieur et inférieur sont tous deux visibles.', 'zh-CN': '顶部和底部分隔线均可见。' },
  'sideSheet.startSideStandard': { 'en-US': 'Start-side standard sheet.', 'ar-SA': 'ورقة قياسية على جهة البداية.', 'he-IL': 'גיליון רגיל בצד ההתחלה.', 'ja-JP': '開始側の標準シート。', 'de-DE': 'Standard-Sheet an der Startkante.', 'fr-FR': 'Feuille standard côté début.', 'zh-CN': '起始侧标准动作条。' },
  'sideSheet.standardSitsStart': { 'en-US': 'The standard sheet sits on the start side.', 'ar-SA': 'توجد الورقة القياسية على جهة البداية.', 'he-IL': 'הגיליון הרגיל ממוקם בצד ההתחלה.', 'ja-JP': '標準シートは開始側に配置されます。', 'de-DE': 'Das Standard-Sheet befindet sich an der Startkante.', 'fr-FR': 'La feuille standard se trouve du côté du début.', 'zh-CN': '标准动作条位于起始侧。' },
  'sideSheet.darkThemeBody': { 'en-US': 'Side sheet in dark theme.', 'ar-SA': 'ورقة جانبية في السمة الداكنة.', 'he-IL': 'גיליון צדי בערכת נושא כהה.', 'ja-JP': 'ダークテーマのサイドシート。', 'de-DE': 'Side Sheet im dunklen Design.', 'fr-FR': 'Feuille latérale en thème sombre.', 'zh-CN': '深色主题下的侧边动作条。' },
  'sideSheet.nonDismissibleBody': { 'en-US': 'This sheet cannot be dismissed by clicking the scrim or pressing Escape. The user must complete the action.', 'ar-SA': 'لا يمكن إغلاق هذه الورقة بالنقر على الحاجب أو الضغط على Escape. يجب على المستخدم إكمال الإجراء.', 'he-IL': 'לא ניתן לסגור גיליון זה בלחיצה על הרקע או בהקשה על Escape. המשתמש חייב להשלים את הפעולה.', 'ja-JP': 'このシートはスクリムをクリックしたり Escape キーを押したりしても閉じられません。ユーザーは操作を完了する必要があります。', 'de-DE': 'Dieses Sheet kann nicht durch Klicken auf den Schleier oder Drücken von Escape geschlossen werden. Der Benutzer muss die Aktion abschließen.', 'fr-FR': 'Cette feuille ne peut pas être fermée en cliquant sur le voile ou en appuyant sur Échap. L\'utilisateur doit terminer l\'action.', 'zh-CN': '无法通过点击遮罩或按 Escape 键关闭此动作条。用户必须完成操作。' },
  'sideSheet.onlyActionCloses': { 'en-US': 'Only the explicit action button will close it.', 'ar-SA': 'زر الإجراء الصريح وحده هو الذي سيغلقها.', 'he-IL': 'רק כפתור הפעולה המפורש יסגור אותו.', 'ja-JP': '明示的なアクションボタンのみがこれを閉じます。', 'de-DE': 'Nur die explizite Aktionsschaltfläche schließt es.', 'fr-FR': 'Seul le bouton d\'action explicite la fermera.', 'zh-CN': '只有明确的操作按钮才能将其关闭。' },
  'sideSheet.noCloseBody': { 'en-US': 'This sheet has no close icon button. It can still be dismissed by clicking the scrim or pressing Escape.', 'ar-SA': 'لا تحتوي هذه الورقة على زر أيقونة إغلاق. لا يزال بإمكانك إغلاقها بالنقر على الحاجب أو الضغط على Escape.', 'he-IL': 'לגיליון זה אין כפתור סגירה. עדיין ניתן לסגור אותו בלחיצה על הרקע או בהקשה על Escape.', 'ja-JP': 'このシートには閉じるアイコンボタンがありません。スクリムをクリックするか Escape キーを押して閉じることができます。', 'de-DE': 'Dieses Sheet hat keine Schließen-Symbolschaltfläche. Es kann dennoch durch Klicken auf den Schleier oder Drücken von Escape geschlossen werden.', 'fr-FR': 'Cette feuille n\'a pas de bouton de fermeture. Elle peut néanmoins être fermée en cliquant sur le voile ou en appuyant sur Échap.', 'zh-CN': '此动作条没有关闭图标按钮。仍可通过点击遮罩或按 Escape 键将其关闭。' },

  // ── Action buttons ───────────────────────────────────────────────
  'sideSheet.apply': { 'en-US': 'Apply', 'ar-SA': 'تطبيق', 'he-IL': 'החלה', 'ja-JP': '適用', 'de-DE': 'Übernehmen', 'fr-FR': 'Appliquer', 'zh-CN': '应用' },
  'sideSheet.reset': { 'en-US': 'Reset', 'ar-SA': 'إعادة تعيين', 'he-IL': 'איפוס', 'ja-JP': 'リセット', 'de-DE': 'Zurücksetzen', 'fr-FR': 'Réinitialiser', 'zh-CN': '重置' },
  'sideSheet.applyFilters': { 'en-US': 'Apply Filters', 'ar-SA': 'تطبيق الفلاتر', 'he-IL': 'החלת מסננים', 'ja-JP': 'フィルターを適用', 'de-DE': 'Filter anwenden', 'fr-FR': 'Appliquer les filtres', 'zh-CN': '应用筛选器' },
  'sideSheet.clearAll': { 'en-US': 'Clear All', 'ar-SA': 'مسح الكل', 'he-IL': 'ניקוי הכול', 'ja-JP': 'すべてクリア', 'de-DE': 'Alle löschen', 'fr-FR': 'Tout effacer', 'zh-CN': '全部清除' },
  'sideSheet.iUnderstand': { 'en-US': 'I Understand', 'ar-SA': 'أفهم ذلك', 'he-IL': 'הבנתי', 'ja-JP': '理解しました', 'de-DE': 'Ich verstehe', 'fr-FR': 'J\'ai compris', 'zh-CN': '我知道了' },
  'sideSheet.applyTheme': { 'en-US': 'Apply Theme', 'ar-SA': 'تطبيق السمة', 'he-IL': 'החלת ערכת נושא', 'ja-JP': 'テーマを適用', 'de-DE': 'Design anwenden', 'fr-FR': 'Appliquer le thème', 'zh-CN': '应用主题' },
  'sideSheet.confirmOrder': { 'en-US': 'Confirm order', 'ar-SA': 'تأكيد الطلب', 'he-IL': 'אישור הזמנה', 'ja-JP': '注文を確定', 'de-DE': 'Bestellung bestätigen', 'fr-FR': 'Confirmer la commande', 'zh-CN': '确认订单' },

  // ── Filter panel ─────────────────────────────────────────────────
  'sideSheet.category': { 'en-US': 'Category', 'ar-SA': 'الفئة', 'he-IL': 'קטגוריה', 'ja-JP': 'カテゴリー', 'de-DE': 'Kategorie', 'fr-FR': 'Catégorie', 'zh-CN': '类别' },
  'sideSheet.electronics': { 'en-US': 'Electronics', 'ar-SA': 'إلكترونيات', 'he-IL': 'אלקטרוניקה', 'ja-JP': '電子機器', 'de-DE': 'Elektronik', 'fr-FR': 'Électronique', 'zh-CN': '电子产品' },
  'sideSheet.clothing': { 'en-US': 'Clothing', 'ar-SA': 'ملابس', 'he-IL': 'ביגוד', 'ja-JP': '衣類', 'de-DE': 'Kleidung', 'fr-FR': 'Vêtements', 'zh-CN': '服装' },
  'sideSheet.books': { 'en-US': 'Books', 'ar-SA': 'كتب', 'he-IL': 'ספרים', 'ja-JP': '書籍', 'de-DE': 'Bücher', 'fr-FR': 'Livres', 'zh-CN': '图书' },
  'sideSheet.priceRange': { 'en-US': 'Price Range', 'ar-SA': 'نطاق السعر', 'he-IL': 'טווח מחירים', 'ja-JP': '価格帯', 'de-DE': 'Preisspanne', 'fr-FR': 'Gamme de prix', 'zh-CN': '价格范围' },
  'sideSheet.availability': { 'en-US': 'Availability', 'ar-SA': 'التوفر', 'he-IL': 'זמינות', 'ja-JP': '在庫状況', 'de-DE': 'Verfügbarkeit', 'fr-FR': 'Disponibilité', 'zh-CN': '库存情况' },
  'sideSheet.inStock': { 'en-US': 'In stock', 'ar-SA': 'متوفر', 'he-IL': 'במלאי', 'ja-JP': '在庫あり', 'de-DE': 'Auf Lager', 'fr-FR': 'En stock', 'zh-CN': '有货' },
  'sideSheet.preOrder': { 'en-US': 'Pre-order', 'ar-SA': 'طلب مسبق', 'he-IL': 'הזמנה מוקדמת', 'ja-JP': '予約注文', 'de-DE': 'Vorbestellung', 'fr-FR': 'Précommande', 'zh-CN': '预订' },
  'sideSheet.outOfStock': { 'en-US': 'Out of stock', 'ar-SA': 'نفد المخزون', 'he-IL': 'אזל מהמלאי', 'ja-JP': '在庫切れ', 'de-DE': 'Nicht auf Lager', 'fr-FR': 'En rupture de stock', 'zh-CN': '缺货' },

  // ── Detail view ──────────────────────────────────────────────────
  'sideSheet.status': { 'en-US': 'Status', 'ar-SA': 'الحالة', 'he-IL': 'סטטוס', 'ja-JP': 'ステータス', 'de-DE': 'Status', 'fr-FR': 'Statut', 'zh-CN': '状态' },
  'sideSheet.shipped': { 'en-US': 'Shipped', 'ar-SA': 'تم الشحن', 'he-IL': 'נשלח', 'ja-JP': '発送済み', 'de-DE': 'Versandt', 'fr-FR': 'Expédié', 'zh-CN': '已发货' },
  'sideSheet.trackingNumber': { 'en-US': 'Tracking Number', 'ar-SA': 'رقم التتبع', 'he-IL': 'מספר מעקב', 'ja-JP': '追跡番号', 'de-DE': 'Sendungsnummer', 'fr-FR': 'Numéro de suivi', 'zh-CN': '追踪单号' },
  'sideSheet.items': { 'en-US': 'Items', 'ar-SA': 'العناصر', 'he-IL': 'פריטים', 'ja-JP': '商品', 'de-DE': 'Artikel', 'fr-FR': 'Articles', 'zh-CN': '商品' },
  'sideSheet.total': { 'en-US': 'Total', 'ar-SA': 'الإجمالي', 'he-IL': 'סה״כ', 'ja-JP': '合計', 'de-DE': 'Gesamt', 'fr-FR': 'Total', 'zh-CN': '总计' },

  // ── Settings panel ───────────────────────────────────────────────
  'sideSheet.application': { 'en-US': 'Application', 'ar-SA': 'التطبيق', 'he-IL': 'אפליקציה', 'ja-JP': 'アプリケーション', 'de-DE': 'Anwendung', 'fr-FR': 'Application', 'zh-CN': '应用程序' },
  'sideSheet.settingsInline': { 'en-US': 'The settings side sheet stays open alongside the main content.', 'ar-SA': 'تبقى ورقة الإعدادات الجانبية مفتوحة بجانب المحتوى الرئيسي.', 'he-IL': 'גיליון ההגדרות הצדי נשאר פתוח לצד התוכן הראשי.', 'ja-JP': '設定サイドシートはメインコンテンツと並んで開いたままになります。', 'de-DE': 'Das Einstellungen-Side-Sheet bleibt neben dem Hauptinhalt geöffnet.', 'fr-FR': 'La feuille latérale des paramètres reste ouverte à côté du contenu principal.', 'zh-CN': '设置侧边动作条与主要内容并排保持打开状态。' },
  'sideSheet.standardVariantNote': { 'en-US': 'It uses the standard variant — no scrim, no overlay.', 'ar-SA': 'تستخدم النمط القياسي — بدون حاجب، وبدون تراكب.', 'he-IL': 'הוא משתמש בגרסה הרגילה — ללא רקע מוצל, ללא שכבת-על.', 'ja-JP': '標準バリアントを使用します — スクリムなし、オーバーレイなし。', 'de-DE': 'Es verwendet die Standardvariante – kein Schleier, kein Overlay.', 'fr-FR': 'Elle utilise la variante standard — sans voile, sans superposition.', 'zh-CN': '它使用标准变体——无遮罩，无叠加层。' },
  'sideSheet.darkMode': { 'en-US': 'Dark mode', 'ar-SA': 'الوضع الداكن', 'he-IL': 'מצב כהה', 'ja-JP': 'ダークモード', 'de-DE': 'Dunkler Modus', 'fr-FR': 'Mode sombre', 'zh-CN': '深色模式' },
  'sideSheet.compactView': { 'en-US': 'Compact view', 'ar-SA': 'عرض مضغوط', 'he-IL': 'תצוגה קומפקטית', 'ja-JP': 'コンパクト表示', 'de-DE': 'Kompakte Ansicht', 'fr-FR': 'Vue compacte', 'zh-CN': '紧凑视图' },
  'sideSheet.language': { 'en-US': 'Language', 'ar-SA': 'اللغة', 'he-IL': 'שפה', 'ja-JP': '言語', 'de-DE': 'Sprache', 'fr-FR': 'Langue', 'zh-CN': '语言' },

  // ── Edit profile form ────────────────────────────────────────────
  'sideSheet.displayName': { 'en-US': 'Display name', 'ar-SA': 'الاسم المعروض', 'he-IL': 'שם תצוגה', 'ja-JP': '表示名', 'de-DE': 'Anzeigename', 'fr-FR': 'Nom d\'affichage', 'zh-CN': '显示名称' },
  'sideSheet.email': { 'en-US': 'Email', 'ar-SA': 'البريد الإلكتروني', 'he-IL': 'דוא״ל', 'ja-JP': 'メール', 'de-DE': 'E-Mail', 'fr-FR': 'E-mail', 'zh-CN': '电子邮件' },
  'sideSheet.bio': { 'en-US': 'Bio', 'ar-SA': 'نبذة', 'he-IL': 'אודות', 'ja-JP': '自己紹介', 'de-DE': 'Bio', 'fr-FR': 'Bio', 'zh-CN': '简介' },

  // ── Multi-step navigation ────────────────────────────────────────
  'sideSheet.selectCategory': { 'en-US': 'Select Category', 'ar-SA': 'اختر الفئة', 'he-IL': 'בחירת קטגוריה', 'ja-JP': 'カテゴリーを選択', 'de-DE': 'Kategorie auswählen', 'fr-FR': 'Sélectionner une catégorie', 'zh-CN': '选择类别' },
  'sideSheet.chooseItem': { 'en-US': 'Choose Item', 'ar-SA': 'اختر العنصر', 'he-IL': 'בחירת פריט', 'ja-JP': '商品を選択', 'de-DE': 'Artikel auswählen', 'fr-FR': 'Choisir un article', 'zh-CN': '选择商品' },
  'sideSheet.homeGarden': { 'en-US': 'Home & Garden', 'ar-SA': 'المنزل والحديقة', 'he-IL': 'בית וגינה', 'ja-JP': 'ホーム＆ガーデン', 'de-DE': 'Haus & Garten', 'fr-FR': 'Maison et jardin', 'zh-CN': '家居与园艺' },
  'sideSheet.sportsOutdoors': { 'en-US': 'Sports & Outdoors', 'ar-SA': 'الرياضة والأنشطة الخارجية', 'he-IL': 'ספורט וטבע', 'ja-JP': 'スポーツ＆アウトドア', 'de-DE': 'Sport & Outdoor', 'fr-FR': 'Sports et plein air', 'zh-CN': '运动与户外' },
  'sideSheet.electronicsDesc': { 'en-US': 'Phones, laptops, accessories', 'ar-SA': 'هواتف، حواسيب محمولة، ملحقات', 'he-IL': 'טלפונים, מחשבים ניידים, אביזרים', 'ja-JP': 'スマートフォン、ノートパソコン、アクセサリー', 'de-DE': 'Telefone, Laptops, Zubehör', 'fr-FR': 'Téléphones, ordinateurs portables, accessoires', 'zh-CN': '手机、笔记本电脑、配件' },
  'sideSheet.homeGardenDesc': { 'en-US': 'Furniture, decor, tools', 'ar-SA': 'أثاث، ديكور، أدوات', 'he-IL': 'רהיטים, עיצוב, כלים', 'ja-JP': '家具、装飾、工具', 'de-DE': 'Möbel, Dekoration, Werkzeuge', 'fr-FR': 'Meubles, décoration, outils', 'zh-CN': '家具、装饰、工具' },
  'sideSheet.sportsDesc': { 'en-US': 'Gear, apparel, equipment', 'ar-SA': 'معدات، ملابس، تجهيزات', 'he-IL': 'ציוד, ביגוד, אבזור', 'ja-JP': 'ギア、アパレル、用具', 'de-DE': 'Ausrüstung, Bekleidung, Zubehör', 'fr-FR': 'Matériel, vêtements, équipement', 'zh-CN': '装备、服饰、器材' },
  'sideSheet.headphonesDesc': { 'en-US': 'Noise-cancelling, 30 h battery', 'ar-SA': 'إلغاء الضوضاء، بطارية 30 ساعة', 'he-IL': 'ביטול רעשים, סוללה ל-30 שעות', 'ja-JP': 'ノイズキャンセリング、30時間バッテリー', 'de-DE': 'Geräuschunterdrückung, 30 Std. Akku', 'fr-FR': 'Réduction de bruit, batterie 30 h', 'zh-CN': '降噪，30 小时续航' },
  'sideSheet.watchDesc': { 'en-US': 'Health tracking, GPS', 'ar-SA': 'تتبع الصحة، GPS', 'he-IL': 'מעקב בריאותי, GPS', 'ja-JP': '健康トラッキング、GPS', 'de-DE': 'Gesundheitstracking, GPS', 'fr-FR': 'Suivi de santé, GPS', 'zh-CN': '健康追踪，GPS' },
  'sideSheet.speakerDesc': { 'en-US': '360° sound, waterproof', 'ar-SA': 'صوت 360°، مقاوم للماء', 'he-IL': 'צליל 360°, עמיד למים', 'ja-JP': '360°サウンド、防水', 'de-DE': '360°-Klang, wasserdicht', 'fr-FR': 'Son à 360°, étanche', 'zh-CN': '360° 环绕音效，防水' },
  'sideSheet.item': { 'en-US': 'Item', 'ar-SA': 'العنصر', 'he-IL': 'פריט', 'ja-JP': '商品', 'de-DE': 'Artikel', 'fr-FR': 'Article', 'zh-CN': '商品' },
  'sideSheet.price': { 'en-US': 'Price', 'ar-SA': 'السعر', 'he-IL': 'מחיר', 'ja-JP': '価格', 'de-DE': 'Preis', 'fr-FR': 'Prix', 'zh-CN': '价格' },

  // ── Notification list items ──────────────────────────────────────
  'sideSheet.newMessageAlex': { 'en-US': 'New message from Alex', 'ar-SA': 'رسالة جديدة من Alex', 'he-IL': 'הודעה חדשה מ-Alex', 'ja-JP': 'Alex からの新しいメッセージ', 'de-DE': 'Neue Nachricht von Alex', 'fr-FR': 'Nouveau message d\'Alex', 'zh-CN': '来自 Alex 的新消息' },
  'sideSheet.orderShipped': { 'en-US': 'Your order has shipped', 'ar-SA': 'تم شحن طلبك', 'he-IL': 'ההזמנה שלך נשלחה', 'ja-JP': 'ご注文が発送されました', 'de-DE': 'Ihre Bestellung wurde versandt', 'fr-FR': 'Votre commande a été expédiée', 'zh-CN': '您的订单已发货' },
  'sideSheet.weeklyReport': { 'en-US': 'Weekly report is ready', 'ar-SA': 'التقرير الأسبوعي جاهز', 'he-IL': 'הדוח השבועי מוכן', 'ja-JP': '週次レポートの準備ができました', 'de-DE': 'Der Wochenbericht ist fertig', 'fr-FR': 'Le rapport hebdomadaire est prêt', 'zh-CN': '周报已就绪' },

  // ── Custom headline slot ─────────────────────────────────────────
  'sideSheet.primaryColor': { 'en-US': 'Primary Color', 'ar-SA': 'اللون الأساسي', 'he-IL': 'צבע ראשי', 'ja-JP': 'プライマリカラー', 'de-DE': 'Primärfarbe', 'fr-FR': 'Couleur principale', 'zh-CN': '主色' },
  'sideSheet.borderRadius': { 'en-US': 'Border Radius', 'ar-SA': 'نصف قطر الحدود', 'he-IL': 'רדיוס פינה', 'ja-JP': '角の丸み', 'de-DE': 'Eckenradius', 'fr-FR': 'Rayon des bords', 'zh-CN': '边框圆角' },
};
