import type { Entry } from '../index';

/** Demo strings for the Stepper stories. Only genuine user-facing content is
 *  localized: step labels + descriptions, error/helper text, the explicit
 *  Back / Continue / Reset buttons of the "own your navigation" demo, the
 *  status / completion messages, the validation field labels + placeholder,
 *  and the swap-in content panels (titles + body copy) of the mock checkout /
 *  onboarding / deploy / survey flows. The `Back` verb reuses `common.ts`.
 *
 *  Left byte-for-byte (not routed through this catalog): the `labelStyle`
 *  section captions and other prose that explains the component / events /
 *  CSS variables; the built-in nav labels (owned by the component, English
 *  defaults); API identifiers embedded in copy (mdComplete, next(), pnpm,
 *  dist/); proper-noun sample data (AWC, Visa, GitHub, ionut@example.com,
 *  Str. Exemplu 12 / București, card numbers, prices, dates); the intentional
 *  static German + Arabic RTL `Localization` story; and the theming-docs
 *  `CustomCSS` and DOM-mechanism `LazyContent` stories. */
export const messages: Record<string, Entry> = {
  // ── Step labels ──────────────────────────────────────────────────
  'stepper.cart': { 'en-US': 'Cart', 'ar-SA': 'سلة التسوق', 'he-IL': 'עגלה', 'ja-JP': 'カート', 'de-DE': 'Warenkorb', 'fr-FR': 'Panier', 'zh-CN': '购物车' },
  'stepper.shipping': { 'en-US': 'Shipping', 'ar-SA': 'الشحن', 'he-IL': 'משלוח', 'ja-JP': '配送', 'de-DE': 'Versand', 'fr-FR': 'Livraison', 'zh-CN': '配送' },
  'stepper.payment': { 'en-US': 'Payment', 'ar-SA': 'الدفع', 'he-IL': 'תשלום', 'ja-JP': '支払い', 'de-DE': 'Zahlung', 'fr-FR': 'Paiement', 'zh-CN': '付款' },
  'stepper.review': { 'en-US': 'Review', 'ar-SA': 'المراجعة', 'he-IL': 'סקירה', 'ja-JP': '確認', 'de-DE': 'Überprüfung', 'fr-FR': 'Vérification', 'zh-CN': '确认' },
  'stepper.welcome': { 'en-US': 'Welcome', 'ar-SA': 'مرحبًا', 'he-IL': 'ברוך הבא', 'ja-JP': 'ようこそ', 'de-DE': 'Willkommen', 'fr-FR': 'Bienvenue', 'zh-CN': '欢迎' },
  'stepper.profile': { 'en-US': 'Profile', 'ar-SA': 'الملف الشخصي', 'he-IL': 'פרופיל', 'ja-JP': 'プロフィール', 'de-DE': 'Profil', 'fr-FR': 'Profil', 'zh-CN': '个人资料' },
  'stepper.preferences': { 'en-US': 'Preferences', 'ar-SA': 'التفضيلات', 'he-IL': 'העדפות', 'ja-JP': '設定', 'de-DE': 'Einstellungen', 'fr-FR': 'Préférences', 'zh-CN': '偏好设置' },
  'stepper.done': { 'en-US': 'Done', 'ar-SA': 'تم', 'he-IL': 'סיום', 'ja-JP': '完了', 'de-DE': 'Fertig', 'fr-FR': 'Terminé', 'zh-CN': '完成' },
  'stepper.connect': { 'en-US': 'Connect', 'ar-SA': 'الاتصال', 'he-IL': 'התחברות', 'ja-JP': '接続', 'de-DE': 'Verbinden', 'fr-FR': 'Connexion', 'zh-CN': '连接' },
  'stepper.configure': { 'en-US': 'Configure', 'ar-SA': 'التهيئة', 'he-IL': 'הגדרה', 'ja-JP': '構成', 'de-DE': 'Konfigurieren', 'fr-FR': 'Configurer', 'zh-CN': '配置' },
  'stepper.deploy': { 'en-US': 'Deploy', 'ar-SA': 'النشر', 'he-IL': 'פריסה', 'ja-JP': 'デプロイ', 'de-DE': 'Bereitstellen', 'fr-FR': 'Déployer', 'zh-CN': '部署' },
  'stepper.account': { 'en-US': 'Account', 'ar-SA': 'الحساب', 'he-IL': 'חשבון', 'ja-JP': 'アカウント', 'de-DE': 'Konto', 'fr-FR': 'Compte', 'zh-CN': '账户' },
  'stepper.addons': { 'en-US': 'Add-ons', 'ar-SA': 'الإضافات', 'he-IL': 'תוספות', 'ja-JP': 'アドオン', 'de-DE': 'Add-ons', 'fr-FR': 'Extras', 'zh-CN': '附加项' },
  'stepper.personal': { 'en-US': 'Personal', 'ar-SA': 'شخصي', 'he-IL': 'אישי', 'ja-JP': '個人情報', 'de-DE': 'Persönlich', 'fr-FR': 'Personnel', 'zh-CN': '个人信息' },
  'stepper.address': { 'en-US': 'Address', 'ar-SA': 'العنوان', 'he-IL': 'כתובת', 'ja-JP': '住所', 'de-DE': 'Adresse', 'fr-FR': 'Adresse', 'zh-CN': '地址' },
  'stepper.pay': { 'en-US': 'Pay', 'ar-SA': 'الدفع', 'he-IL': 'תשלום', 'ja-JP': '支払う', 'de-DE': 'Bezahlen', 'fr-FR': 'Payer', 'zh-CN': '支付' },
  'stepper.email': { 'en-US': 'Email', 'ar-SA': 'البريد الإلكتروني', 'he-IL': 'אימייל', 'ja-JP': 'メール', 'de-DE': 'E-Mail', 'fr-FR': 'E-mail', 'zh-CN': '电子邮件' },
  'stepper.accountDetails': { 'en-US': 'Account details', 'ar-SA': 'تفاصيل الحساب', 'he-IL': 'פרטי חשבון', 'ja-JP': 'アカウント詳細', 'de-DE': 'Kontodetails', 'fr-FR': 'Détails du compte', 'zh-CN': '账户详情' },
  'stepper.shippingAddress': { 'en-US': 'Shipping address', 'ar-SA': 'عنوان الشحن', 'he-IL': 'כתובת למשלוח', 'ja-JP': '配送先住所', 'de-DE': 'Lieferadresse', 'fr-FR': 'Adresse de livraison', 'zh-CN': '配送地址' },
  'stepper.paymentMethod': { 'en-US': 'Payment method', 'ar-SA': 'طريقة الدفع', 'he-IL': 'אמצעי תשלום', 'ja-JP': '支払い方法', 'de-DE': 'Zahlungsmethode', 'fr-FR': 'Mode de paiement', 'zh-CN': '付款方式' },
  'stepper.reviewConfirm': { 'en-US': 'Review & confirm', 'ar-SA': 'المراجعة والتأكيد', 'he-IL': 'סקירה ואישור', 'ja-JP': '確認と確定', 'de-DE': 'Prüfen & bestätigen', 'fr-FR': 'Vérifier et confirmer', 'zh-CN': '确认并提交' },
  'stepper.emailAddress': { 'en-US': 'Email address', 'ar-SA': 'عنوان البريد الإلكتروني', 'he-IL': 'כתובת אימייל', 'ja-JP': 'メールアドレス', 'de-DE': 'E-Mail-Adresse', 'fr-FR': 'Adresse e-mail', 'zh-CN': '电子邮件地址' },

  // ── Step descriptions ────────────────────────────────────────────
  'stepper.descAddressMethod': { 'en-US': 'Address & method', 'ar-SA': 'العنوان والطريقة', 'he-IL': 'כתובת ושיטה', 'ja-JP': '住所と方法', 'de-DE': 'Adresse & Methode', 'fr-FR': 'Adresse et méthode', 'zh-CN': '地址与方式' },
  'stepper.descYourDetails': { 'en-US': 'Your details', 'ar-SA': 'بياناتك', 'he-IL': 'הפרטים שלך', 'ja-JP': 'あなたの詳細', 'de-DE': 'Ihre Angaben', 'fr-FR': 'Vos coordonnées', 'zh-CN': '您的详细信息' },
  'stepper.descWhereToDeliver': { 'en-US': 'Where to deliver', 'ar-SA': 'مكان التسليم', 'he-IL': 'לאן לשלוח', 'ja-JP': '配送先', 'de-DE': 'Wohin liefern', 'fr-FR': 'Où livrer', 'zh-CN': '配送地点' },

  // ── Error / helper text ──────────────────────────────────────────
  'stepper.cardDeclined': { 'en-US': 'Card declined — try another', 'ar-SA': 'تم رفض البطاقة — جرّب بطاقة أخرى', 'he-IL': 'הכרטיס נדחה — נסה כרטיס אחר', 'ja-JP': 'カードが拒否されました — 別のカードをお試しください', 'de-DE': 'Karte abgelehnt — andere Karte versuchen', 'fr-FR': 'Carte refusée — essayez-en une autre', 'zh-CN': '卡被拒绝 — 请尝试其他卡' },

  // ── Explicit nav buttons (ImperativeControls) ────────────────────
  'stepper.continue': { 'en-US': 'Continue', 'ar-SA': 'متابعة', 'he-IL': 'המשך', 'ja-JP': '続行', 'de-DE': 'Weiter', 'fr-FR': 'Continuer', 'zh-CN': '继续' },
  'stepper.reset': { 'en-US': 'Reset', 'ar-SA': 'إعادة تعيين', 'he-IL': 'איפוס', 'ja-JP': 'リセット', 'de-DE': 'Zurücksetzen', 'fr-FR': 'Réinitialiser', 'zh-CN': '重置' },

  // ── Panel titles (distinct from step labels) ─────────────────────
  'stepper.welcomeAboard': { 'en-US': 'Welcome aboard', 'ar-SA': 'مرحبًا بك', 'he-IL': 'ברוכים הבאים', 'ja-JP': 'ようこそ', 'de-DE': 'Willkommen an Bord', 'fr-FR': 'Bienvenue à bord', 'zh-CN': '欢迎加入' },
  'stepper.yourProfile': { 'en-US': 'Your profile', 'ar-SA': 'ملفك الشخصي', 'he-IL': 'הפרופיל שלך', 'ja-JP': 'あなたのプロフィール', 'de-DE': 'Ihr Profil', 'fr-FR': 'Votre profil', 'zh-CN': '您的个人资料' },
  'stepper.allSet': { 'en-US': 'You are all set', 'ar-SA': 'كل شيء جاهز', 'he-IL': 'הכול מוכן', 'ja-JP': '準備完了', 'de-DE': 'Alles bereit', 'fr-FR': 'Tout est prêt', 'zh-CN': '一切就绪' },
  'stepper.connectRepo': { 'en-US': 'Connect a repository', 'ar-SA': 'اربط مستودعًا', 'he-IL': 'חבר מאגר', 'ja-JP': 'リポジトリを接続', 'de-DE': 'Repository verbinden', 'fr-FR': 'Connecter un dépôt', 'zh-CN': '连接仓库' },
  'stepper.configureBuild': { 'en-US': 'Configure the build', 'ar-SA': 'تهيئة عملية البناء', 'he-IL': 'הגדרת הבנייה', 'ja-JP': 'ビルドを構成', 'de-DE': 'Build konfigurieren', 'fr-FR': 'Configurer la build', 'zh-CN': '配置构建' },
  'stepper.addonsOptional': { 'en-US': 'Add-ons (optional)', 'ar-SA': 'الإضافات (اختياري)', 'he-IL': 'תוספות (אופציונלי)', 'ja-JP': 'アドオン（任意）', 'de-DE': 'Add-ons (optional)', 'fr-FR': 'Extras (facultatif)', 'zh-CN': '附加项（可选）' },
  'stepper.paymentActionNeeded': { 'en-US': 'Payment — action needed', 'ar-SA': 'الدفع — مطلوب إجراء', 'he-IL': 'תשלום — נדרשת פעולה', 'ja-JP': '支払い — 対応が必要です', 'de-DE': 'Zahlung — Aktion erforderlich', 'fr-FR': 'Paiement — action requise', 'zh-CN': '付款 — 需要处理' },
  'stepper.statusComplete': { 'en-US': 'Complete', 'ar-SA': 'مكتملة', 'he-IL': 'הושלם', 'ja-JP': '完了', 'de-DE': 'Abgeschlossen', 'fr-FR': 'Terminé', 'zh-CN': '已完成' },
  'stepper.statusInProgress': { 'en-US': 'In progress', 'ar-SA': 'قيد التنفيذ', 'he-IL': 'בתהליך', 'ja-JP': '進行中', 'de-DE': 'In Bearbeitung', 'fr-FR': 'En cours', 'zh-CN': '进行中' },
  'stepper.statusNotStarted': { 'en-US': 'Not started', 'ar-SA': 'لم تبدأ', 'he-IL': 'טרם החל', 'ja-JP': '未開始', 'de-DE': 'Nicht begonnen', 'fr-FR': 'Non commencé', 'zh-CN': '未开始' },

  // ── Status / completion messages ─────────────────────────────────
  'stepper.statusAllComplete': { 'en-US': '✓ All steps completed — mdComplete fired', 'ar-SA': '✓ اكتملت جميع الخطوات — تم إطلاق mdComplete', 'he-IL': '✓ כל השלבים הושלמו — mdComplete הופעל', 'ja-JP': '✓ すべてのステップが完了しました — mdComplete が発火', 'de-DE': '✓ Alle Schritte abgeschlossen — mdComplete ausgelöst', 'fr-FR': '✓ Toutes les étapes terminées — mdComplete déclenché', 'zh-CN': '✓ 所有步骤已完成 — mdComplete 已触发' },
  'stepper.statusOrderPlacedFired': { 'en-US': '✓ Order placed — mdComplete fired', 'ar-SA': '✓ تم تقديم الطلب — تم إطلاق mdComplete', 'he-IL': '✓ ההזמנה בוצעה — mdComplete הופעל', 'ja-JP': '✓ 注文が完了しました — mdComplete が発火', 'de-DE': '✓ Bestellung aufgegeben — mdComplete ausgelöst', 'fr-FR': '✓ Commande passée — mdComplete déclenché', 'zh-CN': '✓ 订单已提交 — mdComplete 已触发' },
  'stepper.statusOnboardingFinished': { 'en-US': '✓ Onboarding finished', 'ar-SA': '✓ اكتمل الإعداد', 'he-IL': '✓ ההצטרפות הושלמה', 'ja-JP': '✓ オンボーディング完了', 'de-DE': '✓ Onboarding abgeschlossen', 'fr-FR': '✓ Intégration terminée', 'zh-CN': '✓ 引导完成' },
  'stepper.statusDeployed': { 'en-US': '✓ Deployed to production', 'ar-SA': '✓ تم النشر إلى بيئة الإنتاج', 'he-IL': '✓ נפרס לסביבת הייצור', 'ja-JP': '✓ 本番環境にデプロイ完了', 'de-DE': '✓ In Produktion bereitgestellt', 'fr-FR': '✓ Déployé en production', 'zh-CN': '✓ 已部署到生产环境' },
  'stepper.statusAccountCreated': { 'en-US': '🎉 Account created — mdComplete fired', 'ar-SA': '🎉 تم إنشاء الحساب — تم إطلاق mdComplete', 'he-IL': '🎉 החשבון נוצר — mdComplete הופעל', 'ja-JP': '🎉 アカウントが作成されました — mdComplete が発火', 'de-DE': '🎉 Konto erstellt — mdComplete ausgelöst', 'fr-FR': '🎉 Compte créé — mdComplete déclenché', 'zh-CN': '🎉 账户已创建 — mdComplete 已触发' },
  'stepper.statusSurveySubmitted': { 'en-US': '✓ Survey submitted', 'ar-SA': '✓ تم إرسال الاستبيان', 'he-IL': '✓ הסקר נשלח', 'ja-JP': '✓ アンケートを送信しました', 'de-DE': '✓ Umfrage gesendet', 'fr-FR': '✓ Enquête envoyée', 'zh-CN': '✓ 问卷已提交' },
  'stepper.statusImperativeComplete': { 'en-US': '✓ mdComplete — next() past the last step', 'ar-SA': '✓ mdComplete — next() تجاوز الخطوة الأخيرة', 'he-IL': '✓ mdComplete — next() אחרי השלב האחרון', 'ja-JP': '✓ mdComplete — 最後のステップを超えた next()', 'de-DE': '✓ mdComplete — next() über den letzten Schritt hinaus', 'fr-FR': '✓ mdComplete — next() au-delà de la dernière étape', 'zh-CN': '✓ mdComplete — next() 越过最后一步' },
  'stepper.statusOrderPlaced': { 'en-US': '✓ Order placed', 'ar-SA': '✓ تم تقديم الطلب', 'he-IL': '✓ ההזמנה בוצעה', 'ja-JP': '✓ 注文が完了しました', 'de-DE': '✓ Bestellung aufgegeben', 'fr-FR': '✓ Commande passée', 'zh-CN': '✓ 订单已提交' },
  'stepper.statusPlacingOrder': { 'en-US': 'Placing order…', 'ar-SA': 'جارٍ تقديم الطلب…', 'he-IL': 'מבצע הזמנה…', 'ja-JP': '注文処理中…', 'de-DE': 'Bestellung wird aufgegeben…', 'fr-FR': 'Commande en cours…', 'zh-CN': '正在下单…' },

  // ── Checkout panels (content slot) ───────────────────────────────
  'stepper.checkoutCartBody': { 'en-US': '3 items — AWC hoodie, sticker pack, enamel mug. Subtotal €64.00. Continue when you are ready to ship.', 'ar-SA': '3 عناصر — سترة AWC، حزمة ملصقات، كوب مينا. المجموع الفرعي €64.00. تابع عندما تكون مستعدًا للشحن.', 'he-IL': '3 פריטים — קפוצ׳ון AWC, חבילת מדבקות, ספל אמייל. סכום ביניים €64.00. המשך כשתהיה מוכן למשלוח.', 'ja-JP': '3 点 — AWC パーカー、ステッカーパック、ホーローマグ。小計 €64.00。発送の準備ができたら続行してください。', 'de-DE': '3 Artikel — AWC-Hoodie, Sticker-Set, Emaille-Becher. Zwischensumme €64.00. Fahren Sie fort, wenn Sie versandbereit sind.', 'fr-FR': '3 articles — sweat à capuche AWC, pack d’autocollants, mug émaillé. Sous-total €64.00. Continuez quand vous êtes prêt à expédier.', 'zh-CN': '3 件商品 — AWC 连帽衫、贴纸套装、搪瓷马克杯。小计 €64.00。准备好发货后继续。' },
  'stepper.checkoutShippingBody': { 'en-US': 'Deliver to Str. Exemplu 12, București. Standard courier (2–3 days), free over €50.', 'ar-SA': 'التسليم إلى Str. Exemplu 12, București. بريد قياسي (2–3 أيام)، مجاني للطلبات فوق €50.', 'he-IL': 'משלוח אל Str. Exemplu 12, București. שליח רגיל (2–3 ימים), חינם מעל €50.', 'ja-JP': '配送先: Str. Exemplu 12, București。通常配送（2–3 日）、€50 以上で送料無料。', 'de-DE': 'Lieferung an Str. Exemplu 12, București. Standardversand (2–3 Tage), kostenlos ab €50.', 'fr-FR': 'Livraison à Str. Exemplu 12, București. Coursier standard (2–3 jours), gratuit au-delà de €50.', 'zh-CN': '配送至 Str. Exemplu 12, București。标准快递（2–3 天），满 €50 免运费。' },
  'stepper.checkoutPaymentBody': { 'en-US': 'Visa ending in 4242, expiring 08/28. You can also switch to pay-on-delivery here.', 'ar-SA': 'بطاقة Visa تنتهي بـ 4242، تنتهي صلاحيتها 08/28. يمكنك أيضًا التبديل إلى الدفع عند الاستلام هنا.', 'he-IL': 'כרטיס Visa המסתיים ב-4242, בתוקף עד 08/28. ניתן גם לעבור לתשלום במשלוח כאן.', 'ja-JP': '末尾 4242 の Visa カード、有効期限 08/28。ここで代金引換に切り替えることもできます。', 'de-DE': 'Visa mit Endung 4242, gültig bis 08/28. Sie können hier auch zur Zahlung bei Lieferung wechseln.', 'fr-FR': 'Visa se terminant par 4242, expirant le 08/28. Vous pouvez aussi passer au paiement à la livraison ici.', 'zh-CN': '尾号 4242 的 Visa 卡，有效期至 08/28。您也可以在此切换为货到付款。' },
  'stepper.checkoutReviewBody': { 'en-US': 'Everything look good? Press Finish to place the order — mdComplete fires on the last Continue.', 'ar-SA': 'هل كل شيء على ما يرام؟ اضغط "إنهاء" لتقديم الطلب — يُطلق mdComplete عند آخر "متابعة".', 'he-IL': 'הכול נראה תקין? לחץ על "סיום" לביצוע ההזמנה — mdComplete מופעל בלחיצה האחרונה על "המשך".', 'ja-JP': 'すべて問題ありませんか？「完了」を押して注文を確定します — 最後の「続行」で mdComplete が発火します。', 'de-DE': 'Sieht alles gut aus? Klicken Sie auf „Fertig", um die Bestellung aufzugeben — mdComplete wird beim letzten „Weiter" ausgelöst.', 'fr-FR': 'Tout est correct ? Appuyez sur « Terminer » pour passer la commande — mdComplete se déclenche au dernier « Continuer ».', 'zh-CN': '一切正常吗？点击“完成”以下单 — 在最后一次“继续”时触发 mdComplete。' },

  // ── Playground inline step content ───────────────────────────────
  'stepper.playgroundCartBody': { 'en-US': '3 items in your cart — hoodie, stickers, mug.', 'ar-SA': '3 عناصر في سلتك — سترة، ملصقات، كوب.', 'he-IL': '3 פריטים בעגלה — קפוצ׳ון, מדבקות, ספל.', 'ja-JP': 'カートに 3 点 — パーカー、ステッカー、マグ。', 'de-DE': '3 Artikel im Warenkorb — Hoodie, Sticker, Becher.', 'fr-FR': '3 articles dans votre panier — sweat, autocollants, mug.', 'zh-CN': '购物车中有 3 件商品 — 连帽衫、贴纸、马克杯。' },
  'stepper.playgroundShippingBody': { 'en-US': 'Deliver to Str. Exemplu 12, standard courier.', 'ar-SA': 'التسليم إلى Str. Exemplu 12، بريد قياسي.', 'he-IL': 'משלוח אל Str. Exemplu 12, שליח רגיל.', 'ja-JP': '配送先: Str. Exemplu 12、通常配送。', 'de-DE': 'Lieferung an Str. Exemplu 12, Standardversand.', 'fr-FR': 'Livraison à Str. Exemplu 12, coursier standard.', 'zh-CN': '配送至 Str. Exemplu 12，标准快递。' },
  'stepper.playgroundPaymentBody': { 'en-US': 'Visa ending in 4242 — or pay on delivery.', 'ar-SA': 'بطاقة Visa تنتهي بـ 4242 — أو الدفع عند الاستلام.', 'he-IL': 'כרטיס Visa המסתיים ב-4242 — או תשלום במשלוח.', 'ja-JP': '末尾 4242 の Visa — または代金引換。', 'de-DE': 'Visa mit Endung 4242 — oder Zahlung bei Lieferung.', 'fr-FR': 'Visa se terminant par 4242 — ou paiement à la livraison.', 'zh-CN': '尾号 4242 的 Visa — 或货到付款。' },
  'stepper.playgroundReviewBody': { 'en-US': 'Confirm and place your order.', 'ar-SA': 'أكّد وقدّم طلبك.', 'he-IL': 'אשר ובצע את ההזמנה.', 'ja-JP': '内容を確認して注文を確定します。', 'de-DE': 'Bestätigen Sie und geben Sie Ihre Bestellung auf.', 'fr-FR': 'Confirmez et passez votre commande.', 'zh-CN': '确认并提交您的订单。' },

  // ── Onboarding panels ────────────────────────────────────────────
  'stepper.onboardWelcomeBody': { 'en-US': 'A 60-second tour of your new workspace. Continue to set up your profile.', 'ar-SA': 'جولة مدتها 60 ثانية في مساحة عملك الجديدة. تابع لإعداد ملفك الشخصي.', 'he-IL': 'סיור בן 60 שניות בסביבת העבודה החדשה שלך. המשך כדי להגדיר את הפרופיל שלך.', 'ja-JP': '新しいワークスペースの 60 秒ツアー。続行してプロフィールを設定します。', 'de-DE': 'Eine 60-Sekunden-Tour durch Ihren neuen Arbeitsbereich. Fahren Sie fort, um Ihr Profil einzurichten.', 'fr-FR': 'Une visite de 60 secondes de votre nouvel espace de travail. Continuez pour configurer votre profil.', 'zh-CN': '用 60 秒快速浏览您的新工作区。继续设置您的个人资料。' },
  'stepper.onboardProfileBody': { 'en-US': 'Add a display name and avatar so teammates recognize you.', 'ar-SA': 'أضف اسمًا معروضًا وصورة رمزية ليتعرّف عليك زملاؤك.', 'he-IL': 'הוסף שם תצוגה ותמונת פרופיל כדי שחברי הצוות יזהו אותך.', 'ja-JP': '表示名とアバターを追加して、チームメンバーがあなたを認識できるようにします。', 'de-DE': 'Fügen Sie einen Anzeigenamen und ein Avatar hinzu, damit Teamkollegen Sie erkennen.', 'fr-FR': 'Ajoutez un nom d’affichage et un avatar pour que vos coéquipiers vous reconnaissent.', 'zh-CN': '添加显示名称和头像，以便队友认出您。' },
  'stepper.onboardPrefsBody': { 'en-US': 'Pick a theme, notification schedule and default landing page.', 'ar-SA': 'اختر سمة وجدول إشعارات وصفحة رئيسية افتراضية.', 'he-IL': 'בחר ערכת נושא, לוח זמנים להתראות ודף נחיתה ברירת מחדל.', 'ja-JP': 'テーマ、通知スケジュール、デフォルトのランディングページを選択します。', 'de-DE': 'Wählen Sie ein Design, einen Benachrichtigungszeitplan und eine Standard-Startseite.', 'fr-FR': 'Choisissez un thème, un calendrier de notifications et une page d’accueil par défaut.', 'zh-CN': '选择主题、通知时间表和默认着陆页。' },
  'stepper.onboardDoneBody': { 'en-US': 'Press Finish to jump into your dashboard.', 'ar-SA': 'اضغط "إنهاء" للانتقال إلى لوحة التحكم.', 'he-IL': 'לחץ על "סיום" כדי לעבור ללוח הבקרה שלך.', 'ja-JP': '「完了」を押してダッシュボードに移動します。', 'de-DE': 'Klicken Sie auf „Fertig", um zu Ihrem Dashboard zu gelangen.', 'fr-FR': 'Appuyez sur « Terminer » pour accéder à votre tableau de bord.', 'zh-CN': '点击“完成”进入您的仪表板。' },

  // ── Deploy panels ────────────────────────────────────────────────
  'stepper.deployConnectBody': { 'en-US': 'Authorize GitHub and pick the repo to deploy — read-only access is enough.', 'ar-SA': 'امنح تصريحًا لـ GitHub واختر المستودع المراد نشره — صلاحية القراءة فقط كافية.', 'he-IL': 'אשר את GitHub ובחר את המאגר לפריסה — הרשאת קריאה בלבד מספיקה.', 'ja-JP': 'GitHub を認可し、デプロイするリポジトリを選択します — 読み取り専用アクセスで十分です。', 'de-DE': 'Autorisieren Sie GitHub und wählen Sie das zu bereitstellende Repository — Lesezugriff genügt.', 'fr-FR': 'Autorisez GitHub et choisissez le dépôt à déployer — un accès en lecture seule suffit.', 'zh-CN': '授权 GitHub 并选择要部署的仓库 — 只读权限即可。' },
  'stepper.deployConfigBody': { 'en-US': 'Node 22, pnpm, `pnpm build`, output in dist/. Autodetected — adjust if needed.', 'ar-SA': 'Node 22 وpnpm و`pnpm build`، الإخراج في dist/. يتم اكتشافه تلقائيًا — عدّله عند الحاجة.', 'he-IL': 'Node 22, pnpm, `pnpm build`, פלט ב-dist/. מזוהה אוטומטית — התאם לפי הצורך.', 'ja-JP': 'Node 22、pnpm、`pnpm build`、出力は dist/。自動検出されます — 必要に応じて調整してください。', 'de-DE': 'Node 22, pnpm, `pnpm build`, Ausgabe in dist/. Automatisch erkannt — bei Bedarf anpassen.', 'fr-FR': 'Node 22, pnpm, `pnpm build`, sortie dans dist/. Détecté automatiquement — ajustez si nécessaire.', 'zh-CN': 'Node 22、pnpm、`pnpm build`，输出到 dist/。自动检测 — 如有需要可调整。' },
  'stepper.deployDeployBody': { 'en-US': 'Ship the first build to the edge network. Press Finish to trigger it.', 'ar-SA': 'انشر أول إصدار إلى شبكة الحافة. اضغط "إنهاء" لتشغيله.', 'he-IL': 'שלח את הבנייה הראשונה לרשת הקצה. לחץ על "סיום" כדי להפעיל אותה.', 'ja-JP': '最初のビルドをエッジネットワークに配信します。「完了」を押して実行します。', 'de-DE': 'Bringen Sie den ersten Build ins Edge-Netzwerk. Klicken Sie auf „Fertig", um ihn auszulösen.', 'fr-FR': 'Envoyez la première build vers le réseau de périphérie. Appuyez sur « Terminer » pour la déclencher.', 'zh-CN': '将首个构建发布到边缘网络。点击“完成”以触发。' },

  // ── Vertical wizard panels ───────────────────────────────────────
  'stepper.verticalAccountBody': { 'en-US': 'Create your account — name, email and a password you have not used elsewhere.', 'ar-SA': 'أنشئ حسابك — الاسم والبريد الإلكتروني وكلمة مرور لم تستخدمها في مكان آخر.', 'he-IL': 'צור את החשבון שלך — שם, אימייל וסיסמה שלא השתמשת בה במקום אחר.', 'ja-JP': 'アカウントを作成します — 名前、メール、他で使用していないパスワード。', 'de-DE': 'Erstellen Sie Ihr Konto — Name, E-Mail und ein Passwort, das Sie nirgendwo sonst verwendet haben.', 'fr-FR': 'Créez votre compte — nom, e-mail et un mot de passe que vous n’avez pas utilisé ailleurs.', 'zh-CN': '创建您的账户 — 姓名、电子邮件和一个您未在别处使用过的密码。' },
  'stepper.verticalShippingBody': { 'en-US': 'Enter the delivery address. Courier and locker pickup are both available.', 'ar-SA': 'أدخل عنوان التسليم. يتوفر كل من التوصيل عبر ساعي واستلام من الخزائن.', 'he-IL': 'הזן את כתובת המשלוח. איסוף באמצעות שליח ואיסוף מלוקר זמינים.', 'ja-JP': '配送先住所を入力します。宅配とロッカー受け取りの両方が利用できます。', 'de-DE': 'Geben Sie die Lieferadresse ein. Kurier- und Locker-Abholung sind beide verfügbar.', 'fr-FR': 'Saisissez l’adresse de livraison. La livraison par coursier et le retrait en consigne sont disponibles.', 'zh-CN': '输入配送地址。快递配送和自提柜取货均可选择。' },
  'stepper.verticalPaymentBody': { 'en-US': 'Add a card or choose pay on delivery. Cards are stored with your provider, not us.', 'ar-SA': 'أضف بطاقة أو اختر الدفع عند الاستلام. تُخزَّن البطاقات لدى مزوّدك، وليس لدينا.', 'he-IL': 'הוסף כרטיס או בחר תשלום במשלוח. הכרטיסים נשמרים אצל הספק שלך, לא אצלנו.', 'ja-JP': 'カードを追加するか、代金引換を選択します。カード情報は当社ではなく、プロバイダーに保存されます。', 'de-DE': 'Fügen Sie eine Karte hinzu oder wählen Sie Zahlung bei Lieferung. Karten werden bei Ihrem Anbieter gespeichert, nicht bei uns.', 'fr-FR': 'Ajoutez une carte ou choisissez le paiement à la livraison. Les cartes sont stockées chez votre fournisseur, pas chez nous.', 'zh-CN': '添加银行卡或选择货到付款。卡信息存储在您的服务商处，而非我们这里。' },
  'stepper.verticalReviewBody': { 'en-US': 'Everything look good? Press Finish to place the order.', 'ar-SA': 'هل كل شيء على ما يرام؟ اضغط "إنهاء" لتقديم الطلب.', 'he-IL': 'הכול נראה תקין? לחץ על "סיום" לביצוע ההזמנה.', 'ja-JP': 'すべて問題ありませんか？「完了」を押して注文を確定します。', 'de-DE': 'Sieht alles gut aus? Klicken Sie auf „Fertig", um die Bestellung aufzugeben.', 'fr-FR': 'Tout est correct ? Appuyez sur « Terminer » pour passer la commande.', 'zh-CN': '一切正常吗？点击“完成”以下单。' },

  // ── Optional / editable / error panels ───────────────────────────
  'stepper.optionalAccountBody': { 'en-US': 'Signed in as ionut@example.com.', 'ar-SA': 'تم تسجيل الدخول باسم ionut@example.com.', 'he-IL': 'מחובר בתור ionut@example.com.', 'ja-JP': 'ionut@example.com としてサインインしています。', 'de-DE': 'Angemeldet als ionut@example.com.', 'fr-FR': 'Connecté en tant que ionut@example.com.', 'zh-CN': '已以 ionut@example.com 登录。' },
  'stepper.optionalAddonsBody': { 'en-US': 'Gift wrap, priority handling, a handwritten note — or just skip ahead with Continue.', 'ar-SA': 'تغليف الهدايا، معالجة ذات أولوية، ملاحظة مكتوبة بخط اليد — أو تخطَّ ذلك بالضغط على "متابعة".', 'he-IL': 'עטיפת מתנה, טיפול בעדיפות, פתק בכתב יד — או פשוט דלג קדימה עם "המשך".', 'ja-JP': 'ギフトラッピング、優先処理、手書きのメモ — または「続行」でスキップします。', 'de-DE': 'Geschenkverpackung, bevorzugte Bearbeitung, eine handschriftliche Notiz — oder überspringen Sie einfach mit „Weiter".', 'fr-FR': 'Emballage cadeau, traitement prioritaire, une note manuscrite — ou passez directement avec « Continuer ».', 'zh-CN': '礼品包装、优先处理、手写便条 — 或直接点击“继续”跳过。' },
  'stepper.optionalPaymentBody': { 'en-US': 'Add a card to finish.', 'ar-SA': 'أضف بطاقة للإنهاء.', 'he-IL': 'הוסף כרטיס לסיום.', 'ja-JP': 'カードを追加して完了します。', 'de-DE': 'Fügen Sie eine Karte hinzu, um abzuschließen.', 'fr-FR': 'Ajoutez une carte pour terminer.', 'zh-CN': '添加银行卡以完成。' },
  'stepper.editableAccountBody': { 'en-US': 'Revisiting a completed, editable step — downstream progress is preserved.', 'ar-SA': 'إعادة زيارة خطوة مكتملة قابلة للتحرير — يتم الحفاظ على التقدم اللاحق.', 'he-IL': 'חזרה לשלב שהושלם וניתן לעריכה — ההתקדמות שבהמשך נשמרת.', 'ja-JP': '完了済みで編集可能なステップを再訪 — 後続の進捗は保持されます。', 'de-DE': 'Ein abgeschlossener, bearbeitbarer Schritt wird erneut besucht — der nachfolgende Fortschritt bleibt erhalten.', 'fr-FR': 'Retour sur une étape terminée et modifiable — la progression en aval est préservée.', 'zh-CN': '重新访问已完成、可编辑的步骤 — 后续进度将被保留。' },
  'stepper.editableShippingBody': { 'en-US': 'Change the address or courier without losing the Payment step.', 'ar-SA': 'غيّر العنوان أو الساعي دون فقدان خطوة الدفع.', 'he-IL': 'שנה את הכתובת או השליח מבלי לאבד את שלב התשלום.', 'ja-JP': '支払いステップを失うことなく、住所や配送業者を変更できます。', 'de-DE': 'Ändern Sie die Adresse oder den Kurier, ohne den Zahlungsschritt zu verlieren.', 'fr-FR': 'Modifiez l’adresse ou le coursier sans perdre l’étape de paiement.', 'zh-CN': '在不丢失付款步骤的情况下更改地址或快递。' },
  'stepper.editablePaymentBody': { 'en-US': 'The two earlier steps stay checked while you edit them — click their pencils to jump back.', 'ar-SA': 'تبقى الخطوتان السابقتان محددتين أثناء تحريرهما — انقر على أقلامهما للعودة إليهما.', 'he-IL': 'שני השלבים הקודמים נשארים מסומנים בזמן העריכה — לחץ על העפרונות שלהם כדי לחזור.', 'ja-JP': '編集中も前の 2 つのステップはチェックされたままです — 鉛筆アイコンをクリックして戻ります。', 'de-DE': 'Die beiden vorherigen Schritte bleiben markiert, während Sie sie bearbeiten — klicken Sie auf ihre Stifte, um zurückzuspringen.', 'fr-FR': 'Les deux étapes précédentes restent cochées pendant que vous les modifiez — cliquez sur leurs crayons pour y revenir.', 'zh-CN': '编辑时前两个步骤保持勾选状态 — 点击它们的铅笔图标即可跳回。' },
  'stepper.errorAccountBody': { 'en-US': 'Signed in.', 'ar-SA': 'تم تسجيل الدخول.', 'he-IL': 'מחובר.', 'ja-JP': 'サインインしました。', 'de-DE': 'Angemeldet.', 'fr-FR': 'Connecté.', 'zh-CN': '已登录。' },
  'stepper.errorShippingBody': { 'en-US': 'Address confirmed.', 'ar-SA': 'تم تأكيد العنوان.', 'he-IL': 'הכתובת אושרה.', 'ja-JP': '住所を確認しました。', 'de-DE': 'Adresse bestätigt.', 'fr-FR': 'Adresse confirmée.', 'zh-CN': '地址已确认。' },
  'stepper.errorPaymentBody': { 'en-US': 'The card was declined by the issuer. Try another card or pay on delivery.', 'ar-SA': 'تم رفض البطاقة من قبل الجهة المُصدِرة. جرّب بطاقة أخرى أو ادفع عند الاستلام.', 'he-IL': 'הכרטיס נדחה על ידי המנפיק. נסה כרטיס אחר או שלם במשלוח.', 'ja-JP': 'カードが発行会社によって拒否されました。別のカードを試すか、代金引換でお支払いください。', 'de-DE': 'Die Karte wurde vom Aussteller abgelehnt. Versuchen Sie eine andere Karte oder zahlen Sie bei Lieferung.', 'fr-FR': 'La carte a été refusée par l’émetteur. Essayez une autre carte ou payez à la livraison.', 'zh-CN': '该卡被发卡机构拒绝。请尝试其他卡或货到付款。' },

  // ── Survey panels (non-linear) ───────────────────────────────────
  'stepper.surveyPersonalBody': { 'en-US': 'Name and contact — already filled in.', 'ar-SA': 'الاسم وجهة الاتصال — تم ملؤهما بالفعل.', 'he-IL': 'שם ופרטי קשר — כבר מולאו.', 'ja-JP': '名前と連絡先 — すでに入力済みです。', 'de-DE': 'Name und Kontakt — bereits ausgefüllt.', 'fr-FR': 'Nom et contact — déjà remplis.', 'zh-CN': '姓名和联系方式 — 已填写。' },
  'stepper.surveyAddressBody': { 'en-US': 'Confirmed. Jump anywhere; non-linear mode never blocks.', 'ar-SA': 'تم التأكيد. انتقل إلى أي مكان؛ الوضع غير الخطي لا يحظر أبدًا.', 'he-IL': 'אושר. קפוץ לכל מקום; מצב לא-לינארי לעולם אינו חוסם.', 'ja-JP': '確認済み。どこへでも移動できます。非線形モードは決してブロックしません。', 'de-DE': 'Bestätigt. Springen Sie überallhin; der nicht-lineare Modus blockiert nie.', 'fr-FR': 'Confirmé. Naviguez où vous voulez ; le mode non linéaire ne bloque jamais.', 'zh-CN': '已确认。可跳转到任意步骤；非线性模式从不阻止。' },
  'stepper.surveyReviewBody': { 'en-US': 'Check both sections, or click straight to Pay.', 'ar-SA': 'راجع كلا القسمين، أو انقر مباشرةً للانتقال إلى الدفع.', 'he-IL': 'בדוק את שני החלקים, או לחץ ישירות לתשלום.', 'ja-JP': '両方のセクションを確認するか、そのまま「支払う」をクリックします。', 'de-DE': 'Prüfen Sie beide Abschnitte oder klicken Sie direkt auf „Bezahlen".', 'fr-FR': 'Vérifiez les deux sections ou cliquez directement sur « Payer ».', 'zh-CN': '检查两个部分，或直接点击“支付”。' },
  'stepper.surveyPayBody': { 'en-US': 'Finish fires mdComplete.', 'ar-SA': 'يؤدي "إنهاء" إلى إطلاق mdComplete.', 'he-IL': '"סיום" מפעיל את mdComplete.', 'ja-JP': '「完了」で mdComplete が発火します。', 'de-DE': '„Fertig" löst mdComplete aus.', 'fr-FR': '« Terminer » déclenche mdComplete.', 'zh-CN': '“完成”会触发 mdComplete。' },

  // ── Validation & async ───────────────────────────────────────────
  'stepper.vaPlaceholder': { 'en-US': 'Type something to enable Continue', 'ar-SA': 'اكتب شيئًا لتفعيل "متابعة"', 'he-IL': 'הקלד משהו כדי לאפשר "המשך"', 'ja-JP': '「続行」を有効にするには何か入力してください', 'de-DE': 'Geben Sie etwas ein, um „Weiter" zu aktivieren', 'fr-FR': 'Saisissez quelque chose pour activer « Continuer »', 'zh-CN': '输入内容以启用“继续”' },
  'stepper.vaReviewNote': { 'en-US': 'Press Finish to place the order - it submits asynchronously.', 'ar-SA': 'اضغط "إنهاء" لتقديم الطلب - يتم الإرسال بشكل غير متزامن.', 'he-IL': 'לחץ על "סיום" לביצוע ההזמנה - השליחה מתבצעת באופן אסינכרוני.', 'ja-JP': '「完了」を押して注文を確定します - 非同期で送信されます。', 'de-DE': 'Klicken Sie auf „Fertig", um die Bestellung aufzugeben - sie wird asynchron gesendet.', 'fr-FR': 'Appuyez sur « Terminer » pour passer la commande - elle est envoyée de façon asynchrone.', 'zh-CN': '点击“完成”以下单 - 将以异步方式提交。' },
};
