export const arabic = {
  "Operations control": "إدارة العمليات",
  "Central metro": "المترو المركزي",
  "Central metro · Operations control": "المترو المركزي · إدارة العمليات",
  "Metro pulse": "Metro pulse",
  "Powered by awc-ui": "مدعوم بمكتبة awc-ui",
  "Built with": "طُوّر باستخدام",
  "Built with awc-ui": "طُوّر باستخدام awc-ui",
  Overview: "نظرة عامة",
  Stations: "المحطات",
  Incidents: "البلاغات",
  Settings: "الإعدادات",
  Workspace: "مساحة العمل",
  "Demo workspace": "مساحة عمل تجريبية",
  "Main navigation": "التنقل الرئيسي",
  "Toggle sidebar": "توسيع الشريط الجانبي أو طيّه",
  "Expand sidebar": "توسيع الشريط الجانبي",
  "Collapse sidebar": "طيّ الشريط الجانبي",
  "Close navigation": "إغلاق قائمة التنقل",
  "Toggle navigation": "فتح قائمة التنقل أو إغلاقها",
  "Skip to content": "انتقل إلى المحتوى",
  "Network overview": "نظرة عامة على الشبكة",
  "Network overview · Metro pulse": "نظرة عامة على الشبكة · Metro pulse",
  "Incident center": "مركز البلاغات",
  "Workspace settings": "إعدادات مساحة العمل",
  Operations: "العمليات",
  "Operations / Central metro": "العمليات / المترو المركزي",
  "Demo environment": "بيئة تجريبية",
  "Simulation running": "المحاكاة قيد التشغيل",
  "Simulation paused": "المحاكاة متوقفة مؤقتًا",
  "Simulation resumed.": "استؤنفت المحاكاة.",
  "Simulation paused.": "أُوقفت المحاكاة مؤقتًا.",
  "A safe space to explore metro operations.":
    "بيئة آمنة لاستكشاف عمليات المترو.",
  "Network operator": "مشغّل الشبكة",
  "Sign out": "تسجيل الخروج",
  "Open incidents": "فتح البلاغات",
  "Use dark theme": "استخدام المظهر الداكن",
  "Use light theme": "استخدام المظهر الفاتح",
  "Your network at a glance. Every station, every signal.":
    "شبكتك في لمحة. كل محطة، وكل إشارة.",
  "Monitor station health, capacity, and passenger movement.":
    "راقب حالة المحطات وسعتها وحركة الركاب.",
  "Coordinate the response and keep your network moving.":
    "نسّق الاستجابة وحافظ على انسيابية حركة الشبكة.",
  "Make this control room work for you.":
    "اضبط غرفة التحكم بما يناسب احتياجاتك.",
  "Updating every 15s": "تحديث كل 15 ثانية",
  "Updates paused": "التحديثات متوقفة مؤقتًا",
  "Export report": "تصدير التقرير",
  "Metro line filters": "تصفية خطوط المترو",
  "All lines": "جميع الخطوط",
  "Simulated morning peak · 08:45": "محاكاة ذروة الصباح · 08:45",
  "Network performance": "أداء الشبكة",
  "Stations online": "المحطات المتصلة",
  "All connected": "جميع المحطات متصلة",
  "Passengers / hour": "الركاب / ساعة",
  "Pax / hour": "الركاب / ساعة",
  "Morning peak": "ذروة الصباح",
  "Average headway": "متوسط الفاصل بين القطارات",
  "Within 4 min target": "ضمن المعدل المستهدف: 4 دقائق",
  "Active incidents": "البلاغات النشطة",
  "awaiting response": "بانتظار الاستجابة",
  Review: "مراجعة",
  "Live network": "الشبكة المباشرة",
  "Follow simulated trains or select a station.":
    "تابع القطارات في المحاكاة أو اختر محطة.",
  Connected: "متصل",
  "3 lines": "3 خطوط",
  stations: "محطات",
  "connected lines": "خطوط مترابطة",
  "Schematic · Demo network": "مخطط توضيحي · شبكة تجريبية",
  "View all incidents": "عرض جميع البلاغات",
  "All clear": "كل شيء على ما يرام",
  "No active incidents on this line.": "لا توجد بلاغات نشطة على هذا الخط.",
  "Incident actions affect this demo session.":
    "تسري إجراءات البلاغات على هذه الجلسة التجريبية.",
  "Passenger flow": "تدفق الركاب",
  "Entries and exits across": "حركة الدخول والخروج عبر",
  "Entries and exits across the network": "حركة الدخول والخروج عبر الشبكة",
  Entries: "الدخول",
  Exits: "الخروج",
  "the network": "الشبكة",
  Today: "اليوم",
  "This week": "هذا الأسبوع",
  "Passenger entries and exits": "دخول الركاب وخروجهم",
  "Station watchlist": "قائمة متابعة المحطات",
  "Latest telemetry across your selected lines":
    "أحدث بيانات الرصد للخطوط التي اخترتها",
  "View all stations": "عرض جميع المحطات",
  "Metro station telemetry": "بيانات رصد محطات المترو",
  Station: "المحطة",
  Line: "الخط",
  Lines: "الخطوط",
  Status: "الحالة",
  Occupancy: "نسبة الإشغال",
  Details: "التفاصيل",
  "No stations match": "لا توجد محطات مطابقة",
  "Try another station name or clear the filters.":
    "جرّب اسم محطة آخر أو أزل عوامل التصفية.",
  "Clear filters": "إزالة عوامل التصفية",
  "Search stations": "البحث عن محطة",
  "Station status": "حالة المحطة",
  "All statuses": "جميع الحالات",
  Operational: "تعمل بشكل طبيعي",
  "Needs attention": "تحتاج إلى متابعة",
  Busy: "مزدحمة",
  Active: "نشطة",
  Open: "مفتوح",
  Resolved: "تم الحل",
  Acknowledged: "تم الاستلام",
  "View station": "عرض المحطة",
  Acknowledge: "تأكيد الاستلام",
  "Resolve incident": "حل البلاغ",
  Resolve: "حل البلاغ",
  "Incident resolved in this demo session.":
    "تم حل البلاغ في هذه الجلسة التجريبية.",
  "Incident acknowledged. Response team notified in simulation.":
    "تم تأكيد استلام البلاغ وإخطار فريق الاستجابة ضمن المحاكاة.",
  "This part of the network is clear.":
    "لا توجد بلاغات في هذا الجزء من الشبكة.",
  "Resolved incidents will appear here.": "ستظهر هنا البلاغات التي تم حلّها.",
  "No active incidents": "لا توجد بلاغات نشطة",
  "No resolved incidents": "لا توجد بلاغات تم حلّها",
  "Display & telemetry": "العرض وبيانات الرصد",
  "Dark appearance": "المظهر الداكن",
  "Reduce glare in the control room.": "خفّف الوهج في غرفة التحكم.",
  "Simulated live updates": "تحديثات مباشرة للمحاكاة",
  "Refresh passenger counts every 15 seconds.":
    "تحديث أعداد الركاب كل 15 ثانية.",
  "Account & access": "الحساب والوصول",
  "Demo authentication": "مصادقة تجريبية",
  "Login, signup, and MFA demonstrate the interface. No real identity service is connected.":
    "توضح عمليات تسجيل الدخول وإنشاء الحساب والمصادقة متعددة العوامل طريقة استخدام الواجهة. لا توجد خدمة هوية فعلية متصلة.",
  "Simulated data · For demonstration": "بيانات محاكاة · لأغراض العرض",
  "Station details": "تفاصيل المحطة",
  "Simulated telemetry": "بيانات رصد محاكاة",
  "Platform occupancy": "نسبة إشغال الرصيف",
  "High demand. Monitor platform access.":
    "إقبال مرتفع. راقب الدخول إلى الرصيف.",
  "Capacity is within the operating range.": "الإشغال ضمن الحدود التشغيلية.",
  Headway: "الفاصل بين القطارات",
  Temperature: "درجة الحرارة",
  "Equipment available": "المعدات المتاحة",
  "Occupancy trend": "تغيّر نسبة الإشغال",
  "Station incidents": "بلاغات المحطة",
  "No incidents reported at this station.": "لم تُسجّل بلاغات في هذه المحطة.",
  "Close details": "إغلاق التفاصيل",
  "Station ID": "معرّف المحطة",
  "Occupancy (%)": "نسبة الإشغال (%)",
  "Headway (min)": "الفاصل بين القطارات (min)",
  "River line": "خط النهر",
  "Airport line": "خط المطار",
  "Garden line": "خط الحدائق",
  Westgate: "البوابة الغربية",
  Riverside: "ضفة النهر",
  "Central exchange": "التقاطع المركزي",
  "City hall": "دار البلدية",
  "East market": "السوق الشرقي",
  Eastend: "الطرف الشرقي",
  "North park": "المنتزه الشمالي",
  "Museum quarter": "حي المتحف",
  Southbank: "الضفة الجنوبية",
  "Airport terminal": "مبنى المطار",
  Hillcrest: "قمة التل",
  "Botanical garden": "الحديقة النباتية",
  University: "الجامعة",
  "Tech park": "مجمع التقنية",
  "Innovation hub": "مركز الابتكار",
  "River Alder": "نهر ألدر",
  "High platform occupancy": "ارتفاع إشغال الرصيف",
  "Platform 2 is above the 85% occupancy threshold. Open the overflow entrance and direct passengers to the rear carriages.":
    "تجاوز إشغال الرصيف 2 الحد المحدد بنسبة 85%. افتح المدخل الإضافي ووجّه الركاب إلى العربات الخلفية.",
  "Lift E-02 unavailable": "المصعد E-02 خارج الخدمة",
  "The east entrance lift is out of service. Step-free access is available from the west entrance. Maintenance team ETA: 09:15.":
    "مصعد المدخل الشرقي خارج الخدمة. يتوفر مسار وصول دون درجات عبر المدخل الغربي. الوصول المتوقع لفريق الصيانة: 09:15.",
  "Ventilation inspection due": "حان موعد فحص التهوية",
  "Air handling unit AHU-03 reported reduced output. Air quality remains within the operating range; a technician has been assigned.":
    "أبلغت وحدة مناولة الهواء AHU-03 عن انخفاض في الأداء. لا تزال جودة الهواء ضمن الحدود التشغيلية؛ وقد تم تكليف فني بالمتابعة.",
  Accessibility: "إمكانية الوصول",
  Equipment: "المعدات",
  "Unknown incident state": "حالة البلاغ غير معروفة",
  Mon: "الاثنين",
  Tue: "الثلاثاء",
  Wed: "الأربعاء",
  Thu: "الخميس",
  Fri: "الجمعة",
  Sat: "السبت",
  Sun: "الأحد",
  "Simulated train movement": "محاكاة حركة القطارات",
  "Network paused": "الشبكة متوقفة مؤقتًا",
  Running: "قيد التشغيل",
  Paused: "متوقف مؤقتًا",
  "Pause trains": "إيقاف القطارات مؤقتًا",
  "Play trains": "تشغيل القطارات",
  Pause: "إيقاف مؤقت",
  Play: "تشغيل",
  "Simulation speed": "سرعة المحاكاة",
  "Schematic of the simulated metro network":
    "مخطط توضيحي لشبكة المترو في المحاكاة",
  "Inspect a simulated train": "عرض تفاصيل قطار في المحاكاة",
  Boarding: "صعود الركاب",
  "In transit": "في الطريق",
  At: "في",
  From: "من",
  Toward: "باتجاه",
  "A clear view.": "رؤية واضحة.",
  "A moving city.": "مدينة تنبض بالحركة.",
  "One place to monitor every station, understand passenger flow, and keep your network moving.":
    "مكان واحد لمراقبة كل محطة وفهم تدفق الركاب والحفاظ على انسيابية حركة الشبكة.",
  "Simulated network": "شبكة محاكاة",
  "Network online": "الشبكة متصلة",
  "Station telemetry": "بيانات رصد المحطات",
  "MFA flow": "خطوات المصادقة متعددة العوامل",
  "Incident response": "الاستجابة للبلاغات",
  "Interactive showcase": "عرض تفاعلي",
  "Toggle appearance": "تبديل المظهر",
  "Sign in": "تسجيل الدخول",
  "Create account": "إنشاء حساب",
  "Verify identity": "التحقق من الهوية",
  "Step 2 of 2 · Verify identity": "الخطوة 2 من 2 · التحقق من الهوية",
  "Step 1 of 2 · Account access": "الخطوة 1 من 2 · الوصول إلى الحساب",
  "Use a recovery code": "استخدام رمز استرداد",
  "Set up verification": "إعداد التحقق",
  "Verify it’s you": "تحقق من هويتك",
  "Create your account": "أنشئ حسابك",
  "Welcome back": "مرحبًا بعودتك",
  "Enter your eight-character demo recovery code.":
    "أدخل رمز الاسترداد التجريبي المكوّن من ثمانية محارف.",
  "Enter the six-digit demo code to finish setting up your account.":
    "أدخل الرمز التجريبي المكوّن من ستة أرقام لإكمال إعداد حسابك.",
  "Enter the six-digit demo code to continue to your workspace.":
    "أدخل الرمز التجريبي المكوّن من ستة أرقام للمتابعة إلى مساحة عملك.",
  "finish setting up your account": "إكمال إعداد حسابك",
  "continue to your workspace": "المتابعة إلى مساحة عملك",
  "Join your metro operations workspace.": "انضم إلى مساحة عمل عمليات المترو.",
  "Sign in to your metro operations workspace.":
    "سجّل الدخول إلى مساحة عمل عمليات المترو.",
  "Full name": "الاسم الكامل",
  "Work email": "البريد الإلكتروني للعمل",
  Password: "كلمة المرور",
  "Use at least 12 characters. Choose a demo-only password.":
    "استخدم 12 محرفًا على الأقل. اختر كلمة مرور مخصصة للتجربة فقط.",
  "Confirm password": "تأكيد كلمة المرور",
  "Passwords do not match": "كلمتا المرور غير متطابقتين",
  "I understand this creates a temporary demo account":
    "أدرك أن هذا الإجراء ينشئ حسابًا تجريبيًا مؤقتًا",
  "I understand this creates a temporary demo account.":
    "أدرك أن هذا الإجراء ينشئ حسابًا تجريبيًا مؤقتًا.",
  "Account email": "البريد الإلكتروني للحساب",
  "Recovery code": "رمز الاسترداد",
  "Verification code": "رمز التحقق",
  "Enter all eight characters.": "أدخل المحارف الثمانية كاملةً.",
  "Enter all six digits.": "أدخل الأرقام الستة كاملةً.",
  "Enter your code to continue.": "أدخل الرمز للمتابعة.",
  "Demo recovery code": "رمز الاسترداد التجريبي",
  "Demo verification code": "رمز التحقق التجريبي",
  "One use per account in this session.":
    "يُستخدم مرة واحدة لكل حساب خلال هذه الجلسة.",
  "For this showcase only · Expires in 5 minutes":
    "لهذا العرض فقط · تنتهي صلاحيته خلال 5 دقائق",
  "Verify & continue": "التحقق والمتابعة",
  "Use demo credentials": "استخدام بيانات الدخول التجريبية",
  "Demo code refreshed. No email or SMS was sent.":
    "تم تحديث الرمز التجريبي. لم تُرسل رسالة بريد إلكتروني أو رسالة نصية.",
  "Refresh demo code": "تحديث الرمز التجريبي",
  "Use verification code": "استخدام رمز التحقق",
  "Back to sign in": "العودة إلى تسجيل الدخول",
  "Already have an account?": "هل لديك حساب بالفعل؟",
  "New to Metro pulse?": "هل تستخدم Metro pulse لأول مرة؟",
  "Create an account": "إنشاء حساب",
  "This showcase uses simulated accounts and MFA. Accounts last until you reload the page. No real credentials or station systems are connected.":
    "يعتمد هذا العرض على محاكاة الحسابات والمصادقة متعددة العوامل. تبقى الحسابات متاحة حتى تعيد تحميل الصفحة. لا توجد بيانات دخول حقيقية أو أنظمة محطات متصلة.",
  "Demo access · No real identity service": "وصول تجريبي · دون خدمة هوية فعلية",
  "Something went wrong. Please try again.":
    "حدث خطأ. يُرجى المحاولة مرة أخرى.",
  "Demo credentials filled. Continue to sign in.":
    "تم إدخال بيانات الدخول التجريبية. تابع لتسجيل الدخول.",
  "Enter your name and a valid email address.":
    "أدخل اسمك وعنوان بريد إلكتروني صالحًا.",
  "Use at least 12 characters for your demo password.":
    "استخدم كلمة مرور تجريبية بطول 12 محرفًا على الأقل.",
  "Your passwords do not match.": "كلمتا المرور غير متطابقتين.",
  "This demo account already exists. Sign in instead.":
    "هذا الحساب التجريبي موجود بالفعل. سجّل الدخول إليه.",
  "This request was canceled.": "تم إلغاء هذا الطلب.",
  "Email or password is incorrect. Use the demo account or create an account for this session.":
    "البريد الإلكتروني أو كلمة المرور غير صحيحة. استخدم الحساب التجريبي أو أنشئ حسابًا لهذه الجلسة.",
  "Sign in again to request a verification code.":
    "سجّل الدخول مجددًا لطلب رمز تحقق.",
  "Your code has expired. Sign in again.":
    "انتهت صلاحية الرمز. سجّل الدخول مجددًا.",
  "Too many attempts. Wait 30 seconds, then try again.":
    "تجاوزت عدد المحاولات المسموح به. انتظر 30 ثانية ثم حاول مجددًا.",
  "That recovery code is invalid or already used.":
    "رمز الاسترداد غير صالح أو سبق استخدامه.",
  "That code is incorrect. Use the six-digit demo code shown below.":
    "الرمز غير صحيح. استخدم الرمز التجريبي المكوّن من ستة أرقام والظاهر أدناه.",
  "Sign in again to request a code.": "سجّل الدخول مجددًا لطلب رمز.",
  "Wait for the attempt limit to reset.":
    "انتظر حتى يُسمح لك بالمحاولة مجددًا.",
  "Make it yours": "خصّصها كما تحب",
  "Your control room, your preferences.": "غرفة تحكم تناسب تفضيلاتك.",
  Appearance: "المظهر",
  Light: "فاتح",
  Dark: "داكن",
  "Primary color": "اللون الأساسي",
  Density: "كثافة الواجهة",
  "Interface density": "كثافة عناصر الواجهة",
  Comfortable: "مريحة",
  "Cozy · default": "متوازنة · الافتراضية",
  Compact: "مدمجة",
  Dense: "كثيفة",
  "Extra dense": "شديدة الكثافة",
  "Right-to-left layout": "تخطيط من اليمين إلى اليسار",
  "Mirror navigation and reading direction.": "اعكس اتجاه التنقل والقراءة.",
  "Saved on this device.": "تم الحفظ على هذا الجهاز.",
  "Changes apply for this session. Browser storage is unavailable.":
    "تسري التغييرات على هذه الجلسة فقط. التخزين في المتصفح غير متاح.",
  "Reset customization": "إعادة ضبط التخصيص",
  Done: "تم",
  metro: "metro",
  pulse: "pulse",
  "awc-ui": "awc-ui",
  "AWC UI": "AWC UI",
  No: "لا توجد",
  incidents: "بلاغات",
  "· Simulated telemetry": "· بيانات رصد محاكاة",
  "trains ·": "قطارات ·",
  "Alex Morgan": "أليكس مورغان",
  "Exported {count} stations.": "تم تصدير بيانات {count} محطة.",
  "{station} occupancy": "نسبة الإشغال في {station}",
  "View {station}": "عرض {station}",
  "%from%–%to% of %count%": "%from%–%to% من %count%",
  "Rows per page:": "الصفوف في الصفحة:",
  "First page": "الصفحة الأولى",
  "Previous page": "الصفحة السابقة",
  "Next page": "الصفحة التالية",
  "Last page": "الصفحة الأخيرة",
  All: "الكل",
  min: "دقيقة",
  "°C": "°م",
  "Passenger entries and exits over the selected period.":
    "حركة دخول الركاب وخروجهم خلال الفترة المحددة.",
  "No data available": "لا توجد بيانات متاحة",
  "Loading chart": "جارٍ تحميل المخطط",
  "Plot area": "منطقة الرسم",
  "{label}: {value}": "{label}: {value}",
  "Start of visible range": "بداية النطاق المعروض",
  "End of visible range": "نهاية النطاق المعروض",
  Time: "الوقت",
  Point: "النقطة",
  Series: "السلسلة",
  "Showing first {count} rows": "عرض أول {count} صف",
  "Clear search": "مسح البحث",
  Dismiss: "إغلاق",
  "{count} connected lines": "{count} خطوط مترابطة",
  "Hide password": "إخفاء كلمة المرور",
  "Show password": "إظهار كلمة المرور",
  "Character {index} of {length}": "الخانة {index} من {length}",
  "Refresh code in {seconds}s": "تحديث الرمز بعد {seconds} ثانية",
  "{speed} times simulation speed": "سرعة المحاكاة ×{speed}",
  "{station}, {status}, {occupancy}% occupancy":
    "{station}، {status}، نسبة الإشغال {occupancy}٪",
  "At {station}": "في {station}",
  "From {station}": "من {station}",
  "Toward {station}": "باتجاه {station}",
  "Close settings": "إغلاق الإعدادات",
  Language: "اللغة",
  "Show {line}": "عرض {line}",
  "Too many attempts. Try again in {seconds} seconds.":
    "تجاوزت عدد المحاولات المسموح به. حاول مجددًا بعد {seconds} ثانية.",
  "Entries and exits across {scope}": "حركة الدخول والخروج عبر {scope}",
  "Please complete the required fields with valid values.":
    "يرجى إكمال الحقول المطلوبة بقيم صحيحة.",
  "Export complete · {stations}": "اكتمل التصدير · {stations}",
  "→": "←",
};
