import { APP_INITIALIZER, CUSTOM_ELEMENTS_SCHEMA, NgModule, Provider } from '@angular/core';
import { CommonModule } from '@angular/common';
import { defineCustomElements } from '@awc-ui/core/loader';

import { DIRECTIVES } from './directives';
import { TextValueAccessor } from './directives/text-value-accessor';
import { SelectValueAccessor } from './directives/select-value-accessor';
import { BooleanValueAccessor } from './directives/boolean-value-accessor';
import { RadioValueAccessor } from './directives/radio-value-accessor';
import { NumericValueAccessor } from './directives/number-value-accessor';
import { SwitchValueAccessor } from './directives/switch-value-accessor';

/**
 * ControlValueAccessor directives, so `[(ngModel)]` and `formControlName` bind
 * to AWC UI inputs. Declared here rather than in `DIRECTIVES` because that
 * array is GENERATED by the Stencil output target on every build and would
 * discard anything added to it.
 */
export const VALUE_ACCESSORS = [
  TextValueAccessor,
  SelectValueAccessor,
  BooleanValueAccessor,
  RadioValueAccessor,
  NumericValueAccessor,
  SwitchValueAccessor,
];

/**
 * Registers the AWC UI custom elements (the Stencil lazy loader) during
 * application bootstrap. Add it to your root providers instead of calling
 * `defineCustomElements()` manually:
 *
 * @example
 * // NgModule app
 * @NgModule({
 *   imports: [AwcUiModule],
 *   providers: [provideAwcUi()],
 * })
 * export class AppModule {}
 *
 * // Standalone app
 * bootstrapApplication(AppComponent, {
 *   providers: [provideAwcUi(), importProvidersFrom(AwcUiModule)],
 * });
 *
 * SSR-safe: it is a no-op when `window` is not available.
 */
export function provideAwcUi(): Provider {
  return {
    provide: APP_INITIALIZER,
    multi: true,
    useValue: (): Promise<void> =>
      typeof window !== 'undefined' ? defineCustomElements(window) : Promise.resolve(),
  };
}

/**
 * AwcUiModule
 *
 * Import this module in your Angular application to use all AWC UI
 * component proxies (typed inputs, outputs and methods).
 *
 * The underlying custom elements must be registered once. Either add
 * `provideAwcUi()` to your root providers (recommended, see above), or
 * call `defineCustomElements()` from `@awc-ui/core/loader` in `main.ts`:
 *
 * @example
 * // main.ts
 * import { defineCustomElements } from '@awc-ui/core/loader';
 * defineCustomElements(window);
 *
 * // app.module.ts (or standalone component)
 * import { AwcUiModule } from '@awc-ui/angular';
 *
 * @NgModule({
 *   imports: [AwcUiModule, ...],
 * })
 * export class AppModule {}
 */
@NgModule({
  imports: [CommonModule],
  declarations: [...DIRECTIVES, ...VALUE_ACCESSORS],
  exports: [...DIRECTIVES, ...VALUE_ACCESSORS],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AwcUiModule {}
