import { APP_INITIALIZER, CUSTOM_ELEMENTS_SCHEMA, NgModule, Provider } from '@angular/core';
import { CommonModule } from '@angular/common';
import { defineCustomElements } from '@awc-ui/core/loader';

import { DIRECTIVES } from './directives';
import { TextValueAccessor } from './directives/text-value-accessor';
import { SelectValueAccessor } from './directives/select-value-accessor';
import { BooleanValueAccessor } from './directives/boolean-value-accessor';
import { RadioValueAccessor } from './directives/radio-value-accessor';
import { NumericValueAccessor } from './directives/number-value-accessor';
import { SwitchValueAccessor } from './directives/switch-value-accessor';

/**
 * ControlValueAccessor directives, so `[(ngModel)]` and `formControlName` bind
 * to AWC UI inputs. Declared here rather than in `DIRECTIVES` because that
 * array is GENERATED by the Stencil output target on every build and would
 * discard anything added to it.
 */
export const VALUE_ACCESSORS = [
  TextValueAccessor,
  SelectValueAccessor,
  BooleanValueAccessor,
  RadioValueAccessor,
  NumericValueAccessor,
  SwitchValueAccessor,
];

/**
 * Registers ALL AWC UI custom elements (the Stencil lazy loader) during
 * application bootstrap.
 *
 * Since the proxies became standalone (each one statically imports and
 * registers its own element), this provider is NO LONGER REQUIRED — importing
 * a proxy is enough. It is kept for backwards compatibility and for apps that
 * use raw `md-*` tags without importing the corresponding proxy. Element
 * definition is idempotent, so using both mechanisms together is harmless —
 * but adding this provider forces the whole lazy-loader registry into the
 * bundle, so prefer omitting it.
 *
 * @example
 * // NgModule app
 * @NgModule({
 *   imports: [AwcUiModule],
 *   providers: [provideAwcUi()],
 * })
 * export class AppModule {}
 *
 * // Standalone app
 * bootstrapApplication(AppComponent, {
 *   providers: [provideAwcUi(), importProvidersFrom(AwcUiModule)],
 * });
 *
 * SSR-safe: it is a no-op when `window` is not available.
 */
export function provideAwcUi(): Provider {
  return {
    provide: APP_INITIALIZER,
    multi: true,
    useValue: (): Promise<void> =>
      typeof window !== 'undefined' ? defineCustomElements(window) : Promise.resolve(),
  };
}

/**
 * AwcUiModule
 *
 * Convenience module exporting ALL AWC UI component proxies (typed inputs,
 * outputs and methods) plus the form value accessors.
 *
 * NOTE: the proxies are standalone components that register their own custom
 * element on import — no loader bootstrap needed. For the smallest bundles,
 * prefer importing individual components over this module: this module
 * references all 81 proxies, so the whole component set ships with your app.
 *
 * @example
 * // Smallest bundle — standalone component imports exactly what it uses:
 * import { MdButton } from '@awc-ui/angular';
 * @Component({ standalone: true, imports: [MdButton], ... })
 *
 * // Convenience — everything at once (ships all components):
 * import { AwcUiModule } from '@awc-ui/angular';
 * @NgModule({ imports: [AwcUiModule, ...] })
 * export class AppModule {}
 */
@NgModule({
  imports: [CommonModule, ...DIRECTIVES, ...VALUE_ACCESSORS],
  exports: [...DIRECTIVES, ...VALUE_ACCESSORS],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AwcUiModule {}
