/**
 * Hand-written ABI surface for the WASM option engine.
 *
 * `engine.wasm.ts` (the base64 blob) is generated by scripts/build-wasm.mjs;
 * this file is the stable, committed wrapper the rest of the codebase imports.
 * Keep `EngineExports` in sync with the exports of `engine.ts`.
 */
import { WASM_BASE64 } from './engine.wasm';

/** Filter modes accepted by `setQuery` (mirrors engine.ts). */
export const FILTER_SUBSTRING = 0;
export const FILTER_PREFIX = 1;
export const FILTER_FUZZY = 2;

/** The functions exported by the compiled WASM engine. */
export interface EngineExports {
  memory: WebAssembly.Memory;
  reserve(
    rows: number,
    valueBytesTotal: number,
    labelBytesTotal: number,
    iconBytesTotal: number,
    supportBytesTotal: number,
  ): void;
  valueWritePtr(): number;
  labelWritePtr(): number;
  iconWritePtr(): number;
  supportWritePtr(): number;
  appendRow(
    valueLen: number,
    labelLen: number,
    iconLen: number,
    supportLen: number,
    flags: number,
  ): number;
  finalizeLoad(): void;
  queryPtr(): number;
  queryCapacity(): number;
  setQuery(queryLen: number, mode: number): number;
  totalCount(): number;
  filteredCount(): number;
  rowAt(filteredIndex: number): number;
  valuePtr(absIndex: number): number;
  valueLen(absIndex: number): number;
  labelPtr(absIndex: number): number;
  labelLen(absIndex: number): number;
  iconPtr(absIndex: number): number;
  iconLen(absIndex: number): number;
  supportPtr(absIndex: number): number;
  supportLen(absIndex: number): number;
  rowFlags(absIndex: number): number;
  indexOfValue(queryLen: number): number;
  findLabelPrefix(queryLen: number, fromFilteredIndex: number): number;
  reset(): void;
}

function decodeBase64(b64: string): Uint8Array {
  if (typeof atob === 'function') {
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  // Node without a global atob (older runtimes / spec env).
  return Uint8Array.from(Buffer.from(b64, 'base64'));
}

/**
 * Lazily instantiate the engine. The compiled module is a few KB; consumers
 * load their (potentially millions of) rows into its memory at runtime.
 */
export async function instantiateEngine(): Promise<EngineExports> {
  const bytes = decodeBase64(WASM_BASE64);
  const imports = {
    env: {
      abort() {},
      trace() {},
      seed() {
        return Date.now();
      },
    },
  };
  // `bytes` is a BufferSource, so at runtime this is the `{ module, instance }`
  // overload. Some TS lib versions infer the `Module` overload instead
  // (`Promise<Instance>`, which has no `.instance`) for a generic `Uint8Array`,
  // so reach the instance through a structural cast that doesn't depend on the
  // overload TS picked.
  const source = (await WebAssembly.instantiate(bytes, imports)) as unknown as {
    instance: WebAssembly.Instance;
  };
  return source.instance.exports as unknown as EngineExports;
}
