/**
 * Hand-written ABI surface for the WASM option engine.
 *
 * `engine.wasm.ts` (the base64 blob) is generated by scripts/build-wasm.mjs;
 * this file is the stable, committed wrapper the rest of the codebase imports.
 * Keep `EngineExports` in sync with the exports of `engine.ts`.
 *
 * The blob is imported DYNAMICALLY inside instantiateEngine() rather than at
 * module top level: the engine only ever instantiates above the virtualization
 * threshold (200+ options), but a static import made every consumer of
 * md-select/md-autocomplete/md-multi-select/md-table-pagination ship the
 * ~11 kB base64 string (5.6 kB gz) eagerly. As a dynamic import the bundler
 * emits it as its own async chunk, fetched only if virtualization engages.
 */

/** Filter modes accepted by `setQuery` (mirrors engine.ts). */
export const FILTER_SUBSTRING = 0;
export const FILTER_PREFIX = 1;
export const FILTER_FUZZY = 2;

/** The functions exported by the compiled WASM engine. */
export interface EngineExports {
  memory: WebAssembly.Memory;
  reserve(
    rows: number,
    valueBytesTotal: number,
    labelBytesTotal: number,
    iconBytesTotal: number,
    supportBytesTotal: number,
  ): void;
  valueWritePtr(): number;
  labelWritePtr(): number;
  iconWritePtr(): number;
  supportWritePtr(): number;
  appendRow(
    valueLen: number,
    labelLen: number,
    iconLen: number,
    supportLen: number,
    flags: number,
  ): number;
  finalizeLoad(): void;
  queryPtr(): number;
  queryCapacity(): number;
  setQuery(queryLen: number, mode: number): number;
  totalCount(): number;
  filteredCount(): number;
  rowAt(filteredIndex: number): number;
  valuePtr(absIndex: number): number;
  valueLen(absIndex: number): number;
  labelPtr(absIndex: number): number;
  labelLen(absIndex: number): number;
  iconPtr(absIndex: number): number;
  iconLen(absIndex: number): number;
  supportPtr(absIndex: number): number;
  supportLen(absIndex: number): number;
  rowFlags(absIndex: number): number;
  indexOfValue(queryLen: number): number;
  findLabelPrefix(queryLen: number, fromFilteredIndex: number): number;
  reset(): void;
}

function decodeBase64(b64: string): Uint8Array {
  if (typeof atob === 'function') {
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  // Node without a global atob (older runtimes / spec env).
  return Uint8Array.from(Buffer.from(b64, 'base64'));
}

/**
 * Compiled once per process — the module bytes never change, and every
 * consumer gets its own isolated instance (fresh memory) below. Without this
 * cache each component instance re-decoded and recompiled the same module.
 */
let modulePromise: Promise<WebAssembly.Module> | undefined;

/**
 * Lazily instantiate the engine. The compiled module is a few KB; consumers
 * load their (potentially millions of) rows into its memory at runtime.
 */
export async function instantiateEngine(): Promise<EngineExports> {
  modulePromise ??= import('./engine.wasm').then(({ WASM_BASE64 }) =>
    WebAssembly.compile(decodeBase64(WASM_BASE64)),
  );
  const module = await modulePromise;
  const imports = {
    env: {
      abort() {},
      trace() {},
      seed() {
        return Date.now();
      },
    },
  };
  const instance = await WebAssembly.instantiate(module, imports);
  return instance.exports as unknown as EngineExports;
}
