import { useT as usePictorT } from '@/lib/showcase';
import { useState } from 'react';
import { ADJUSTMENT_ORDER, BLEND_ORDER, ancestorIds, ALIGN_ORDER, adjustmentKey, alignIcon, alignKey, blendKey, childrenOf, commonValue, isMixed, layerById, moveSubtree, clampRect, type Layer, type Rect } from '@awc-ui/showcase-kit/design';
import { useDocument } from '@/lib/document';
import { colorOf, componentMarkup, DEFAULT_SWATCHES } from '@/lib/editor-model';
import { PanelTabs, ColorControl, NumberControl, RangeControl, SelectControl, TextControl, ToggleControl } from './controls';
import { useT } from '@/lib/showcase';

export function Inspector() {
  const p = usePictorT();
  const doc = useDocument(); const t = useT();
  const [tab, setTab] = useState('design'); const [copied, setCopied] = useState(false);
  const selected = doc.layers.filter(layer => doc.selection.includes(layer.id));
  const first = selected[0];
  const pick = (fn: (layer: Layer) => unknown) => commonValue(doc.layers, doc.selection, fn);
  const geometry = (key: keyof Rect) => { const value = pick(layer => layer.rect[key]); return typeof value === 'number' ? value * 20 : null; };
  const setGeometry = (key: keyof Rect, pixels: number) => {
    const value = Math.round(pixels / 20);
    doc.commitLayers(key === 'x' || key === 'y' ? 'move' : 'resize', layers => {
      let next = layers;
      const ids = key === 'x' || key === 'y' ? doc.selection.filter(id => ![...ancestorIds(layers, id)].some(parent => doc.selection.includes(parent))) : doc.selection;
      for (const id of ids) {
        const layer = layerById(next, id); if (!layer) continue;
        if (key === 'x' || key === 'y') next = moveSubtree(next, id, key === 'x' ? value - layer.rect.x : 0, key === 'y' ? value - layer.rect.y : 0);
        else next = next.map(item => item.id === id ? { ...item, rect: clampRect({ ...item.rect, [key]: value }) } : item);
      }
      return next;
    });
  };
  const snippet = first ? first.componentId?.startsWith('awc:') ? componentMarkup(first) : `.design-element {\n  width: ${first.rect.w * 20}px;\n  height: ${first.rect.h * 20}px;\n  ${first.kind === 'text' ? 'color' : 'background'}: ${colorOf(first.fill)};\n  opacity: ${first.opacity / 100};\n  mix-blend-mode: ${first.blend};\n}` : '';
  const reorder = (where: 'front' | 'back') => { if (!first) return; doc.reorderTo(first.id, first.parentId, where === 'front' ? childrenOf(doc.layers, first.parentId).length - 1 : 0); };

  return <div className="inspector studio-inspector" data-inspector>
    <div className="studio-panel-head"><strong>{p("Inspector")}</strong><span>{selected.length ? p("{count} selected", { count: selected.length }) : p("Canvas")}</span></div>
    <PanelTabs value={tab} onValue={setTab} label={p("Inspector view")} options={[{ value: 'design', label: p("Design"), icon: 'tune' }, { value: 'code', label: p("Handoff"), icon: 'code' }]} />
    {!first ? <div className="studio-inspector-empty"><span className="material-symbols-outlined" aria-hidden="true">interests</span><h3>{p("Every detail is a possibility.")}</h3><p>{p("Select an object to adjust its geometry, color and appearance.")}</p><div className="studio-canvas-spec"><span>{p("Canvas size")}</span><strong>960 × 640</strong><span>{p("Color profile")}</span><strong>{p("sRGB")}</strong><span>{p("Editable layers")}</span><strong>{doc.layers.length}</strong><span>{p("Grid")}</span><strong>{p("20px snapping")}</strong></div><md-button variant="tonal" icon="add" onClick={() => window.dispatchEvent(new Event('pictor:insert'))}>{p("Insert something")}</md-button><p className="studio-tip">{p("Try R to draw a rectangle, T for text, or double-click a text layer to edit it.")}</p></div> : tab === 'code' ? <section className="inspector__section"><h3 className="inspector__title">{first.componentId?.startsWith('awc:') ? p("AWC component markup") : p("CSS properties")}</h3><p className="studio-tip">{first.componentId?.startsWith('awc:') ? p("This is a live component. Open Present mode to interact with it.") : p("Measured directly from your selected layer. Position it within your own layout.")}</p><pre className="studio-code"><code>{snippet}</code></pre><md-button variant="tonal" icon={copied ? 'check' : 'content_copy'} onClick={async () => { try { await navigator.clipboard.writeText(snippet); setCopied(true); setTimeout(() => setCopied(false), 2000); } catch { setCopied(false); } }}>{copied ? p("Copied") : p("Copy code")}</md-button><div className="studio-canvas-spec"><span>{p("Layer ID")}</span><code>{first.id}</code><span>{p("Type")}</span><strong>{t(first.kindKey)}</strong></div></section> : <>
      <section className="inspector__section"><TextControl label={first.kind === 'text' ? p("Text content") : p("Layer name")} value={selected.length === 1 ? first.textKey ? t(first.textKey) : first.name : ''} placeholder={selected.length > 1 ? p("Rename selected layers") : undefined} onValue={name => doc.restyle({ name, ...(first.kind === 'text' ? { textKey: null } : {}) })} data-name-field multiline={first.kind === 'text' ? 'auto-grow' : undefined} rows={first.kind === 'text' ? 3 : undefined} />{first.kind === 'text' ? <p className="studio-tip">{p("Text scales to fit its frame. Add a line break or resize for a new composition.")}</p> : null}</section>
      <section className="inspector__section"><h3 className="inspector__title">{p("Position & size")} <span>{p("PX")}</span></h3><div className="inspector__grid">{(['x','y','w','h'] as const).map(key => <NumberControl key={key} label={key.toUpperCase()} value={geometry(key)} onValue={value => setGeometry(key, value)} min={key === 'w' || key === 'h' ? 20 : 0} max={key === 'x' || key === 'w' ? 960 : 640} step={20} data-geometry={key} data-field={`design.label.${key}`} />)}</div><p className="studio-tip">{p("Snaps to 20px. Drag canvas corner handles to resize.")}</p></section>
      <section className="inspector__section"><h3 className="inspector__title">{p("Fill & appearance")}</h3><div className="studio-color-row"><ColorControl value={colorOf(first.fill, '#203D35')} onValue={fill => doc.restyle({ fill })} /><TextControl label={p("Color")} value={colorOf(first.fill, '#203D35')} onValue={fill => { if (/^#(?:[0-9a-f]{3}|[0-9a-f]{4}|[0-9a-f]{6}|[0-9a-f]{8})$/i.test(fill)) doc.restyle({ fill }); }} /></div><div className="studio-swatches" role="group" aria-label={p("Brand colors")}>{DEFAULT_SWATCHES.slice(0, 12).map(fill => <button key={fill} title={fill} aria-label={p("Set fill to {fill}", { fill: fill })} aria-pressed={colorOf(first.fill) === fill} onClick={() => doc.restyle({ fill })}><svg viewBox="0 0 24 24" aria-hidden="true"><rect width="24" height="24" rx="7" fill={fill} /></svg></button>)}</div><RangeControl label={p("Opacity")} value={typeof pick(l => l.opacity) === 'number' ? Number(pick(l => l.opacity)) : 100} onValue={opacity => doc.restyle({ opacity })} /><SelectControl value={isMixed(pick(l => l.blend) as never) ? '' : first.blend} label={p("Blend mode")} onValue={blend => doc.restyle({ blend: blend as Layer['blend'], blendKey: blendKey(blend as Layer['blend']) })} options={BLEND_ORDER.map(mode => ({ value: mode, label: t(blendKey(mode)) }))} data-blend-select /></section>
      <section className="inspector__section"><h3 className="inspector__title">{p("Arrange")}</h3><div className="studio-arrange" role="group" aria-label={p("Align selected layers")}>{ALIGN_ORDER.map(axis => <md-icon-button key={axis} icon={alignIcon(axis)} aria-label={t(alignKey(axis))} disabled={selected.length < 2 || undefined} data-align={axis} onClick={() => doc.align(axis)} />)}</div><div className="studio-arrange"><md-icon-button icon="horizontal_distribute" aria-label={p("Distribute horizontally")} disabled={selected.length < 3 || undefined} onClick={() => doc.distribute('horizontal')} /><md-icon-button icon="vertical_distribute" aria-label={p("Distribute vertically")} disabled={selected.length < 3 || undefined} onClick={() => doc.distribute('vertical')} /><md-icon-button icon="flip_to_front" aria-label={p("Bring to front")} onClick={() => reorder('front')} /><md-icon-button icon="flip_to_back" aria-label={p("Send to back")} onClick={() => reorder('back')} /><md-icon-button icon="folder" aria-label={p("Group layers")} disabled={selected.length < 2 || undefined} onClick={() => doc.group()} /><md-icon-button icon="folder_off" aria-label={p("Ungroup")} disabled={!selected.some(l => l.kind === 'group' || l.kind === 'frame') || undefined} onClick={() => doc.ungroup()} /></div></section>
      {selected.some(layer => layer.kind === 'image') ? <section className="inspector__section"><h3 className="inspector__title">{p("Image adjustments")}</h3>{ADJUSTMENT_ORDER.map(kind => <RangeControl key={kind} label={t(adjustmentKey(kind))} min={-100} max={100} step={20} value={first.adjustments.find(a => a.kind === kind)?.value ?? 0} onValue={value => doc.setAdjustment(kind, value)} />)}<ToggleControl label={p("Rounded image mask")} selected={first.masked} onValue={masked => doc.restyle({ masked })} /></section> : null}
      <section className="inspector__section"><md-button variant="tonal" icon="content_copy" onClick={() => doc.duplicate()}>{p("Duplicate selection")}</md-button><md-button variant="text" icon="delete" onClick={() => doc.remove()}>{p("Delete selection")}</md-button></section>
    </>}
  </div>;
}
