import { useT as usePictorT } from '@/lib/showcase';
import { ancestorIds, canReparent, childrenOf, isContainer, layerById, layerIcon, lockedLayers, visibleLayers } from '@awc-ui/showcase-kit/design';
import { useMemo, useRef, useState, type DragEvent } from 'react';
import { useDocument, useTreeRows } from '@/lib/document';
import { TextControl } from './controls';

type DropSide = 'before' | 'after' | 'inside';
export function LayerTree() {
  const p = usePictorT();
  const doc = useDocument();
  const rows = useTreeRows();
  const visible = useMemo(() => visibleLayers(doc.layers), [doc.layers]);
  const locked = useMemo(() => lockedLayers(doc.layers), [doc.layers]);
  const [query, setQuery] = useState('');
  const [collapsed, setCollapsed] = useState<string[]>([]);
  const [dragId, setDragId] = useState<string | null>(null);
  const [dropOn, setDropOn] = useState<{ id: string; side: DropSide } | null>(null);
  const tree = useRef<HTMLDivElement>(null);
  const shown = rows.filter(({ layer }) => query ? layer.name.toLowerCase().includes(query.toLowerCase()) : ![...ancestorIds(doc.layers, layer.id)].some(id => collapsed.includes(id)));
  const toggle = (id: string) => setCollapsed(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]);
  const over = (event: DragEvent<HTMLElement>, id: string) => { if (!dragId || dragId === id) return; event.preventDefault(); const box = event.currentTarget.getBoundingClientRect(); const offset = (event.clientY - box.top) / box.height; const layer = layerById(doc.layers, id); setDropOn({ id, side: layer && isContainer(layer) && offset > .25 && offset < .75 ? 'inside' : offset < .5 ? 'before' : 'after' }); };
  const drop = (event: DragEvent) => { event.preventDefault(); if (dragId && dropOn) { const target = layerById(doc.layers, dropOn.id); if (target) { const parentId = dropOn.side === 'inside' ? target.id : target.parentId; const siblings = childrenOf(doc.layers, parentId).filter(layer => layer.id !== dragId); const at = dropOn.side === 'inside' ? siblings.length : siblings.findIndex(layer => layer.id === target.id) + (dropOn.side === 'after' ? 1 : 0); if (canReparent(doc.layers, dragId, parentId)) doc.reorderTo(dragId, parentId, Math.max(0, at)); } } setDragId(null); setDropOn(null); };
  return <div className="studio-layers"><div className="studio-panel-heading"><div><h3>{p("Layers")} <span>{doc.layers.length}</span></h3><p>{p("Your composition, piece by piece.")}</p></div><md-icon-button icon="add" aria-label={p("Insert a layer")} onClick={() => window.dispatchEvent(new Event('pictor:insert'))} /></div><TextControl live label={p("Find a layer")} value={query} onValue={setQuery} /><div ref={tree} className="tree" role="tree" aria-label={p("Canvas layers")} data-layer-tree>{shown.map(({ layer, level }, index) => <div key={layer.id} className="tree__row" role="treeitem" aria-level={level + 1} aria-expanded={isContainer(layer) ? !collapsed.includes(layer.id) : undefined} aria-selected={doc.selection.includes(layer.id)} tabIndex={0} data-layer={layer.id} data-level={level} data-selected={doc.selection.includes(layer.id) ? '' : undefined} data-tone={!visible.has(layer.id) ? 'hidden' : locked.has(layer.id) ? 'locked' : undefined} data-drop={dropOn?.id === layer.id ? dropOn.side : undefined} draggable={!locked.has(layer.id)} onDragStart={event => { setDragId(layer.id); event.dataTransfer.setData('text/plain', layer.id); event.dataTransfer.effectAllowed = 'move'; }} onDragOver={event => over(event, layer.id)} onDrop={drop} onDragEnd={() => { setDragId(null); setDropOn(null); }} onClick={event => { if (!locked.has(layer.id)) event.shiftKey || event.metaKey || event.ctrlKey ? doc.toggleInSelection(layer.id) : doc.select([layer.id]); }} onKeyDown={event => { if (event.target !== event.currentTarget) return; if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); if (!locked.has(layer.id)) doc.select([layer.id]); } if (event.key === 'ArrowDown' || event.key === 'ArrowUp') { event.preventDefault(); event.stopPropagation(); const next = Math.max(0, Math.min(shown.length - 1, index + (event.key === 'ArrowDown' ? 1 : -1))); tree.current?.querySelectorAll<HTMLElement>('[role="treeitem"]')[next]?.focus(); } if ((event.key === 'ArrowLeft' || event.key === 'ArrowRight') && isContainer(layer)) { event.preventDefault(); event.stopPropagation(); setCollapsed(current => event.key === 'ArrowLeft' ? [...new Set([...current, layer.id])] : current.filter(id => id !== layer.id)); } }}>
    {isContainer(layer) ? <button className="tree__expand" aria-label={`${collapsed.includes(layer.id) ? p("Expand") : p("Collapse")} ${layer.name}`} onClick={event => { event.stopPropagation(); toggle(layer.id); }}><span className="material-symbols-outlined" aria-hidden="true">{collapsed.includes(layer.id) ? 'chevron_right' : 'expand_more'}</span></button> : <span className="tree__expand-spacer" />}<span className="material-symbols-outlined tree__icon" aria-hidden="true">{layerIcon(layer.kind)}</span><span className="tree__name" title={layer.name}>{layer.name}</span><md-icon-button class="tree__toggle" size="x-small" icon={layer.visible ? 'visibility' : 'visibility_off'} aria-label={`${layer.visible ? p("Hide") : p("Show")} ${layer.name}`} data-visibility={layer.id} onClick={(event: React.MouseEvent) => { event.stopPropagation(); doc.toggleVisible(layer.id); }} /><md-icon-button class="tree__toggle" size="x-small" icon={layer.locked ? 'lock' : 'lock_open'} aria-label={`${layer.locked ? p("Unlock") : p("Lock")} ${layer.name}`} data-lock={layer.id} onClick={(event: React.MouseEvent) => { event.stopPropagation(); doc.toggleLocked(layer.id); }} />
  </div>)}</div>{shown.length === 0 ? <p className="studio-description">{p("No matching layers. Try another name.")}</p> : null}<p className="studio-panel-footnote">{p("Shift-click to select more. Drag rows to reorder or nest.")}</p></div>;
}
