'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdAccordionItemCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdAccordionItem as MdAccordionItemElement, defineCustomElement as defineMdAccordionItem } from "@awc-ui/core/dist/components/md-accordion-item.js";

export type MdAccordionItemEvents = {
    onMdItemToggle: EventName<MdAccordionItemCustomEvent<{ expanded: boolean; index: number }>>,
    onMdItemRequestFocus: EventName<MdAccordionItemCustomEvent<{ direction: 'next' | 'prev' | 'first' | 'last'; from: number; }>>,
    onMdItemRequestReorder: EventName<MdAccordionItemCustomEvent<{ direction: 'up' | 'down'; from: number; }>>
};

export const MdAccordionItem: StencilReactComponent<MdAccordionItemElement, MdAccordionItemEvents, Components.MdAccordionItem> = /*@__PURE__*/ createComponent<MdAccordionItemElement, MdAccordionItemEvents, Components.MdAccordionItem>({
    tagName: 'md-accordion-item',
    elementClass: MdAccordionItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdItemToggle: 'mdItemToggle',
        onMdItemRequestFocus: 'mdItemRequestFocus',
        onMdItemRequestReorder: 'mdItemRequestReorder'
    } as MdAccordionItemEvents,
    defineCustomElement: defineMdAccordionItem
});
