'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdAccordionCustomEvent, MdAccordionDragDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdAccordion as MdAccordionElement, defineCustomElement as defineMdAccordion } from "@awc-ui/core/dist/components/md-accordion.js";

export type MdAccordionEvents = {
    onMdToggle: EventName<MdAccordionCustomEvent<{ index: number; expanded: boolean; expandedIndices: number[]; }>>,
    onMdReorder: EventName<MdAccordionCustomEvent<{ from: number; to: number; order: number[]; }>>,
    onMdDragStart: EventName<MdAccordionCustomEvent<MdAccordionDragDetail>>,
    onMdDragMove: EventName<MdAccordionCustomEvent<MdAccordionDragDetail>>,
    onMdDragEnd: EventName<MdAccordionCustomEvent<MdAccordionDragDetail>>
};

export const MdAccordion: StencilReactComponent<MdAccordionElement, MdAccordionEvents, Components.MdAccordion> = /*@__PURE__*/ createComponent<MdAccordionElement, MdAccordionEvents, Components.MdAccordion>({
    tagName: 'md-accordion',
    elementClass: MdAccordionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdToggle: 'mdToggle',
        onMdReorder: 'mdReorder',
        onMdDragStart: 'mdDragStart',
        onMdDragMove: 'mdDragMove',
        onMdDragEnd: 'mdDragEnd'
    } as MdAccordionEvents,
    defineCustomElement: defineMdAccordion
});
