'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdAppBarCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdAppBar as MdAppBarElement, defineCustomElement as defineMdAppBar } from "@awc-ui/core/dist/components/md-app-bar.js";

export type MdAppBarEvents = {
    onMdLeadingClick: EventName<MdAppBarCustomEvent<MouseEvent>>,
    onMdSearchActivate: EventName<MdAppBarCustomEvent<{ value: string }>>,
    onMdSearchInput: EventName<MdAppBarCustomEvent<{ value: string }>>
};

export const MdAppBar: StencilReactComponent<MdAppBarElement, MdAppBarEvents, Components.MdAppBar> = /*@__PURE__*/ createComponent<MdAppBarElement, MdAppBarEvents, Components.MdAppBar>({
    tagName: 'md-app-bar',
    elementClass: MdAppBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdLeadingClick: 'mdLeadingClick',
        onMdSearchActivate: 'mdSearchActivate',
        onMdSearchInput: 'mdSearchInput'
    } as MdAppBarEvents,
    defineCustomElement: defineMdAppBar
});
