'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdAreaChartCustomEvent, MdChartAxisClickDetail, MdChartClickDetail, MdChartHoverDetail, MdChartSeries } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdAreaChart as MdAreaChartElement, defineCustomElement as defineMdAreaChart } from "@awc-ui/core/dist/components/md-area-chart.js";

export type MdAreaChartEvents = {
    onMdMarkerClick: EventName<MdAreaChartCustomEvent<MdChartClickDetail<MdChartSeries>>>,
    onMdLineClick: EventName<MdAreaChartCustomEvent<MdChartClickDetail<MdChartSeries>>>,
    onMdAreaClick: EventName<MdAreaChartCustomEvent<MdChartClickDetail<MdChartSeries>>>,
    onMdAxisClick: EventName<MdAreaChartCustomEvent<MdChartAxisClickDetail>>,
    onMdLegendClick: EventName<MdAreaChartCustomEvent<{ seriesIndex: number; seriesId?: string; selected: boolean }>>,
    onMdHover: EventName<MdAreaChartCustomEvent<MdChartHoverDetail>>,
    onMdReady: EventName<MdAreaChartCustomEvent<void>>,
    onMdZoom: EventName<MdAreaChartCustomEvent<{ startIndex: number; endIndex: number; reset: boolean }>>
};

export const MdAreaChart: StencilReactComponent<MdAreaChartElement, MdAreaChartEvents, Components.MdAreaChart> = /*@__PURE__*/ createComponent<MdAreaChartElement, MdAreaChartEvents, Components.MdAreaChart>({
    tagName: 'md-area-chart',
    elementClass: MdAreaChartElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdMarkerClick: 'mdMarkerClick',
        onMdLineClick: 'mdLineClick',
        onMdAreaClick: 'mdAreaClick',
        onMdAxisClick: 'mdAxisClick',
        onMdLegendClick: 'mdLegendClick',
        onMdHover: 'mdHover',
        onMdReady: 'mdReady',
        onMdZoom: 'mdZoom'
    } as MdAreaChartEvents,
    defineCustomElement: defineMdAreaChart
});
