'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdAutocompleteCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdAutocomplete as MdAutocompleteElement, defineCustomElement as defineMdAutocomplete } from "@awc-ui/core/dist/components/md-autocomplete.js";

export type MdAutocompleteEvents = {
    onMdChange: EventName<MdAutocompleteCustomEvent<string | string[]>>,
    onMdInput: EventName<MdAutocompleteCustomEvent<string>>,
    onMdOpen: EventName<MdAutocompleteCustomEvent<void>>,
    onMdClose: EventName<MdAutocompleteCustomEvent<void>>,
    onMdClear: EventName<MdAutocompleteCustomEvent<void>>,
    onMdValidityChange: EventName<MdAutocompleteCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdAutocomplete: StencilReactComponent<MdAutocompleteElement, MdAutocompleteEvents, Components.MdAutocomplete> = /*@__PURE__*/ createComponent<MdAutocompleteElement, MdAutocompleteEvents, Components.MdAutocomplete>({
    tagName: 'md-autocomplete',
    elementClass: MdAutocompleteElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdChange: 'mdChange',
        onMdInput: 'mdInput',
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdClear: 'mdClear',
        onMdValidityChange: 'mdValidityChange'
    } as MdAutocompleteEvents,
    defineCustomElement: defineMdAutocomplete
});
