'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdAvatarCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdAvatar as MdAvatarElement, defineCustomElement as defineMdAvatar } from "@awc-ui/core/dist/components/md-avatar.js";

export type MdAvatarEvents = {
    onMdLoad: EventName<MdAvatarCustomEvent<{ src: string }>>,
    onMdError: EventName<MdAvatarCustomEvent<{ src: string }>>
};

export const MdAvatar: StencilReactComponent<MdAvatarElement, MdAvatarEvents, Components.MdAvatar> = /*@__PURE__*/ createComponent<MdAvatarElement, MdAvatarEvents, Components.MdAvatar>({
    tagName: 'md-avatar',
    elementClass: MdAvatarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdLoad: 'mdLoad',
        onMdError: 'mdError'
    } as MdAvatarEvents,
    defineCustomElement: defineMdAvatar
});
