'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdBarChartCustomEvent, MdChartClickDetail, MdChartHoverDetail, MdChartSeries } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdBarChart as MdBarChartElement, defineCustomElement as defineMdBarChart } from "@awc-ui/core/dist/components/md-bar-chart.js";

export type MdBarChartEvents = {
    onMdBarClick: EventName<MdBarChartCustomEvent<MdChartClickDetail<MdChartSeries>>>,
    onMdLegendClick: EventName<MdBarChartCustomEvent<{ seriesIndex: number; seriesId?: string; selected: boolean }>>,
    onMdHover: EventName<MdBarChartCustomEvent<MdChartHoverDetail>>,
    onMdReady: EventName<MdBarChartCustomEvent<void>>,
    onMdZoom: EventName<MdBarChartCustomEvent<{ startIndex: number; endIndex: number; reset: boolean }>>
};

export const MdBarChart: StencilReactComponent<MdBarChartElement, MdBarChartEvents, Components.MdBarChart> = /*@__PURE__*/ createComponent<MdBarChartElement, MdBarChartEvents, Components.MdBarChart>({
    tagName: 'md-bar-chart',
    elementClass: MdBarChartElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdBarClick: 'mdBarClick',
        onMdLegendClick: 'mdLegendClick',
        onMdHover: 'mdHover',
        onMdReady: 'mdReady',
        onMdZoom: 'mdZoom'
    } as MdBarChartEvents,
    defineCustomElement: defineMdBarChart
});
