'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdBadge as MdBadgeElement, defineCustomElement as defineMdBadge } from "@awc-ui/core/dist/components/md-badge.js";

export type MdBadgeEvents = NonNullable<unknown>;

export const MdBadge: StencilReactComponent<MdBadgeElement, MdBadgeEvents, Components.MdBadge> = /*@__PURE__*/ createComponent<MdBadgeElement, MdBadgeEvents, Components.MdBadge>({
    tagName: 'md-badge',
    elementClass: MdBadgeElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdBadgeEvents,
    defineCustomElement: defineMdBadge
});
