'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdBottomSheetCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdBottomSheet as MdBottomSheetElement, defineCustomElement as defineMdBottomSheet } from "@awc-ui/core/dist/components/md-bottom-sheet.js";

export type MdBottomSheetEvents = {
    onMdOpen: EventName<MdBottomSheetCustomEvent<void>>,
    onMdClose: EventName<MdBottomSheetCustomEvent<void>>,
    onMdCancel: EventName<MdBottomSheetCustomEvent<void>>
};

export const MdBottomSheet: StencilReactComponent<MdBottomSheetElement, MdBottomSheetEvents, Components.MdBottomSheet> = /*@__PURE__*/ createComponent<MdBottomSheetElement, MdBottomSheetEvents, Components.MdBottomSheet>({
    tagName: 'md-bottom-sheet',
    elementClass: MdBottomSheetElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdCancel: 'mdCancel'
    } as MdBottomSheetEvents,
    defineCustomElement: defineMdBottomSheet
});
