'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdBreadcrumbsCustomEvent, MdBreadcrumbsExpandDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdBreadcrumbs as MdBreadcrumbsElement, defineCustomElement as defineMdBreadcrumbs } from "@awc-ui/core/dist/components/md-breadcrumbs.js";

export type MdBreadcrumbsEvents = { onMdExpand: EventName<MdBreadcrumbsCustomEvent<MdBreadcrumbsExpandDetail>> };

export const MdBreadcrumbs: StencilReactComponent<MdBreadcrumbsElement, MdBreadcrumbsEvents, Components.MdBreadcrumbs> = /*@__PURE__*/ createComponent<MdBreadcrumbsElement, MdBreadcrumbsEvents, Components.MdBreadcrumbs>({
    tagName: 'md-breadcrumbs',
    elementClass: MdBreadcrumbsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdExpand: 'mdExpand' } as MdBreadcrumbsEvents,
    defineCustomElement: defineMdBreadcrumbs
});
