'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdBreadcrumbItemCustomEvent, MdBreadcrumbSelectDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdBreadcrumbItem as MdBreadcrumbItemElement, defineCustomElement as defineMdBreadcrumbItem } from "@awc-ui/core/dist/components/md-breadcrumb-item.js";

export type MdBreadcrumbItemEvents = { onMdSelect: EventName<MdBreadcrumbItemCustomEvent<MdBreadcrumbSelectDetail>> };

export const MdBreadcrumbItem: StencilReactComponent<MdBreadcrumbItemElement, MdBreadcrumbItemEvents, Components.MdBreadcrumbItem> = /*@__PURE__*/ createComponent<MdBreadcrumbItemElement, MdBreadcrumbItemEvents, Components.MdBreadcrumbItem>({
    tagName: 'md-breadcrumb-item',
    elementClass: MdBreadcrumbItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdSelect: 'mdSelect' } as MdBreadcrumbItemEvents,
    defineCustomElement: defineMdBreadcrumbItem
});
