'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdButtonGroupChangeDetail, MdButtonGroupCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdButtonGroup as MdButtonGroupElement, defineCustomElement as defineMdButtonGroup } from "@awc-ui/core/dist/components/md-button-group.js";

export type MdButtonGroupEvents = { onMdSelectionChange: EventName<MdButtonGroupCustomEvent<MdButtonGroupChangeDetail>> };

export const MdButtonGroup: StencilReactComponent<MdButtonGroupElement, MdButtonGroupEvents, Components.MdButtonGroup> = /*@__PURE__*/ createComponent<MdButtonGroupElement, MdButtonGroupEvents, Components.MdButtonGroup>({
    tagName: 'md-button-group',
    elementClass: MdButtonGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdSelectionChange: 'mdSelectionChange' } as MdButtonGroupEvents,
    defineCustomElement: defineMdButtonGroup
});
