'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdButtonChangeDetail, MdButtonClickDetail, MdButtonCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdButton as MdButtonElement, defineCustomElement as defineMdButton } from "@awc-ui/core/dist/components/md-button.js";

export type MdButtonEvents = {
    onMdClick: EventName<MdButtonCustomEvent<MdButtonClickDetail>>,
    onMdChange: EventName<MdButtonCustomEvent<MdButtonChangeDetail>>
};

export const MdButton: StencilReactComponent<MdButtonElement, MdButtonEvents, Components.MdButton> = /*@__PURE__*/ createComponent<MdButtonElement, MdButtonEvents, Components.MdButton>({
    tagName: 'md-button',
    elementClass: MdButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdClick: 'mdClick',
        onMdChange: 'mdChange'
    } as MdButtonEvents,
    defineCustomElement: defineMdButton
});
