'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdCardCustomEvent, MdCardDragDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdCard as MdCardElement, defineCustomElement as defineMdCard } from "@awc-ui/core/dist/components/md-card.js";

export type MdCardEvents = {
    onMdClick: EventName<MdCardCustomEvent<MouseEvent>>,
    onMdDragStart: EventName<MdCardCustomEvent<MdCardDragDetail>>,
    onMdDragMove: EventName<MdCardCustomEvent<MdCardDragDetail>>,
    onMdDragEnd: EventName<MdCardCustomEvent<MdCardDragDetail>>
};

export const MdCard: StencilReactComponent<MdCardElement, MdCardEvents, Components.MdCard> = /*@__PURE__*/ createComponent<MdCardElement, MdCardEvents, Components.MdCard>({
    tagName: 'md-card',
    elementClass: MdCardElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdClick: 'mdClick',
        onMdDragStart: 'mdDragStart',
        onMdDragMove: 'mdDragMove',
        onMdDragEnd: 'mdDragEnd'
    } as MdCardEvents,
    defineCustomElement: defineMdCard
});
