'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdCheckboxCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdCheckbox as MdCheckboxElement, defineCustomElement as defineMdCheckbox } from "@awc-ui/core/dist/components/md-checkbox.js";

export type MdCheckboxEvents = {
    onMdChange: EventName<MdCheckboxCustomEvent<{ checked: boolean; indeterminate: boolean }>>,
    onMdValidityChange: EventName<MdCheckboxCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdCheckbox: StencilReactComponent<MdCheckboxElement, MdCheckboxEvents, Components.MdCheckbox> = /*@__PURE__*/ createComponent<MdCheckboxElement, MdCheckboxEvents, Components.MdCheckbox>({
    tagName: 'md-checkbox',
    elementClass: MdCheckboxElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdChange: 'mdChange',
        onMdValidityChange: 'mdValidityChange'
    } as MdCheckboxEvents,
    defineCustomElement: defineMdCheckbox
});
