'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdChipCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdChip as MdChipElement, defineCustomElement as defineMdChip } from "@awc-ui/core/dist/components/md-chip.js";

export type MdChipEvents = {
    onMdClick: EventName<MdChipCustomEvent<void>>,
    onMdSelect: EventName<MdChipCustomEvent<{ selected: boolean }>>,
    onMdRemove: EventName<MdChipCustomEvent<void>>
};

export const MdChip: StencilReactComponent<MdChipElement, MdChipEvents, Components.MdChip> = /*@__PURE__*/ createComponent<MdChipElement, MdChipEvents, Components.MdChip>({
    tagName: 'md-chip',
    elementClass: MdChipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdClick: 'mdClick',
        onMdSelect: 'mdSelect',
        onMdRemove: 'mdRemove'
    } as MdChipEvents,
    defineCustomElement: defineMdChip
});
