'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdColorPickerCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdColorPicker as MdColorPickerElement, defineCustomElement as defineMdColorPicker } from "@awc-ui/core/dist/components/md-color-picker.js";

export type MdColorPickerEvents = {
    onMdInput: EventName<MdColorPickerCustomEvent<{ value: string }>>,
    onMdChange: EventName<MdColorPickerCustomEvent<{ value: string }>>,
    onMdOpenChange: EventName<MdColorPickerCustomEvent<{ open: boolean }>>
};

export const MdColorPicker: StencilReactComponent<MdColorPickerElement, MdColorPickerEvents, Components.MdColorPicker> = /*@__PURE__*/ createComponent<MdColorPickerElement, MdColorPickerEvents, Components.MdColorPicker>({
    tagName: 'md-color-picker',
    elementClass: MdColorPickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdInput: 'mdInput',
        onMdChange: 'mdChange',
        onMdOpenChange: 'mdOpenChange'
    } as MdColorPickerEvents,
    defineCustomElement: defineMdColorPicker
});
