'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdDatePickerChangeDetail, MdDatePickerCustomEvent, MdDatePickerMenuOpenDetail, MdDatePickerMenuSelectDetail, MdDatePickerModeChangeDetail, MdDatePickerSelectedDetail, MdDatePickerViewChangeDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdDatePicker as MdDatePickerElement, defineCustomElement as defineMdDatePicker } from "@awc-ui/core/dist/components/md-date-picker.js";

export type MdDatePickerEvents = {
    onMdChange: EventName<MdDatePickerCustomEvent<MdDatePickerChangeDetail>>,
    onMdSelected: EventName<MdDatePickerCustomEvent<MdDatePickerSelectedDetail>>,
    onMdInput: EventName<MdDatePickerCustomEvent<{ value: string }>>,
    onMdOpen: EventName<MdDatePickerCustomEvent<void>>,
    onMdClose: EventName<MdDatePickerCustomEvent<void>>,
    onMdCancel: EventName<MdDatePickerCustomEvent<void>>,
    onMdViewChange: EventName<MdDatePickerCustomEvent<MdDatePickerViewChangeDetail>>,
    onMdMenuOpen: EventName<MdDatePickerCustomEvent<MdDatePickerMenuOpenDetail>>,
    onMdMenuSelect: EventName<MdDatePickerCustomEvent<MdDatePickerMenuSelectDetail>>,
    onMdModeChange: EventName<MdDatePickerCustomEvent<MdDatePickerModeChangeDetail>>,
    onMdValidityChange: EventName<MdDatePickerCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdDatePicker: StencilReactComponent<MdDatePickerElement, MdDatePickerEvents, Components.MdDatePicker> = /*@__PURE__*/ createComponent<MdDatePickerElement, MdDatePickerEvents, Components.MdDatePicker>({
    tagName: 'md-date-picker',
    elementClass: MdDatePickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdChange: 'mdChange',
        onMdSelected: 'mdSelected',
        onMdInput: 'mdInput',
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdCancel: 'mdCancel',
        onMdViewChange: 'mdViewChange',
        onMdMenuOpen: 'mdMenuOpen',
        onMdMenuSelect: 'mdMenuSelect',
        onMdModeChange: 'mdModeChange',
        onMdValidityChange: 'mdValidityChange'
    } as MdDatePickerEvents,
    defineCustomElement: defineMdDatePicker
});
