'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdDivider as MdDividerElement, defineCustomElement as defineMdDivider } from "@awc-ui/core/dist/components/md-divider.js";

export type MdDividerEvents = NonNullable<unknown>;

export const MdDivider: StencilReactComponent<MdDividerElement, MdDividerEvents, Components.MdDivider> = /*@__PURE__*/ createComponent<MdDividerElement, MdDividerEvents, Components.MdDivider>({
    tagName: 'md-divider',
    elementClass: MdDividerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdDividerEvents,
    defineCustomElement: defineMdDivider
});
