'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdDialogCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdDialog as MdDialogElement, defineCustomElement as defineMdDialog } from "@awc-ui/core/dist/components/md-dialog.js";

export type MdDialogEvents = {
    onMdOpen: EventName<MdDialogCustomEvent<void>>,
    onMdClose: EventName<MdDialogCustomEvent<void>>,
    onMdCancel: EventName<MdDialogCustomEvent<void>>
};

export const MdDialog: StencilReactComponent<MdDialogElement, MdDialogEvents, Components.MdDialog> = /*@__PURE__*/ createComponent<MdDialogElement, MdDialogEvents, Components.MdDialog>({
    tagName: 'md-dialog',
    elementClass: MdDialogElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdCancel: 'mdCancel'
    } as MdDialogEvents,
    defineCustomElement: defineMdDialog
});
