'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdFabCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdFab as MdFabElement, defineCustomElement as defineMdFab } from "@awc-ui/core/dist/components/md-fab.js";

export type MdFabEvents = { onMdClick: EventName<MdFabCustomEvent<MouseEvent>> };

export const MdFab: StencilReactComponent<MdFabElement, MdFabEvents, Components.MdFab> = /*@__PURE__*/ createComponent<MdFabElement, MdFabEvents, Components.MdFab>({
    tagName: 'md-fab',
    elementClass: MdFabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdClick: 'mdClick' } as MdFabEvents,
    defineCustomElement: defineMdFab
});
