'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdFabMenuItemCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdFabMenuItem as MdFabMenuItemElement, defineCustomElement as defineMdFabMenuItem } from "@awc-ui/core/dist/components/md-fab-menu-item.js";

export type MdFabMenuItemEvents = { onMdClick: EventName<MdFabMenuItemCustomEvent<void>> };

export const MdFabMenuItem: StencilReactComponent<MdFabMenuItemElement, MdFabMenuItemEvents, Components.MdFabMenuItem> = /*@__PURE__*/ createComponent<MdFabMenuItemElement, MdFabMenuItemEvents, Components.MdFabMenuItem>({
    tagName: 'md-fab-menu-item',
    elementClass: MdFabMenuItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdClick: 'mdClick' } as MdFabMenuItemEvents,
    defineCustomElement: defineMdFabMenuItem
});
