'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdFabMenuCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdFabMenu as MdFabMenuElement, defineCustomElement as defineMdFabMenu } from "@awc-ui/core/dist/components/md-fab-menu.js";

export type MdFabMenuEvents = {
    onMdOpen: EventName<MdFabMenuCustomEvent<void>>,
    onMdClose: EventName<MdFabMenuCustomEvent<void>>
};

export const MdFabMenu: StencilReactComponent<MdFabMenuElement, MdFabMenuEvents, Components.MdFabMenu> = /*@__PURE__*/ createComponent<MdFabMenuElement, MdFabMenuEvents, Components.MdFabMenu>({
    tagName: 'md-fab-menu',
    elementClass: MdFabMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose'
    } as MdFabMenuEvents,
    defineCustomElement: defineMdFabMenu
});
