'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdIconButtonCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdIconButton as MdIconButtonElement, defineCustomElement as defineMdIconButton } from "@awc-ui/core/dist/components/md-icon-button.js";

export type MdIconButtonEvents = { onMdClick: EventName<MdIconButtonCustomEvent<{ selected: boolean }>> };

export const MdIconButton: StencilReactComponent<MdIconButtonElement, MdIconButtonEvents, Components.MdIconButton> = /*@__PURE__*/ createComponent<MdIconButtonElement, MdIconButtonEvents, Components.MdIconButton>({
    tagName: 'md-icon-button',
    elementClass: MdIconButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdClick: 'mdClick' } as MdIconButtonEvents,
    defineCustomElement: defineMdIconButton
});
