'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdListCustomEvent, MdListSelectDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdList as MdListElement, defineCustomElement as defineMdList } from "@awc-ui/core/dist/components/md-list.js";

export type MdListEvents = {
    onMdSelect: EventName<MdListCustomEvent<MdListSelectDetail>>,
    onMdActivate: EventName<MdListCustomEvent<{ index: number; item: HTMLMdListItemElement }>>,
    onMdReorder: EventName<MdListCustomEvent<{ from: number; to: number; order: number[] }>>
};

export const MdList: StencilReactComponent<MdListElement, MdListEvents, Components.MdList> = /*@__PURE__*/ createComponent<MdListElement, MdListEvents, Components.MdList>({
    tagName: 'md-list',
    elementClass: MdListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdSelect: 'mdSelect',
        onMdActivate: 'mdActivate',
        onMdReorder: 'mdReorder'
    } as MdListEvents,
    defineCustomElement: defineMdList
});
