'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdChartAxisClickDetail, MdChartClickDetail, MdChartHoverDetail, MdChartXYSeries, MdLineChartCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdLineChart as MdLineChartElement, defineCustomElement as defineMdLineChart } from "@awc-ui/core/dist/components/md-line-chart.js";

export type MdLineChartEvents = {
    onMdMarkerClick: EventName<MdLineChartCustomEvent<MdChartClickDetail<MdChartXYSeries>>>,
    onMdLineClick: EventName<MdLineChartCustomEvent<MdChartClickDetail<MdChartXYSeries>>>,
    onMdAreaClick: EventName<MdLineChartCustomEvent<MdChartClickDetail<MdChartXYSeries>>>,
    onMdAxisClick: EventName<MdLineChartCustomEvent<MdChartAxisClickDetail>>,
    onMdLegendClick: EventName<MdLineChartCustomEvent<{ seriesIndex: number; seriesId?: string; selected: boolean }>>,
    onMdHover: EventName<MdLineChartCustomEvent<MdChartHoverDetail>>,
    onMdReady: EventName<MdLineChartCustomEvent<void>>,
    onMdZoom: EventName<MdLineChartCustomEvent<{ startIndex: number; endIndex: number; reset: boolean }>>
};

export const MdLineChart: StencilReactComponent<MdLineChartElement, MdLineChartEvents, Components.MdLineChart> = /*@__PURE__*/ createComponent<MdLineChartElement, MdLineChartEvents, Components.MdLineChart>({
    tagName: 'md-line-chart',
    elementClass: MdLineChartElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdMarkerClick: 'mdMarkerClick',
        onMdLineClick: 'mdLineClick',
        onMdAreaClick: 'mdAreaClick',
        onMdAxisClick: 'mdAxisClick',
        onMdLegendClick: 'mdLegendClick',
        onMdHover: 'mdHover',
        onMdReady: 'mdReady',
        onMdZoom: 'mdZoom'
    } as MdLineChartEvents,
    defineCustomElement: defineMdLineChart
});
