'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdListItemCustomEvent, MdListItemExpandDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdListItem as MdListItemElement, defineCustomElement as defineMdListItem } from "@awc-ui/core/dist/components/md-list-item.js";

export type MdListItemEvents = {
    onMdClick: EventName<MdListItemCustomEvent<{ item: HTMLElement }>>,
    onMdItemClick: EventName<MdListItemCustomEvent<{ index: number; selected: boolean }>>,
    onMdItemSelect: EventName<MdListItemCustomEvent<{ index: number; value: string; selected: boolean; item: HTMLMdListItemElement; }>>,
    onMdRequestActivation: EventName<MdListItemCustomEvent<void>>,
    onMdItemRequestReorder: EventName<MdListItemCustomEvent<{ direction: 'up' | 'down'; from: number; }>>,
    onMdExpand: EventName<MdListItemCustomEvent<MdListItemExpandDetail>>
};

export const MdListItem: StencilReactComponent<MdListItemElement, MdListItemEvents, Components.MdListItem> = /*@__PURE__*/ createComponent<MdListItemElement, MdListItemEvents, Components.MdListItem>({
    tagName: 'md-list-item',
    elementClass: MdListItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdClick: 'mdClick',
        onMdItemClick: 'mdItemClick',
        onMdItemSelect: 'mdItemSelect',
        onMdRequestActivation: 'mdRequestActivation',
        onMdItemRequestReorder: 'mdItemRequestReorder',
        onMdExpand: 'mdExpand'
    } as MdListItemEvents,
    defineCustomElement: defineMdListItem
});
