'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdLoadingIndicator as MdLoadingIndicatorElement, defineCustomElement as defineMdLoadingIndicator } from "@awc-ui/core/dist/components/md-loading-indicator.js";

export type MdLoadingIndicatorEvents = NonNullable<unknown>;

export const MdLoadingIndicator: StencilReactComponent<MdLoadingIndicatorElement, MdLoadingIndicatorEvents, Components.MdLoadingIndicator> = /*@__PURE__*/ createComponent<MdLoadingIndicatorElement, MdLoadingIndicatorEvents, Components.MdLoadingIndicator>({
    tagName: 'md-loading-indicator',
    elementClass: MdLoadingIndicatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdLoadingIndicatorEvents,
    defineCustomElement: defineMdLoadingIndicator
});
