'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdMenuItemGroup as MdMenuItemGroupElement, defineCustomElement as defineMdMenuItemGroup } from "@awc-ui/core/dist/components/md-menu-item-group.js";

export type MdMenuItemGroupEvents = NonNullable<unknown>;

export const MdMenuItemGroup: StencilReactComponent<MdMenuItemGroupElement, MdMenuItemGroupEvents, Components.MdMenuItemGroup> = /*@__PURE__*/ createComponent<MdMenuItemGroupElement, MdMenuItemGroupEvents, Components.MdMenuItemGroup>({
    tagName: 'md-menu-item-group',
    elementClass: MdMenuItemGroupElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdMenuItemGroupEvents,
    defineCustomElement: defineMdMenuItemGroup
});
