'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdMenuItemCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdMenuItem as MdMenuItemElement, defineCustomElement as defineMdMenuItem } from "@awc-ui/core/dist/components/md-menu-item.js";

export type MdMenuItemEvents = { onMdClick: EventName<MdMenuItemCustomEvent<void>> };

export const MdMenuItem: StencilReactComponent<MdMenuItemElement, MdMenuItemEvents, Components.MdMenuItem> = /*@__PURE__*/ createComponent<MdMenuItemElement, MdMenuItemEvents, Components.MdMenuItem>({
    tagName: 'md-menu-item',
    elementClass: MdMenuItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdClick: 'mdClick' } as MdMenuItemEvents,
    defineCustomElement: defineMdMenuItem
});
