'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdMeter as MdMeterElement, defineCustomElement as defineMdMeter } from "@awc-ui/core/dist/components/md-meter.js";

export type MdMeterEvents = NonNullable<unknown>;

export const MdMeter: StencilReactComponent<MdMeterElement, MdMeterEvents, Components.MdMeter> = /*@__PURE__*/ createComponent<MdMeterElement, MdMeterEvents, Components.MdMeter>({
    tagName: 'md-meter',
    elementClass: MdMeterElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdMeterEvents,
    defineCustomElement: defineMdMeter
});
