'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdMenuCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdMenu as MdMenuElement, defineCustomElement as defineMdMenu } from "@awc-ui/core/dist/components/md-menu.js";

export type MdMenuEvents = {
    onMdOpen: EventName<MdMenuCustomEvent<void>>,
    onMdClose: EventName<MdMenuCustomEvent<void>>
};

export const MdMenu: StencilReactComponent<MdMenuElement, MdMenuEvents, Components.MdMenu> = /*@__PURE__*/ createComponent<MdMenuElement, MdMenuEvents, Components.MdMenu>({
    tagName: 'md-menu',
    elementClass: MdMenuElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose'
    } as MdMenuEvents,
    defineCustomElement: defineMdMenu
});
