'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdMultiSelectCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdMultiSelect as MdMultiSelectElement, defineCustomElement as defineMdMultiSelect } from "@awc-ui/core/dist/components/md-multi-select.js";

export type MdMultiSelectEvents = {
    onMdChange: EventName<MdMultiSelectCustomEvent<string[]>>,
    onMdOpen: EventName<MdMultiSelectCustomEvent<void>>,
    onMdClose: EventName<MdMultiSelectCustomEvent<void>>,
    onMdRemove: EventName<MdMultiSelectCustomEvent<string>>,
    onMdClear: EventName<MdMultiSelectCustomEvent<void>>,
    onMdValidityChange: EventName<MdMultiSelectCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdMultiSelect: StencilReactComponent<MdMultiSelectElement, MdMultiSelectEvents, Components.MdMultiSelect> = /*@__PURE__*/ createComponent<MdMultiSelectElement, MdMultiSelectEvents, Components.MdMultiSelect>({
    tagName: 'md-multi-select',
    elementClass: MdMultiSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdChange: 'mdChange',
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdRemove: 'mdRemove',
        onMdClear: 'mdClear',
        onMdValidityChange: 'mdValidityChange'
    } as MdMultiSelectEvents,
    defineCustomElement: defineMdMultiSelect
});
