'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdNavigationBarCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdNavigationBar as MdNavigationBarElement, defineCustomElement as defineMdNavigationBar } from "@awc-ui/core/dist/components/md-navigation-bar.js";

export type MdNavigationBarEvents = { onMdChange: EventName<MdNavigationBarCustomEvent<{ index: number; previousIndex: number }>> };

export const MdNavigationBar: StencilReactComponent<MdNavigationBarElement, MdNavigationBarEvents, Components.MdNavigationBar> = /*@__PURE__*/ createComponent<MdNavigationBarElement, MdNavigationBarEvents, Components.MdNavigationBar>({
    tagName: 'md-navigation-bar',
    elementClass: MdNavigationBarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdChange: 'mdChange' } as MdNavigationBarEvents,
    defineCustomElement: defineMdNavigationBar
});
