'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdNavigationRailTabCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdNavigationRailTab as MdNavigationRailTabElement, defineCustomElement as defineMdNavigationRailTab } from "@awc-ui/core/dist/components/md-navigation-rail-tab.js";

export type MdNavigationRailTabEvents = {
    onMdTabClick: EventName<MdNavigationRailTabCustomEvent<{ value: string }>>,
    onMdSubmenuToggle: EventName<MdNavigationRailTabCustomEvent<{ open: boolean }>>
};

export const MdNavigationRailTab: StencilReactComponent<MdNavigationRailTabElement, MdNavigationRailTabEvents, Components.MdNavigationRailTab> = /*@__PURE__*/ createComponent<MdNavigationRailTabElement, MdNavigationRailTabEvents, Components.MdNavigationRailTab>({
    tagName: 'md-navigation-rail-tab',
    elementClass: MdNavigationRailTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdTabClick: 'mdTabClick',
        onMdSubmenuToggle: 'mdSubmenuToggle'
    } as MdNavigationRailTabEvents,
    defineCustomElement: defineMdNavigationRailTab
});
