'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdNavigationTabCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdNavigationTab as MdNavigationTabElement, defineCustomElement as defineMdNavigationTab } from "@awc-ui/core/dist/components/md-navigation-tab.js";

export type MdNavigationTabEvents = { onMdTabClick: EventName<MdNavigationTabCustomEvent<{ index: number }>> };

export const MdNavigationTab: StencilReactComponent<MdNavigationTabElement, MdNavigationTabEvents, Components.MdNavigationTab> = /*@__PURE__*/ createComponent<MdNavigationTabElement, MdNavigationTabEvents, Components.MdNavigationTab>({
    tagName: 'md-navigation-tab',
    elementClass: MdNavigationTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdTabClick: 'mdTabClick' } as MdNavigationTabEvents,
    defineCustomElement: defineMdNavigationTab
});
