'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdNavigationRailCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdNavigationRail as MdNavigationRailElement, defineCustomElement as defineMdNavigationRail } from "@awc-ui/core/dist/components/md-navigation-rail.js";

export type MdNavigationRailEvents = {
    onMdTabChange: EventName<MdNavigationRailCustomEvent<{ index: number; value: string }>>,
    onMdExpand: EventName<MdNavigationRailCustomEvent<void>>,
    onMdCollapse: EventName<MdNavigationRailCustomEvent<void>>
};

export const MdNavigationRail: StencilReactComponent<MdNavigationRailElement, MdNavigationRailEvents, Components.MdNavigationRail> = /*@__PURE__*/ createComponent<MdNavigationRailElement, MdNavigationRailEvents, Components.MdNavigationRail>({
    tagName: 'md-navigation-rail',
    elementClass: MdNavigationRailElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdTabChange: 'mdTabChange',
        onMdExpand: 'mdExpand',
        onMdCollapse: 'mdCollapse'
    } as MdNavigationRailEvents,
    defineCustomElement: defineMdNavigationRail
});
