'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdNumberFieldChangeDetail, MdNumberFieldCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdNumberField as MdNumberFieldElement, defineCustomElement as defineMdNumberField } from "@awc-ui/core/dist/components/md-number-field.js";

export type MdNumberFieldEvents = {
    onMdInput: EventName<MdNumberFieldCustomEvent<MdNumberFieldChangeDetail>>,
    onMdChange: EventName<MdNumberFieldCustomEvent<MdNumberFieldChangeDetail>>,
    onMdValidityChange: EventName<MdNumberFieldCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdNumberField: StencilReactComponent<MdNumberFieldElement, MdNumberFieldEvents, Components.MdNumberField> = /*@__PURE__*/ createComponent<MdNumberFieldElement, MdNumberFieldEvents, Components.MdNumberField>({
    tagName: 'md-number-field',
    elementClass: MdNumberFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdInput: 'mdInput',
        onMdChange: 'mdChange',
        onMdValidityChange: 'mdValidityChange'
    } as MdNumberFieldEvents,
    defineCustomElement: defineMdNumberField
});
