'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdOrganizationChartCustomEvent, OrgChartSelectionChangeDetail, OrgChartToggleDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdOrganizationChart as MdOrganizationChartElement, defineCustomElement as defineMdOrganizationChart } from "@awc-ui/core/dist/components/md-organization-chart.js";

export type MdOrganizationChartEvents = {
    onMdSelectionChange: EventName<MdOrganizationChartCustomEvent<OrgChartSelectionChangeDetail>>,
    onMdNodeToggle: EventName<MdOrganizationChartCustomEvent<OrgChartToggleDetail>>
};

export const MdOrganizationChart: StencilReactComponent<MdOrganizationChartElement, MdOrganizationChartEvents, Components.MdOrganizationChart> = /*@__PURE__*/ createComponent<MdOrganizationChartElement, MdOrganizationChartEvents, Components.MdOrganizationChart>({
    tagName: 'md-organization-chart',
    elementClass: MdOrganizationChartElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdSelectionChange: 'mdSelectionChange',
        onMdNodeToggle: 'mdNodeToggle'
    } as MdOrganizationChartEvents,
    defineCustomElement: defineMdOrganizationChart
});
