'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdOtpFieldCompleteDetail, MdOtpFieldCustomEvent, MdOtpFieldInvalidDetail, MdOtpFieldValidityDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdOtpField as MdOtpFieldElement, defineCustomElement as defineMdOtpField } from "@awc-ui/core/dist/components/md-otp-field.js";

export type MdOtpFieldEvents = {
    onMdInput: EventName<MdOtpFieldCustomEvent<string>>,
    onMdChange: EventName<MdOtpFieldCustomEvent<string>>,
    onMdComplete: EventName<MdOtpFieldCustomEvent<MdOtpFieldCompleteDetail>>,
    onMdInvalidInput: EventName<MdOtpFieldCustomEvent<MdOtpFieldInvalidDetail>>,
    onMdValidityChange: EventName<MdOtpFieldCustomEvent<MdOtpFieldValidityDetail>>
};

export const MdOtpField: StencilReactComponent<MdOtpFieldElement, MdOtpFieldEvents, Components.MdOtpField> = /*@__PURE__*/ createComponent<MdOtpFieldElement, MdOtpFieldEvents, Components.MdOtpField>({
    tagName: 'md-otp-field',
    elementClass: MdOtpFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdInput: 'mdInput',
        onMdChange: 'mdChange',
        onMdComplete: 'mdComplete',
        onMdInvalidInput: 'mdInvalidInput',
        onMdValidityChange: 'mdValidityChange'
    } as MdOtpFieldEvents,
    defineCustomElement: defineMdOtpField
});
