'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdChartClickDetail, MdPieChartCustomEvent, MdPieDatum } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdPieChart as MdPieChartElement, defineCustomElement as defineMdPieChart } from "@awc-ui/core/dist/components/md-pie-chart.js";

export type MdPieChartEvents = {
    onMdSliceClick: EventName<MdPieChartCustomEvent<MdChartClickDetail<MdPieDatum>>>,
    onMdLegendClick: EventName<MdPieChartCustomEvent<{ dataIndex: number; selected: boolean }>>,
    onMdReady: EventName<MdPieChartCustomEvent<void>>
};

export const MdPieChart: StencilReactComponent<MdPieChartElement, MdPieChartEvents, Components.MdPieChart> = /*@__PURE__*/ createComponent<MdPieChartElement, MdPieChartEvents, Components.MdPieChart>({
    tagName: 'md-pie-chart',
    elementClass: MdPieChartElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdSliceClick: 'mdSliceClick',
        onMdLegendClick: 'mdLegendClick',
        onMdReady: 'mdReady'
    } as MdPieChartEvents,
    defineCustomElement: defineMdPieChart
});
