'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdProgressIndicatorCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdProgressIndicator as MdProgressIndicatorElement, defineCustomElement as defineMdProgressIndicator } from "@awc-ui/core/dist/components/md-progress-indicator.js";

export type MdProgressIndicatorEvents = { onMdComplete: EventName<MdProgressIndicatorCustomEvent<void>> };

export const MdProgressIndicator: StencilReactComponent<MdProgressIndicatorElement, MdProgressIndicatorEvents, Components.MdProgressIndicator> = /*@__PURE__*/ createComponent<MdProgressIndicatorElement, MdProgressIndicatorEvents, Components.MdProgressIndicator>({
    tagName: 'md-progress-indicator',
    elementClass: MdProgressIndicatorElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdComplete: 'mdComplete' } as MdProgressIndicatorEvents,
    defineCustomElement: defineMdProgressIndicator
});
