'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdRadioCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdRadio as MdRadioElement, defineCustomElement as defineMdRadio } from "@awc-ui/core/dist/components/md-radio.js";

export type MdRadioEvents = {
    onMdChange: EventName<MdRadioCustomEvent<{ checked: boolean; value: string }>>,
    onMdFocus: EventName<MdRadioCustomEvent<void>>,
    onMdBlur: EventName<MdRadioCustomEvent<void>>,
    onMdValidityChange: EventName<MdRadioCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdRadio: StencilReactComponent<MdRadioElement, MdRadioEvents, Components.MdRadio> = /*@__PURE__*/ createComponent<MdRadioElement, MdRadioEvents, Components.MdRadio>({
    tagName: 'md-radio',
    elementClass: MdRadioElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdChange: 'mdChange',
        onMdFocus: 'mdFocus',
        onMdBlur: 'mdBlur',
        onMdValidityChange: 'mdValidityChange'
    } as MdRadioEvents,
    defineCustomElement: defineMdRadio
});
