'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdRatingCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdRating as MdRatingElement, defineCustomElement as defineMdRating } from "@awc-ui/core/dist/components/md-rating.js";

export type MdRatingEvents = {
    onMdHover: EventName<MdRatingCustomEvent<number | null>>,
    onMdChange: EventName<MdRatingCustomEvent<number>>
};

export const MdRating: StencilReactComponent<MdRatingElement, MdRatingEvents, Components.MdRating> = /*@__PURE__*/ createComponent<MdRatingElement, MdRatingEvents, Components.MdRating>({
    tagName: 'md-rating',
    elementClass: MdRatingElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdHover: 'mdHover',
        onMdChange: 'mdChange'
    } as MdRatingEvents,
    defineCustomElement: defineMdRating
});
