'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdRipple as MdRippleElement, defineCustomElement as defineMdRipple } from "@awc-ui/core/dist/components/md-ripple.js";

export type MdRippleEvents = NonNullable<unknown>;

export const MdRipple: StencilReactComponent<MdRippleElement, MdRippleEvents, Components.MdRipple> = /*@__PURE__*/ createComponent<MdRippleElement, MdRippleEvents, Components.MdRipple>({
    tagName: 'md-ripple',
    elementClass: MdRippleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdRippleEvents,
    defineCustomElement: defineMdRipple
});
