'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSegmentedButtonSetCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSegmentedButtonSet as MdSegmentedButtonSetElement, defineCustomElement as defineMdSegmentedButtonSet } from "@awc-ui/core/dist/components/md-segmented-button-set.js";

export type MdSegmentedButtonSetEvents = { onMdChange: EventName<MdSegmentedButtonSetCustomEvent<string[]>> };

export const MdSegmentedButtonSet: StencilReactComponent<MdSegmentedButtonSetElement, MdSegmentedButtonSetEvents, Components.MdSegmentedButtonSet> = /*@__PURE__*/ createComponent<MdSegmentedButtonSetElement, MdSegmentedButtonSetEvents, Components.MdSegmentedButtonSet>({
    tagName: 'md-segmented-button-set',
    elementClass: MdSegmentedButtonSetElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdChange: 'mdChange' } as MdSegmentedButtonSetEvents,
    defineCustomElement: defineMdSegmentedButtonSet
});
