'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSegmentedButtonCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSegmentedButton as MdSegmentedButtonElement, defineCustomElement as defineMdSegmentedButton } from "@awc-ui/core/dist/components/md-segmented-button.js";

export type MdSegmentedButtonEvents = { onMdSegmentClick: EventName<MdSegmentedButtonCustomEvent<{ value: string; selected: boolean }>> };

export const MdSegmentedButton: StencilReactComponent<MdSegmentedButtonElement, MdSegmentedButtonEvents, Components.MdSegmentedButton> = /*@__PURE__*/ createComponent<MdSegmentedButtonElement, MdSegmentedButtonEvents, Components.MdSegmentedButton>({
    tagName: 'md-segmented-button',
    elementClass: MdSegmentedButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdSegmentClick: 'mdSegmentClick' } as MdSegmentedButtonEvents,
    defineCustomElement: defineMdSegmentedButton
});
