'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSelectCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSelect as MdSelectElement, defineCustomElement as defineMdSelect } from "@awc-ui/core/dist/components/md-select.js";

export type MdSelectEvents = {
    onMdChange: EventName<MdSelectCustomEvent<string>>,
    onMdOpen: EventName<MdSelectCustomEvent<void>>,
    onMdClose: EventName<MdSelectCustomEvent<void>>,
    onMdValidityChange: EventName<MdSelectCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdSelect: StencilReactComponent<MdSelectElement, MdSelectEvents, Components.MdSelect> = /*@__PURE__*/ createComponent<MdSelectElement, MdSelectEvents, Components.MdSelect>({
    tagName: 'md-select',
    elementClass: MdSelectElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdChange: 'mdChange',
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdValidityChange: 'mdValidityChange'
    } as MdSelectEvents,
    defineCustomElement: defineMdSelect
});
