'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSearchCustomEvent, MdSearchLeadingIconClickDetail, MdSearchTrailingIconClickDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSearch as MdSearchElement, defineCustomElement as defineMdSearch } from "@awc-ui/core/dist/components/md-search.js";

export type MdSearchEvents = {
    onMdInput: EventName<MdSearchCustomEvent<{ value: string }>>,
    onMdSearch: EventName<MdSearchCustomEvent<{ value: string }>>,
    onMdSubmit: EventName<MdSearchCustomEvent<{ value: string }>>,
    onMdChange: EventName<MdSearchCustomEvent<{ value: string }>>,
    onMdOpen: EventName<MdSearchCustomEvent<void>>,
    onMdClose: EventName<MdSearchCustomEvent<void>>,
    onMdClear: EventName<MdSearchCustomEvent<void>>,
    onMdVoice: EventName<MdSearchCustomEvent<{ value: string; final: boolean }>>,
    onMdLeadingIconClick: EventName<MdSearchCustomEvent<MdSearchLeadingIconClickDetail>>,
    onMdTrailingIconClick: EventName<MdSearchCustomEvent<MdSearchTrailingIconClickDetail>>
};

export const MdSearch: StencilReactComponent<MdSearchElement, MdSearchEvents, Components.MdSearch> = /*@__PURE__*/ createComponent<MdSearchElement, MdSearchEvents, Components.MdSearch>({
    tagName: 'md-search',
    elementClass: MdSearchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdInput: 'mdInput',
        onMdSearch: 'mdSearch',
        onMdSubmit: 'mdSubmit',
        onMdChange: 'mdChange',
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdClear: 'mdClear',
        onMdVoice: 'mdVoice',
        onMdLeadingIconClick: 'mdLeadingIconClick',
        onMdTrailingIconClick: 'mdTrailingIconClick'
    } as MdSearchEvents,
    defineCustomElement: defineMdSearch
});
