'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSelectOptionCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSelectOption as MdSelectOptionElement, defineCustomElement as defineMdSelectOption } from "@awc-ui/core/dist/components/md-select-option.js";

export type MdSelectOptionEvents = { onMdSelectOptionChange: EventName<MdSelectOptionCustomEvent<void>> };

export const MdSelectOption: StencilReactComponent<MdSelectOptionElement, MdSelectOptionEvents, Components.MdSelectOption> = /*@__PURE__*/ createComponent<MdSelectOptionElement, MdSelectOptionEvents, Components.MdSelectOption>({
    tagName: 'md-select-option',
    elementClass: MdSelectOptionElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdSelectOptionChange: 'mdSelectOptionChange' } as MdSelectOptionEvents,
    defineCustomElement: defineMdSelectOption
});
