'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSideSheetCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSideSheet as MdSideSheetElement, defineCustomElement as defineMdSideSheet } from "@awc-ui/core/dist/components/md-side-sheet.js";

export type MdSideSheetEvents = {
    onMdOpen: EventName<MdSideSheetCustomEvent<void>>,
    onMdClose: EventName<MdSideSheetCustomEvent<void>>,
    onMdCancel: EventName<MdSideSheetCustomEvent<void>>,
    onMdBack: EventName<MdSideSheetCustomEvent<void>>
};

export const MdSideSheet: StencilReactComponent<MdSideSheetElement, MdSideSheetEvents, Components.MdSideSheet> = /*@__PURE__*/ createComponent<MdSideSheetElement, MdSideSheetEvents, Components.MdSideSheet>({
    tagName: 'md-side-sheet',
    elementClass: MdSideSheetElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdCancel: 'mdCancel',
        onMdBack: 'mdBack'
    } as MdSideSheetEvents,
    defineCustomElement: defineMdSideSheet
});
