'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdSkeleton as MdSkeletonElement, defineCustomElement as defineMdSkeleton } from "@awc-ui/core/dist/components/md-skeleton.js";

export type MdSkeletonEvents = NonNullable<unknown>;

export const MdSkeleton: StencilReactComponent<MdSkeletonElement, MdSkeletonEvents, Components.MdSkeleton> = /*@__PURE__*/ createComponent<MdSkeletonElement, MdSkeletonEvents, Components.MdSkeleton>({
    tagName: 'md-skeleton',
    elementClass: MdSkeletonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdSkeletonEvents,
    defineCustomElement: defineMdSkeleton
});
