'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSliderCustomEvent, MdSliderDragDetail, MdSliderThumbDetail, MdSliderValueDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSlider as MdSliderElement, defineCustomElement as defineMdSlider } from "@awc-ui/core/dist/components/md-slider.js";

export type MdSliderEvents = {
    onMdInput: EventName<MdSliderCustomEvent<MdSliderValueDetail>>,
    onMdChange: EventName<MdSliderCustomEvent<MdSliderValueDetail>>,
    onMdFocus: EventName<MdSliderCustomEvent<MdSliderThumbDetail>>,
    onMdBlur: EventName<MdSliderCustomEvent<MdSliderThumbDetail>>,
    onMdDragStart: EventName<MdSliderCustomEvent<MdSliderDragDetail>>,
    onMdDragEnd: EventName<MdSliderCustomEvent<MdSliderDragDetail>>
};

export const MdSlider: StencilReactComponent<MdSliderElement, MdSliderEvents, Components.MdSlider> = /*@__PURE__*/ createComponent<MdSliderElement, MdSliderEvents, Components.MdSlider>({
    tagName: 'md-slider',
    elementClass: MdSliderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdInput: 'mdInput',
        onMdChange: 'mdChange',
        onMdFocus: 'mdFocus',
        onMdBlur: 'mdBlur',
        onMdDragStart: 'mdDragStart',
        onMdDragEnd: 'mdDragEnd'
    } as MdSliderEvents,
    defineCustomElement: defineMdSlider
});
