'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSnackbarCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSnackbar as MdSnackbarElement, defineCustomElement as defineMdSnackbar } from "@awc-ui/core/dist/components/md-snackbar.js";

export type MdSnackbarEvents = {
    onMdOpen: EventName<MdSnackbarCustomEvent<void>>,
    onMdClose: EventName<MdSnackbarCustomEvent<{ reason: 'auto' | 'action' | 'close' }>>,
    onMdAction: EventName<MdSnackbarCustomEvent<void>>
};

export const MdSnackbar: StencilReactComponent<MdSnackbarElement, MdSnackbarEvents, Components.MdSnackbar> = /*@__PURE__*/ createComponent<MdSnackbarElement, MdSnackbarEvents, Components.MdSnackbar>({
    tagName: 'md-snackbar',
    elementClass: MdSnackbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdAction: 'mdAction'
    } as MdSnackbarEvents,
    defineCustomElement: defineMdSnackbar
});
