'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSparklineCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSparkline as MdSparklineElement, defineCustomElement as defineMdSparkline } from "@awc-ui/core/dist/components/md-sparkline.js";

export type MdSparklineEvents = {
    onMdSparkClick: EventName<MdSparklineCustomEvent<{ dataIndex: number; value: number | null }>>,
    onMdReady: EventName<MdSparklineCustomEvent<void>>
};

export const MdSparkline: StencilReactComponent<MdSparklineElement, MdSparklineEvents, Components.MdSparkline> = /*@__PURE__*/ createComponent<MdSparklineElement, MdSparklineEvents, Components.MdSparkline>({
    tagName: 'md-sparkline',
    elementClass: MdSparklineElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdSparkClick: 'mdSparkClick',
        onMdReady: 'mdReady'
    } as MdSparklineEvents,
    defineCustomElement: defineMdSparkline
});
