'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSplitButtonCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSplitButton as MdSplitButtonElement, defineCustomElement as defineMdSplitButton } from "@awc-ui/core/dist/components/md-split-button.js";

export type MdSplitButtonEvents = {
    onMdLeadingClick: EventName<MdSplitButtonCustomEvent<void>>,
    onMdTrailingClick: EventName<MdSplitButtonCustomEvent<{ checked: boolean }>>
};

export const MdSplitButton: StencilReactComponent<MdSplitButtonElement, MdSplitButtonEvents, Components.MdSplitButton> = /*@__PURE__*/ createComponent<MdSplitButtonElement, MdSplitButtonEvents, Components.MdSplitButton>({
    tagName: 'md-split-button',
    elementClass: MdSplitButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdLeadingClick: 'mdLeadingClick',
        onMdTrailingClick: 'mdTrailingClick'
    } as MdSplitButtonEvents,
    defineCustomElement: defineMdSplitButton
});
