'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdStatusDot as MdStatusDotElement, defineCustomElement as defineMdStatusDot } from "@awc-ui/core/dist/components/md-status-dot.js";

export type MdStatusDotEvents = NonNullable<unknown>;

export const MdStatusDot: StencilReactComponent<MdStatusDotElement, MdStatusDotEvents, Components.MdStatusDot> = /*@__PURE__*/ createComponent<MdStatusDotElement, MdStatusDotEvents, Components.MdStatusDot>({
    tagName: 'md-status-dot',
    elementClass: MdStatusDotElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdStatusDotEvents,
    defineCustomElement: defineMdStatusDot
});
