'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdStepperCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdStepper as MdStepperElement, defineCustomElement as defineMdStepper } from "@awc-ui/core/dist/components/md-stepper.js";

export type MdStepperEvents = {
    onMdBeforeChange: EventName<MdStepperCustomEvent<{ index: number; previous: number }>>,
    onMdStepChange: EventName<MdStepperCustomEvent<{ index: number; previous: number }>>,
    onMdComplete: EventName<MdStepperCustomEvent<void>>
};

export const MdStepper: StencilReactComponent<MdStepperElement, MdStepperEvents, Components.MdStepper> = /*@__PURE__*/ createComponent<MdStepperElement, MdStepperEvents, Components.MdStepper>({
    tagName: 'md-stepper',
    elementClass: MdStepperElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdBeforeChange: 'mdBeforeChange',
        onMdStepChange: 'mdStepChange',
        onMdComplete: 'mdComplete'
    } as MdStepperEvents,
    defineCustomElement: defineMdStepper
});
