'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdStepCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdStep as MdStepElement, defineCustomElement as defineMdStep } from "@awc-ui/core/dist/components/md-step.js";

export type MdStepEvents = {
    onMdStepClick: EventName<MdStepCustomEvent<{ index: number }>>,
    onMdStepNext: EventName<MdStepCustomEvent<{ index: number }>>,
    onMdStepBack: EventName<MdStepCustomEvent<{ index: number }>>
};

export const MdStep: StencilReactComponent<MdStepElement, MdStepEvents, Components.MdStep> = /*@__PURE__*/ createComponent<MdStepElement, MdStepEvents, Components.MdStep>({
    tagName: 'md-step',
    elementClass: MdStepElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdStepClick: 'mdStepClick',
        onMdStepNext: 'mdStepNext',
        onMdStepBack: 'mdStepBack'
    } as MdStepEvents,
    defineCustomElement: defineMdStep
});
