'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSubMenuItemCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSubMenuItem as MdSubMenuItemElement, defineCustomElement as defineMdSubMenuItem } from "@awc-ui/core/dist/components/md-sub-menu-item.js";

export type MdSubMenuItemEvents = { onMdClick: EventName<MdSubMenuItemCustomEvent<void>> };

export const MdSubMenuItem: StencilReactComponent<MdSubMenuItemElement, MdSubMenuItemEvents, Components.MdSubMenuItem> = /*@__PURE__*/ createComponent<MdSubMenuItemElement, MdSubMenuItemEvents, Components.MdSubMenuItem>({
    tagName: 'md-sub-menu-item',
    elementClass: MdSubMenuItemElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdClick: 'mdClick' } as MdSubMenuItemEvents,
    defineCustomElement: defineMdSubMenuItem
});
