'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdSwitchCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdSwitch as MdSwitchElement, defineCustomElement as defineMdSwitch } from "@awc-ui/core/dist/components/md-switch.js";

export type MdSwitchEvents = {
    onMdInput: EventName<MdSwitchCustomEvent<{ selected: boolean }>>,
    onMdChange: EventName<MdSwitchCustomEvent<{ selected: boolean }>>,
    onMdValidityChange: EventName<MdSwitchCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdSwitch: StencilReactComponent<MdSwitchElement, MdSwitchEvents, Components.MdSwitch> = /*@__PURE__*/ createComponent<MdSwitchElement, MdSwitchEvents, Components.MdSwitch>({
    tagName: 'md-switch',
    elementClass: MdSwitchElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdInput: 'mdInput',
        onMdChange: 'mdChange',
        onMdValidityChange: 'mdValidityChange'
    } as MdSwitchEvents,
    defineCustomElement: defineMdSwitch
});
