'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdTableBody as MdTableBodyElement, defineCustomElement as defineMdTableBody } from "@awc-ui/core/dist/components/md-table-body.js";

export type MdTableBodyEvents = NonNullable<unknown>;

export const MdTableBody: StencilReactComponent<MdTableBodyElement, MdTableBodyEvents, Components.MdTableBody> = /*@__PURE__*/ createComponent<MdTableBodyElement, MdTableBodyEvents, Components.MdTableBody>({
    tagName: 'md-table-body',
    elementClass: MdTableBodyElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdTableBodyEvents,
    defineCustomElement: defineMdTableBody
});
