'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdTabPanel as MdTabPanelElement, defineCustomElement as defineMdTabPanel } from "@awc-ui/core/dist/components/md-tab-panel.js";

export type MdTabPanelEvents = NonNullable<unknown>;

export const MdTabPanel: StencilReactComponent<MdTabPanelElement, MdTabPanelEvents, Components.MdTabPanel> = /*@__PURE__*/ createComponent<MdTabPanelElement, MdTabPanelEvents, Components.MdTabPanel>({
    tagName: 'md-tab-panel',
    elementClass: MdTabPanelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdTabPanelEvents,
    defineCustomElement: defineMdTabPanel
});
