'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTableSortLabelCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTableSortLabel as MdTableSortLabelElement, defineCustomElement as defineMdTableSortLabel } from "@awc-ui/core/dist/components/md-table-sort-label.js";

export type MdTableSortLabelEvents = { onMdSortRequest: EventName<MdTableSortLabelCustomEvent<{ column: string; defaultOrder: 'asc' | 'desc' }>> };

export const MdTableSortLabel: StencilReactComponent<MdTableSortLabelElement, MdTableSortLabelEvents, Components.MdTableSortLabel> = /*@__PURE__*/ createComponent<MdTableSortLabelElement, MdTableSortLabelEvents, Components.MdTableSortLabel>({
    tagName: 'md-table-sort-label',
    elementClass: MdTableSortLabelElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdSortRequest: 'mdSortRequest' } as MdTableSortLabelEvents,
    defineCustomElement: defineMdTableSortLabel
});
