'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdTableFoot as MdTableFootElement, defineCustomElement as defineMdTableFoot } from "@awc-ui/core/dist/components/md-table-foot.js";

export type MdTableFootEvents = NonNullable<unknown>;

export const MdTableFoot: StencilReactComponent<MdTableFootElement, MdTableFootEvents, Components.MdTableFoot> = /*@__PURE__*/ createComponent<MdTableFootElement, MdTableFootEvents, Components.MdTableFoot>({
    tagName: 'md-table-foot',
    elementClass: MdTableFootElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdTableFootEvents,
    defineCustomElement: defineMdTableFoot
});
