'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdTableCell as MdTableCellElement, defineCustomElement as defineMdTableCell } from "@awc-ui/core/dist/components/md-table-cell.js";

export type MdTableCellEvents = NonNullable<unknown>;

export const MdTableCell: StencilReactComponent<MdTableCellElement, MdTableCellEvents, Components.MdTableCell> = /*@__PURE__*/ createComponent<MdTableCellElement, MdTableCellEvents, Components.MdTableCell>({
    tagName: 'md-table-cell',
    elementClass: MdTableCellElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdTableCellEvents,
    defineCustomElement: defineMdTableCell
});
