'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdTabPanels as MdTabPanelsElement, defineCustomElement as defineMdTabPanels } from "@awc-ui/core/dist/components/md-tab-panels.js";

export type MdTabPanelsEvents = NonNullable<unknown>;

export const MdTabPanels: StencilReactComponent<MdTabPanelsElement, MdTabPanelsEvents, Components.MdTabPanels> = /*@__PURE__*/ createComponent<MdTabPanelsElement, MdTabPanelsEvents, Components.MdTabPanels>({
    tagName: 'md-tab-panels',
    elementClass: MdTabPanelsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdTabPanelsEvents,
    defineCustomElement: defineMdTabPanels
});
