'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdTableExpandToggle as MdTableExpandToggleElement, defineCustomElement as defineMdTableExpandToggle } from "@awc-ui/core/dist/components/md-table-expand-toggle.js";

export type MdTableExpandToggleEvents = NonNullable<unknown>;

export const MdTableExpandToggle: StencilReactComponent<MdTableExpandToggleElement, MdTableExpandToggleEvents, Components.MdTableExpandToggle> = /*@__PURE__*/ createComponent<MdTableExpandToggleElement, MdTableExpandToggleEvents, Components.MdTableExpandToggle>({
    tagName: 'md-table-expand-toggle',
    elementClass: MdTableExpandToggleElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdTableExpandToggleEvents,
    defineCustomElement: defineMdTableExpandToggle
});
