'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdTableHead as MdTableHeadElement, defineCustomElement as defineMdTableHead } from "@awc-ui/core/dist/components/md-table-head.js";

export type MdTableHeadEvents = NonNullable<unknown>;

export const MdTableHead: StencilReactComponent<MdTableHeadElement, MdTableHeadEvents, Components.MdTableHead> = /*@__PURE__*/ createComponent<MdTableHeadElement, MdTableHeadEvents, Components.MdTableHead>({
    tagName: 'md-table-head',
    elementClass: MdTableHeadElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdTableHeadEvents,
    defineCustomElement: defineMdTableHead
});
