'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdTableContainer as MdTableContainerElement, defineCustomElement as defineMdTableContainer } from "@awc-ui/core/dist/components/md-table-container.js";

export type MdTableContainerEvents = NonNullable<unknown>;

export const MdTableContainer: StencilReactComponent<MdTableContainerElement, MdTableContainerEvents, Components.MdTableContainer> = /*@__PURE__*/ createComponent<MdTableContainerElement, MdTableContainerEvents, Components.MdTableContainer>({
    tagName: 'md-table-container',
    elementClass: MdTableContainerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdTableContainerEvents,
    defineCustomElement: defineMdTableContainer
});
