'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTableRowCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTableRow as MdTableRowElement, defineCustomElement as defineMdTableRow } from "@awc-ui/core/dist/components/md-table-row.js";

export type MdTableRowEvents = {
    onMdRowClick: EventName<MdTableRowCustomEvent<{ value: string; row: HTMLElement }>>,
    onMdRowSelectionChange: EventName<MdTableRowCustomEvent<{ selected: boolean; value: string }>>,
    onMdRowExpandedChange: EventName<MdTableRowCustomEvent<{ expanded: boolean }>>
};

export const MdTableRow: StencilReactComponent<MdTableRowElement, MdTableRowEvents, Components.MdTableRow> = /*@__PURE__*/ createComponent<MdTableRowElement, MdTableRowEvents, Components.MdTableRow>({
    tagName: 'md-table-row',
    elementClass: MdTableRowElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdRowClick: 'mdRowClick',
        onMdRowSelectionChange: 'mdRowSelectionChange',
        onMdRowExpandedChange: 'mdRowExpandedChange'
    } as MdTableRowEvents,
    defineCustomElement: defineMdTableRow
});
