'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTabsCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTabs as MdTabsElement, defineCustomElement as defineMdTabs } from "@awc-ui/core/dist/components/md-tabs.js";

export type MdTabsEvents = { onMdTabChange: EventName<MdTabsCustomEvent<{ index: number; previousIndex: number }>> };

export const MdTabs: StencilReactComponent<MdTabsElement, MdTabsEvents, Components.MdTabs> = /*@__PURE__*/ createComponent<MdTabsElement, MdTabsEvents, Components.MdTabs>({
    tagName: 'md-tabs',
    elementClass: MdTabsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdTabChange: 'mdTabChange' } as MdTabsEvents,
    defineCustomElement: defineMdTabs
});
