'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTabCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTab as MdTabElement, defineCustomElement as defineMdTab } from "@awc-ui/core/dist/components/md-tab.js";

export type MdTabEvents = { onMdTabClick: EventName<MdTabCustomEvent<void>> };

export const MdTab: StencilReactComponent<MdTabElement, MdTabEvents, Components.MdTab> = /*@__PURE__*/ createComponent<MdTabElement, MdTabEvents, Components.MdTab>({
    tagName: 'md-tab',
    elementClass: MdTabElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onMdTabClick: 'mdTabClick' } as MdTabEvents,
    defineCustomElement: defineMdTab
});
