'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdTableToolbar as MdTableToolbarElement, defineCustomElement as defineMdTableToolbar } from "@awc-ui/core/dist/components/md-table-toolbar.js";

export type MdTableToolbarEvents = NonNullable<unknown>;

export const MdTableToolbar: StencilReactComponent<MdTableToolbarElement, MdTableToolbarEvents, Components.MdTableToolbar> = /*@__PURE__*/ createComponent<MdTableToolbarElement, MdTableToolbarEvents, Components.MdTableToolbar>({
    tagName: 'md-table-toolbar',
    elementClass: MdTableToolbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdTableToolbarEvents,
    defineCustomElement: defineMdTableToolbar
});
