'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTablePaginationCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTablePagination as MdTablePaginationElement, defineCustomElement as defineMdTablePagination } from "@awc-ui/core/dist/components/md-table-pagination.js";

export type MdTablePaginationEvents = {
    onMdPageChange: EventName<MdTablePaginationCustomEvent<{ page: number }>>,
    onMdRowsPerPageChange: EventName<MdTablePaginationCustomEvent<{ rowsPerPage: number }>>
};

export const MdTablePagination: StencilReactComponent<MdTablePaginationElement, MdTablePaginationEvents, Components.MdTablePagination> = /*@__PURE__*/ createComponent<MdTablePaginationElement, MdTablePaginationEvents, Components.MdTablePagination>({
    tagName: 'md-table-pagination',
    elementClass: MdTablePaginationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdPageChange: 'mdPageChange',
        onMdRowsPerPageChange: 'mdRowsPerPageChange'
    } as MdTablePaginationEvents,
    defineCustomElement: defineMdTablePagination
});
