'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTableCustomEvent, MdTableSelectionState, MdTableSortState } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTable as MdTableElement, defineCustomElement as defineMdTable } from "@awc-ui/core/dist/components/md-table.js";

export type MdTableEvents = {
    onMdSortChange: EventName<MdTableCustomEvent<MdTableSortState>>,
    onMdSelectionChange: EventName<MdTableCustomEvent<MdTableSelectionState>>,
    onMdPinChange: EventName<MdTableCustomEvent<{ column: number; side: 'start' | 'end' | null }>>,
    onMdColumnVisibilityChange: EventName<MdTableCustomEvent<{ column: number; visible: boolean; hidden: number[] }>>,
    onMdScroll: EventName<MdTableCustomEvent<{ scrollLeft: number; scrollTop: number }>>
};

export const MdTable: StencilReactComponent<MdTableElement, MdTableEvents, Components.MdTable> = /*@__PURE__*/ createComponent<MdTableElement, MdTableEvents, Components.MdTable>({
    tagName: 'md-table',
    elementClass: MdTableElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdSortChange: 'mdSortChange',
        onMdSelectionChange: 'mdSelectionChange',
        onMdPinChange: 'mdPinChange',
        onMdColumnVisibilityChange: 'mdColumnVisibilityChange',
        onMdScroll: 'mdScroll'
    } as MdTableEvents,
    defineCustomElement: defineMdTable
});
