'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTextFieldCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTextField as MdTextFieldElement, defineCustomElement as defineMdTextField } from "@awc-ui/core/dist/components/md-text-field.js";

export type MdTextFieldEvents = {
    onMdInput: EventName<MdTextFieldCustomEvent<string>>,
    onMdChange: EventName<MdTextFieldCustomEvent<string>>,
    onMdSearch: EventName<MdTextFieldCustomEvent<string>>,
    onMdClear: EventName<MdTextFieldCustomEvent<void>>,
    onMdPasswordToggle: EventName<MdTextFieldCustomEvent<{ visible: boolean }>>,
    onMdSpeechResult: EventName<MdTextFieldCustomEvent<{ transcript: string; listening: boolean }>>,
    onMdValidityChange: EventName<MdTextFieldCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdTextField: StencilReactComponent<MdTextFieldElement, MdTextFieldEvents, Components.MdTextField> = /*@__PURE__*/ createComponent<MdTextFieldElement, MdTextFieldEvents, Components.MdTextField>({
    tagName: 'md-text-field',
    elementClass: MdTextFieldElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdInput: 'mdInput',
        onMdChange: 'mdChange',
        onMdSearch: 'mdSearch',
        onMdClear: 'mdClear',
        onMdPasswordToggle: 'mdPasswordToggle',
        onMdSpeechResult: 'mdSpeechResult',
        onMdValidityChange: 'mdValidityChange'
    } as MdTextFieldEvents,
    defineCustomElement: defineMdTextField
});
