'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTimePickerChangeDetail, MdTimePickerCustomEvent, MdTimePickerModeChangeDetail } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTimePicker as MdTimePickerElement, defineCustomElement as defineMdTimePicker } from "@awc-ui/core/dist/components/md-time-picker.js";

export type MdTimePickerEvents = {
    onMdChange: EventName<MdTimePickerCustomEvent<MdTimePickerChangeDetail>>,
    onMdInput: EventName<MdTimePickerCustomEvent<MdTimePickerChangeDetail>>,
    onMdOpen: EventName<MdTimePickerCustomEvent<void>>,
    onMdClose: EventName<MdTimePickerCustomEvent<void>>,
    onMdCancel: EventName<MdTimePickerCustomEvent<void>>,
    onMdModeChange: EventName<MdTimePickerCustomEvent<MdTimePickerModeChangeDetail>>,
    onMdValidityChange: EventName<MdTimePickerCustomEvent<{ valid: boolean; validationMessage: string; flags: Record<string, boolean>; }>>
};

export const MdTimePicker: StencilReactComponent<MdTimePickerElement, MdTimePickerEvents, Components.MdTimePicker> = /*@__PURE__*/ createComponent<MdTimePickerElement, MdTimePickerEvents, Components.MdTimePicker>({
    tagName: 'md-time-picker',
    elementClass: MdTimePickerElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdChange: 'mdChange',
        onMdInput: 'mdInput',
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose',
        onMdCancel: 'mdCancel',
        onMdModeChange: 'mdModeChange',
        onMdValidityChange: 'mdValidityChange'
    } as MdTimePickerEvents,
    defineCustomElement: defineMdTimePicker
});
