'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { Components } from "@awc-ui/core/dist/components";
import { MdToolbar as MdToolbarElement, defineCustomElement as defineMdToolbar } from "@awc-ui/core/dist/components/md-toolbar.js";

export type MdToolbarEvents = NonNullable<unknown>;

export const MdToolbar: StencilReactComponent<MdToolbarElement, MdToolbarEvents, Components.MdToolbar> = /*@__PURE__*/ createComponent<MdToolbarElement, MdToolbarEvents, Components.MdToolbar>({
    tagName: 'md-toolbar',
    elementClass: MdToolbarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MdToolbarEvents,
    defineCustomElement: defineMdToolbar
});
