'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTooltipCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTooltip as MdTooltipElement, defineCustomElement as defineMdTooltip } from "@awc-ui/core/dist/components/md-tooltip.js";

export type MdTooltipEvents = {
    onMdOpen: EventName<MdTooltipCustomEvent<void>>,
    onMdClose: EventName<MdTooltipCustomEvent<void>>
};

export const MdTooltip: StencilReactComponent<MdTooltipElement, MdTooltipEvents, Components.MdTooltip> = /*@__PURE__*/ createComponent<MdTooltipElement, MdTooltipEvents, Components.MdTooltip>({
    tagName: 'md-tooltip',
    elementClass: MdTooltipElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdOpen: 'mdOpen',
        onMdClose: 'mdClose'
    } as MdTooltipEvents,
    defineCustomElement: defineMdTooltip
});
