'use client';

/**
 * Generated by scripts/split-react-components.mjs from the Stencil React Output
 * Target's components.ts. Do not edit — regenerated on every core build.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import type { MdTransferListCustomEvent } from "@awc-ui/core";
import type { Components } from "@awc-ui/core/dist/components";
import { MdTransferList as MdTransferListElement, defineCustomElement as defineMdTransferList } from "@awc-ui/core/dist/components/md-transfer-list.js";

export type MdTransferListEvents = {
    onMdChange: EventName<MdTransferListCustomEvent<string[]>>,
    onMdMove: EventName<MdTransferListCustomEvent<{ direction: 'left' | 'right'; moved: string[]; target: string[]; }>>
};

export const MdTransferList: StencilReactComponent<MdTransferListElement, MdTransferListEvents, Components.MdTransferList> = /*@__PURE__*/ createComponent<MdTransferListElement, MdTransferListEvents, Components.MdTransferList>({
    tagName: 'md-transfer-list',
    elementClass: MdTransferListElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onMdChange: 'mdChange',
        onMdMove: 'mdMove'
    } as MdTransferListEvents,
    defineCustomElement: defineMdTransferList
});
