export const ar = {
  "No acknowledged alarms": "لا توجد إنذارات تم الإقرار بها",
  "No matching alarms": "لا توجد إنذارات مطابقة",
  "Choose another severity or acknowledgment filter.":
    "اختر درجة خطورة أو حالة إقرار أخرى.",
  "Real AWC web components power the interactions throughout this workspace. Open Make it yours to change the primary color, density, or layout direction across the workspace.":
    "تعمل مساحة العمل بمكوّنات AWC الأصلية. افتح «خصّص تجربتك» لتغيير اللون الأساسي أو كثافة العرض أو اتجاه التخطيط.",
  "Responsive destinations, active states, and workspace context.":
    "وجهات متجاوبة وحالات نشطة وسياق مساحة العمل.",
  "Composable tables with sorting, filtering, and pagination.":
    "جداول قابلة للتركيب مع الفرز والتصفية وتقسيم الصفحات.",
  "Time series with zoom, compact trends, and semantic health indicators.":
    "سلاسل زمنية قابلة للتكبير واتجاهات موجزة ومؤشرات لحالة المعدات.",
  "Form validation, password visibility, code entry, and selection.":
    "التحقق من النماذج وإظهار كلمات المرور وإدخال الرموز والاختيار.",
  "Actions, severity filters, theme and density controls, and time ranges.":
    "الإجراءات وتصفية درجات الخطورة وإعدادات المظهر والكثافة والنطاقات الزمنية.",
  "Structured content, focused tasks, inspection, feedback, and identity.":
    "محتوى منظّم ومهام محددة وعرض التفاصيل والتغذية الراجعة والهوية.",
  "Sign out": "تسجيل الخروج",
  Overview: "نظرة عامة",
  Assets: "المعدات",
  Alarms: "الإنذارات",
  Trends: "الاتجاهات",
  Settings: "الإعدادات",
  "Main navigation": "التنقل الرئيسي",
  "Expand or collapse navigation": "توسيع قائمة التنقل أو طيها",
  "Plant location": "موقع المحطة",
  "Show plant breadcrumb": "عرض مسار المحطة",
  "North water treatment": "محطة معالجة المياه الشمالية",
  "North water treatment · Operations workspace":
    "محطة معالجة المياه الشمالية · مساحة العمليات",
  "Demo operator": "مشغّل تجريبي",
  "Demo workspace": "مساحة عمل تجريبية",
  "MFA demo verified": "تم التحقق التجريبي متعدد العوامل",
  Simulation: "محاكاة",
  Running: "قيد التشغيل",
  Paused: "متوقف مؤقتاً",
  Standby: "جاهز احتياطياً",
  Warning: "تحذير",
  Critical: "حرج",
  Offline: "غير متصل",
  Info: "معلومة",
  Acknowledged: "تم الإقرار",
  "Plant overview": "نظرة عامة على المحطة",
  "Plant key metrics": "المؤشرات الرئيسية للمحطة",
  "Pause simulation": "إيقاف المحاكاة مؤقتاً",
  "Resume simulation": "استئناف المحاكاة",
  "Export snapshot": "تصدير لقطة البيانات",
  "07 Sep 2026": "٧ سبتمبر ٢٠٢٦",
  "Intake flow": "تدفق السحب",
  "Tank level": "مستوى الخزان",
  "Connected assets": "المعدات المتصلة",
  "Active alarms": "الإنذارات النشطة",
  "Within operating range": "ضمن نطاق التشغيل",
  "Operating band 30–90%": "نطاق التشغيل ٣٠–٩٠٪",
  "1 device offline": "جهاز واحد غير متصل",
  "Flow performance": "أداء التدفق",
  "Intake flow · sampled process values": "تدفق السحب · عينات قيم العملية",
  "Simulated samples": "عينات محاكاة",
  "Simulated process history": "سجل محاكاة العملية",
  "Trend time range": "النطاق الزمني للاتجاهات",
  "1h": "ساعة",
  "6h": "٦ ساعات",
  "24h": "٢٤ ساعة",
  "Needs attention": "يحتاج إلى متابعة",
  "View all": "عرض الكل",
  "Alarms needing attention": "الإنذارات التي تحتاج إلى متابعة",
  "All caught up": "اكتملت المتابعة",
  "All demo alarms are acknowledged.": "تم الإقرار بجميع الإنذارات التجريبية.",
  "Treatment process": "مراحل المعالجة",
  "Train 01 · Select a stage to inspect its equipment":
    "خط المعالجة 01 · اختر مرحلة لعرض معداتها",
  Intake: "السحب",
  Filtration: "الترشيح",
  Storage: "التخزين",
  Distribution: "التوزيع",
  Inspect: "عرض التفاصيل",
  "Intake pump": "مضخة السحب",
  "Standby pump": "المضخة الاحتياطية",
  "Sand filtration": "الترشيح الرملي",
  "Clearwater tank": "خزان المياه المعالجة",
  "Distribution pump": "مضخة التوزيع",
  "Remote telemetry": "القياس عن بُعد",
  "Flow rate": "معدل التدفق",
  "Differential pressure": "فرق الضغط",
  Vibration: "الاهتزاز",
  "Response time": "زمن الاستجابة",
  "Power demand": "الطلب على الطاقة",
  "Filter pressure": "ضغط المرشح",
  "Asset health": "حالة المعدات",
  "Equipment registry": "سجل المعدات",
  "Filter equipment and inspect live signal details.":
    "صفِّ المعدات واستعرض تفاصيل الإشارات الحالية.",
  "Current state across the treatment train":
    "الحالة الحالية على امتداد خط المعالجة",
  "All assets": "جميع المعدات",
  "Filter assets": "تصفية المعدات",
  "Process area": "منطقة العملية",
  "All areas": "جميع المناطق",
  "Equipment health": "سلامة المعدات",
  Equipment: "المعدات",
  Area: "المنطقة",
  Status: "الحالة",
  Reading: "القراءة",
  Health: "السلامة",
  Details: "التفاصيل",
  "No matching assets": "لا توجد معدات مطابقة",
  "Try another name, tag, or process area.":
    "جرّب اسماً أو معرّف إشارة أو منطقة أخرى.",
  "No data": "لا توجد بيانات",
  "Equipment status, signals, and process health.":
    "حالة المعدات والإشارات وسلامة العمليات.",
  "Alarm center": "مركز الإنذارات",
  "Review, investigate, and acknowledge events in this demo workspace.":
    "راجع الأحداث واستقصِ أسبابها وأقرّ بمتابعتها في مساحة العمل التجريبية.",
  "Export alarms": "تصدير الإنذارات",
  Unacknowledged: "بانتظار الإقرار",
  "Alarm filters": "مرشحات الإنذارات",
  All: "الكل",
  Acknowledgment: "الإقرار",
  "All events": "جميع الأحداث",
  Acknowledge: "إقرار",
  "Acknowledge alarm": "الإقرار بالإنذار",
  "Acknowledged in this session": "تم الإقرار في هذه الجلسة",
  "High vibration detected": "تم رصد اهتزاز مرتفع",
  "Communication timeout": "انتهت مهلة الاتصال",
  "Filter pressure rising": "ارتفاع ضغط المرشح",
  "Duty cycle completed": "اكتملت دورة التشغيل",
  "No response after 3 polling attempts":
    "لا توجد استجابة بعد ٣ محاولات استعلام",
  "Standby pump ready for rotation": "المضخة الاحتياطية جاهزة للتناوب",
  "8.4 mm/s · limit 7.1 mm/s": "8.4 مم/ث · الحد 7.1 مم/ث",
  "2.8 bar · advisory limit 2.5 bar": "2.8 بار · حد التنبيه 2.5 بار",
  "Process trends": "اتجاهات العملية",
  "Compare process signals over the selected time window.":
    "قارن إشارات العملية خلال الفترة الزمنية المحددة.",
  "Download CSV": "تنزيل CSV",
  "Process signal": "إشارة العملية",
  "Process historian": "سجل العملية",
  "Select a signal and inspect its simulated history.":
    "اختر إشارة لاستعراض سجلها المحاكى.",
  "All observations are simulated. Drag on the plot or use its range slider to zoom; double-click the plot to reset. Download CSV to inspect every observation as text.":
    "جميع القراءات محاكاة. اسحب على الرسم أو استخدم شريط النطاق للتكبير، وانقر مرتين لإعادة الضبط. نزّل CSV لعرض جميع القراءات نصياً.",
  "Workspace settings": "إعدادات مساحة العمل",
  "Tune your monitoring experience and explore account security.":
    "خصّص تجربة المراقبة واستعرض أمان الحساب.",
  "Appearance & monitoring": "المظهر والمراقبة",
  "Appearance and monitoring preferences": "تفضيلات المظهر والمراقبة",
  "Apply the theme across every component.": "تطبيق المظهر على جميع المكوّنات.",
  "Simulated live updates": "تحديثات المحاكاة المباشرة",
  "Refresh sample values every four seconds.":
    "تحديث قيم العينات كل أربع ثوانٍ.",
  "Account & security": "الحساب والأمان",
  "Account and security": "الحساب والأمان",
  "Guest demo session": "جلسة ضيف تجريبية",
  "Sign in to explore the verification flow.":
    "سجّل الدخول لاستعراض خطوات التحقق.",
  "Multi-factor authentication": "المصادقة متعددة العوامل",
  "Demo verification completed.": "اكتمل التحقق التجريبي.",
  "Six-digit code with a recovery-code alternative.":
    "رمز من ست خانات مع خيار رمز الاسترداد.",
  "Demo environment": "بيئة تجريبية",
  "North water treatment is a fictional plant. Values and alarms are simulated; acknowledgments affect this page only. Reloading restores the original alarm set.":
    "محطة معالجة المياه الشمالية منشأة افتراضية. القيم والإنذارات محاكاة، والإقرار يؤثر في هذه الصفحة فقط. تعيد إعادة التحميل الإنذارات الأصلية.",
  "Reset demo alarms": "إعادة ضبط الإنذارات التجريبية",
  "Reset demo alarms?": "هل تريد إعادة ضبط الإنذارات التجريبية؟",
  "This restores the four sample alarms and removes acknowledgment notes from this page.":
    "سيُعاد ضبط الإنذارات التجريبية الأربعة وتُحذف ملاحظات الإقرار من هذه الصفحة.",
  "Powered by AWC UI": "يعمل بمكتبة AWC UI",
  "Built with AWC UI": "تم إنشاؤه باستخدام AWC UI",
  "Explore components": "استعراض المكوّنات",
  "Explore the components behind the workspace, from data visualization to form validation and modal interactions.":
    "استعرض مكوّنات مساحة العمل، من عرض البيانات إلى التحقق من النماذج والنوافذ الحوارية.",
  "Authentication is a UI demonstration. It does not create a real account or protect plant data. Passwords and verification codes are never saved; demo profile details remain in this tab until you sign out or close it.":
    "المصادقة عرض تجريبي للواجهة، ولا تنشئ حساباً حقيقياً أو تحمي بيانات المحطة. لا تُحفظ كلمات المرور أو رموز التحقق، وتبقى تفاصيل الملف التجريبي في هذا التبويب حتى تسجيل الخروج أو إغلاقه.",
  "Make it yours": "خصّص تجربتك",
  "Choose your colors and the layout that works for you. Changes apply across the app and are saved on this device.":
    "اختر الألوان والتخطيط المناسبين لك. تُطبّق التغييرات على التطبيق وتُحفظ على هذا الجهاز.",
  "Primary color": "اللون الأساسي",
  "Pick a color. Matching light and dark tones keep your workspace readable.":
    "اختر لوناً لتوليد درجات متناسقة للمظهرين الفاتح والداكن تحافظ على وضوح المحتوى.",
  Language: "اللغة",
  "Choose the app language. Arabic starts in right-to-left layout.":
    "اختر لغة التطبيق. تُفعّل العربية التخطيط من اليمين إلى اليسار.",
  Density: "كثافة العرض",
  "Adjust the spacing of library components.":
    "اضبط المسافات بين مكوّنات الواجهة.",
  Comfortable: "مريحة",
  Cozy: "متوازنة",
  Compact: "مضغوطة",
  Dense: "كثيفة",
  "Extra dense": "شديدة الكثافة",
  "Theme and direction": "المظهر والاتجاه",
  "Dark theme": "المظهر الداكن",
  "Right-to-left layout": "تخطيط من اليمين إلى اليسار",
  "Mirror the workspace direction.": "اعكس اتجاه مساحة العمل.",
  "Reset defaults": "استعادة الإعدادات الافتراضية",
  Done: "تم",
  "Equipment details": "تفاصيل المعدات",
  "Signal tag": "معرّف الإشارة",
  Protocol: "البروتوكول",
  "Demo address": "عنوان تجريبي",
  "Data quality": "جودة البيانات",
  "Bad · offline": "رديئة · غير متصل",
  "Good · simulated": "جيدة · محاكاة",
  "Read-only monitoring · simulated equipment":
    "مراقبة للقراءة فقط · معدات محاكاة",
  "Open alarm queue": "فتح قائمة الإنذارات",
  "Operator note (optional)": "ملاحظة المشغّل (اختيارية)",
  "Duty pump supplying the treatment train.":
    "مضخة التشغيل التي تغذّي خط المعالجة.",
  "Available for the next duty rotation.": "متاحة لدورة التشغيل التالية.",
  "Differential pressure is above the 2.5 bar advisory limit.":
    "فرق الضغط أعلى من حد التنبيه البالغ 2.5 بار.",
  "Clearwater storage level remains within the 30–90% operating band.":
    "مستوى خزان المياه المعالجة ضمن نطاق التشغيل من ٣٠ إلى ٩٠٪.",
  "Vibration exceeds the 7.1 mm/s demo threshold. Inspect the bearing assembly.":
    "يتجاوز الاهتزاز الحد التجريبي البالغ 7.1 مم/ث. افحص مجموعة المحامل.",
  "No recent sample. The last valid observation is retained in the historian.":
    "لا توجد عينة حديثة. تُحفظ آخر قراءة صالحة في سجل العملية.",
  "No current telemetry. This signal is offline.":
    "لا توجد بيانات قياس حالية. هذه الإشارة غير متصلة.",
  "Simulated telemetry · North water treatment · UTC":
    "قياسات محاكاة · محطة معالجة المياه الشمالية · UTC",
  "Skip to monitoring": "الانتقال إلى المراقبة",
  "SCADA SYSTEMS": "أنظمة سكادا",
  "Advisory limit": "حد التنبيه",
  "Simulation resumed.": "تم استئناف المحاكاة.",
  "Simulation paused.": "تم إيقاف المحاكاة مؤقتاً.",
  "Appearance restored to defaults.": "تمت استعادة إعدادات المظهر الافتراضية.",
  "Alarm acknowledged in this demo session.":
    "تم الإقرار بالإنذار في هذه الجلسة التجريبية.",
  "Signed out of the demo session.": "تم تسجيل الخروج من الجلسة التجريبية.",
  "Demo alarms restored.": "تمت استعادة الإنذارات التجريبية.",
  "CSV downloaded with simulated data.": "تم تنزيل ملف CSV ببيانات المحاكاة.",
  "The AWC UI toolkit": "مجموعة أدوات AWC UI",
  Navigation: "التنقل",
  "Operational data": "البيانات التشغيلية",
  "Charts & health": "الرسوم البيانية والسلامة",
  "Forms & identity": "النماذج والهوية",
  "Controls & feedback": "عناصر التحكم والتغذية الراجعة",
  Surfaces: "الحاويات",
  "Loading workspace": "جارٍ تحميل مساحة العمل",
  "Loading equipment": "جارٍ تحميل المعدات",
  "Loading equipment details": "جارٍ تحميل تفاصيل المعدات",
  "Loading chart…": "جارٍ تحميل الرسم البياني…",
  "Signing in…": "جارٍ تسجيل الدخول…",
  "Creating demo profile…": "جارٍ إنشاء الملف التجريبي…",
  "Verifying code…": "جارٍ التحقق من الرمز…",
  "Verifying recovery code…": "جارٍ التحقق من رمز الاسترداد…",
  "Preparing CSV…": "جارٍ تجهيز ملف CSV…",
  "Acknowledging alarm…": "جارٍ الإقرار بالإنذار…",
  "Restoring demo alarms…": "جارٍ استعادة الإنذارات التجريبية…",
  "Signing out…": "جارٍ تسجيل الخروج…",
  "CSV is ready. Download started.": "ملف CSV جاهز. بدأ التنزيل.",
  "The action could not be completed. Please try again.":
    "تعذّر إكمال الإجراء. يُرجى المحاولة مرة أخرى.",
  "The chart could not be loaded. Please try again.":
    "تعذّر تحميل الرسم البياني. يُرجى المحاولة مرة أخرى.",
  "Equipment details could not be loaded. Please try again.":
    "تعذّر تحميل تفاصيل المعدات. يُرجى المحاولة مرة أخرى.",
};
