/* eslint-disable */
/**
 * GENERATED FILE — do not edit by hand.
 *
 * Produced by `scripts/generate-seeds.mjs` from `@awc-ui/theme`'s computeTheme.
 * Each preset is a complete pair of :root / [data-theme="dark"] --md-sys-color-*
 * overrides. The `default` preset carries no CSS: it is the token sheet as shipped.
 */

export interface SeedPreset {
  /** Stable id — the value written to the `seed` URL param and localStorage. */
  id: string;
  /** Seed colour, for the dock's swatch. */
  seed: string;
  /** i18n key for the preset's name. */
  labelKey: string;
  /** Complete override sheet, or '' for the default palette. */
  css: string;
}

export const SEED_PRESETS: readonly SeedPreset[] = [
  {
    "id": "default",
    "seed": "#6750A4",
    "labelKey": "dock.accent.default",
    "css": ""
  },
  {
    "id": "azure",
    "seed": "#1A56DB",
    "labelKey": "dock.accent.azure",
    "css": ":root{--md-sys-color-primary:#1353D8;--md-sys-color-on-primary:#FFFFFF;--md-sys-color-primary-container:#DBE1FF;--md-sys-color-on-primary-container:#003DAB;--md-sys-color-inverse-primary:#B5C4FF;--md-sys-color-secondary:#595E72;--md-sys-color-on-secondary:#FFFFFF;--md-sys-color-secondary-container:#DDE1F9;--md-sys-color-on-secondary-container:#414659;--md-sys-color-tertiary:#745470;--md-sys-color-on-tertiary:#FFFFFF;--md-sys-color-tertiary-container:#FFD6F7;--md-sys-color-on-tertiary-container:#5B3D58;--md-sys-color-error:#BA1A1A;--md-sys-color-on-error:#FFFFFF;--md-sys-color-error-container:#FFDAD6;--md-sys-color-on-error-container:#93000A;--md-sys-color-background:#FBF8FD;--md-sys-color-on-background:#1B1B1F;--md-sys-color-surface:#FBF8FD;--md-sys-color-on-surface:#1B1B1F;--md-sys-color-surface-variant:#E2E1EC;--md-sys-color-on-surface-variant:#45464F;--md-sys-color-surface-container-lowest:#FFFFFF;--md-sys-color-surface-container-low:#F5F3F7;--md-sys-color-surface-container:#EFEDF1;--md-sys-color-surface-container-high:#EAE7EC;--md-sys-color-surface-container-highest:#E4E2E6;--md-sys-color-surface-dim:#DBD9DE;--md-sys-color-surface-bright:#FBF8FD;--md-sys-color-outline:#767680;--md-sys-color-outline-variant:#C6C6D0;--md-sys-color-inverse-surface:#303034;--md-sys-color-inverse-on-surface:#F2F0F4;--md-sys-color-shadow:#000000;--md-sys-color-scrim:#000000;--md-sys-color-surface-tint:#1353D8}[data-theme=\"dark\"]{--md-sys-color-primary:#B5C4FF;--md-sys-color-on-primary:#00297A;--md-sys-color-primary-container:#003DAB;--md-sys-color-on-primary-container:#DBE1FF;--md-sys-color-inverse-primary:#1353D8;--md-sys-color-secondary:#C1C5DD;--md-sys-color-on-secondary:#2B3042;--md-sys-color-secondary-container:#414659;--md-sys-color-on-secondary-container:#DDE1F9;--md-sys-color-tertiary:#E2BBDB;--md-sys-color-on-tertiary:#422740;--md-sys-color-tertiary-container:#5B3D58;--md-sys-color-on-tertiary-container:#FFD6F7;--md-sys-color-error:#FFB4AB;--md-sys-color-on-error:#690005;--md-sys-color-error-container:#93000A;--md-sys-color-on-error-container:#FFDAD6;--md-sys-color-background:#131316;--md-sys-color-on-background:#E4E2E6;--md-sys-color-surface:#131316;--md-sys-color-on-surface:#E4E2E6;--md-sys-color-surface-variant:#45464F;--md-sys-color-on-surface-variant:#C6C6D0;--md-sys-color-surface-container-lowest:#0D0E11;--md-sys-color-surface-container-low:#1B1B1F;--md-sys-color-surface-container:#1F1F23;--md-sys-color-surface-container-high:#292A2D;--md-sys-color-surface-container-highest:#343438;--md-sys-color-surface-dim:#131316;--md-sys-color-surface-bright:#39393C;--md-sys-color-outline:#8F909A;--md-sys-color-outline-variant:#45464F;--md-sys-color-inverse-surface:#E4E2E6;--md-sys-color-inverse-on-surface:#303034;--md-sys-color-shadow:#000000;--md-sys-color-scrim:#000000;--md-sys-color-surface-tint:#B5C4FF}"
  },
  {
    "id": "evergreen",
    "seed": "#00796B",
    "labelKey": "dock.accent.evergreen",
    "css": ":root{--md-sys-color-primary:#006B5E;--md-sys-color-on-primary:#FFFFFF;--md-sys-color-primary-container:#97F3E2;--md-sys-color-on-primary-container:#005047;--md-sys-color-inverse-primary:#7AD7C6;--md-sys-color-secondary:#4A635E;--md-sys-color-on-secondary:#FFFFFF;--md-sys-color-secondary-container:#CDE8E1;--md-sys-color-on-secondary-container:#334B46;--md-sys-color-tertiary:#446179;--md-sys-color-on-tertiary:#FFFFFF;--md-sys-color-tertiary-container:#CAE6FF;--md-sys-color-on-tertiary-container:#2C4A60;--md-sys-color-error:#BA1A1A;--md-sys-color-on-error:#FFFFFF;--md-sys-color-error-container:#FFDAD6;--md-sys-color-on-error-container:#93000A;--md-sys-color-background:#F7FAF8;--md-sys-color-on-background:#191C1B;--md-sys-color-surface:#F7FAF8;--md-sys-color-on-surface:#191C1B;--md-sys-color-surface-variant:#DAE5E1;--md-sys-color-on-surface-variant:#3F4946;--md-sys-color-surface-container-lowest:#FFFFFF;--md-sys-color-surface-container-low:#F2F4F2;--md-sys-color-surface-container:#ECEEEC;--md-sys-color-surface-container-high:#E6E9E7;--md-sys-color-surface-container-highest:#E0E3E1;--md-sys-color-surface-dim:#D8DBD8;--md-sys-color-surface-bright:#F7FAF8;--md-sys-color-outline:#6F7976;--md-sys-color-outline-variant:#BEC9C5;--md-sys-color-inverse-surface:#2D3130;--md-sys-color-inverse-on-surface:#EFF1EF;--md-sys-color-shadow:#000000;--md-sys-color-scrim:#000000;--md-sys-color-surface-tint:#006B5E}[data-theme=\"dark\"]{--md-sys-color-primary:#7AD7C6;--md-sys-color-on-primary:#003730;--md-sys-color-primary-container:#005047;--md-sys-color-on-primary-container:#97F3E2;--md-sys-color-inverse-primary:#006B5E;--md-sys-color-secondary:#B1CCC5;--md-sys-color-on-secondary:#1C3530;--md-sys-color-secondary-container:#334B46;--md-sys-color-on-secondary-container:#CDE8E1;--md-sys-color-tertiary:#ACCAE5;--md-sys-color-on-tertiary:#133348;--md-sys-color-tertiary-container:#2C4A60;--md-sys-color-on-tertiary-container:#CAE6FF;--md-sys-color-error:#FFB4AB;--md-sys-color-on-error:#690005;--md-sys-color-error-container:#93000A;--md-sys-color-on-error-container:#FFDAD6;--md-sys-color-background:#101413;--md-sys-color-on-background:#E0E3E1;--md-sys-color-surface:#101413;--md-sys-color-on-surface:#E0E3E1;--md-sys-color-surface-variant:#3F4946;--md-sys-color-on-surface-variant:#BEC9C5;--md-sys-color-surface-container-lowest:#0B0F0E;--md-sys-color-surface-container-low:#191C1B;--md-sys-color-surface-container:#1D201F;--md-sys-color-surface-container-high:#272B2A;--md-sys-color-surface-container-highest:#323534;--md-sys-color-surface-dim:#101413;--md-sys-color-surface-bright:#363A39;--md-sys-color-outline:#899390;--md-sys-color-outline-variant:#3F4946;--md-sys-color-inverse-surface:#E0E3E1;--md-sys-color-inverse-on-surface:#2D3130;--md-sys-color-shadow:#000000;--md-sys-color-scrim:#000000;--md-sys-color-surface-tint:#7AD7C6}"
  },
  {
    "id": "bronze",
    "seed": "#C2410C",
    "labelKey": "dock.accent.bronze",
    "css": ":root{--md-sys-color-primary:#AC3400;--md-sys-color-on-primary:#FFFFFF;--md-sys-color-primary-container:#FFDBD0;--md-sys-color-on-primary-container:#832600;--md-sys-color-inverse-primary:#FFB59D;--md-sys-color-secondary:#77574D;--md-sys-color-on-secondary:#FFFFFF;--md-sys-color-secondary-container:#FFDBD0;--md-sys-color-on-secondary-container:#5D4036;--md-sys-color-tertiary:#6A5E2F;--md-sys-color-on-tertiary:#FFFFFF;--md-sys-color-tertiary-container:#F4E2A7;--md-sys-color-on-tertiary-container:#51461A;--md-sys-color-error:#BA1A1A;--md-sys-color-on-error:#FFFFFF;--md-sys-color-error-container:#FFDAD6;--md-sys-color-on-error-container:#93000A;--md-sys-color-background:#FFF8F6;--md-sys-color-on-background:#201A18;--md-sys-color-surface:#FFF8F6;--md-sys-color-on-surface:#201A18;--md-sys-color-surface-variant:#F5DED7;--md-sys-color-on-surface-variant:#53433F;--md-sys-color-surface-container-lowest:#FFFFFF;--md-sys-color-surface-container-low:#FEF1ED;--md-sys-color-surface-container:#F8EBE7;--md-sys-color-surface-container-high:#F3E5E2;--md-sys-color-surface-container-highest:#EDE0DC;--md-sys-color-surface-dim:#E4D7D4;--md-sys-color-surface-bright:#FFF8F6;--md-sys-color-outline:#85736E;--md-sys-color-outline-variant:#D8C2BB;--md-sys-color-inverse-surface:#362F2D;--md-sys-color-inverse-on-surface:#FBEEEA;--md-sys-color-shadow:#000000;--md-sys-color-scrim:#000000;--md-sys-color-surface-tint:#AC3400}[data-theme=\"dark\"]{--md-sys-color-primary:#FFB59D;--md-sys-color-on-primary:#5D1800;--md-sys-color-primary-container:#832600;--md-sys-color-on-primary-container:#FFDBD0;--md-sys-color-inverse-primary:#AC3400;--md-sys-color-secondary:#E7BDB1;--md-sys-color-on-secondary:#442A21;--md-sys-color-secondary-container:#5D4036;--md-sys-color-on-secondary-container:#FFDBD0;--md-sys-color-tertiary:#D7C68D;--md-sys-color-on-tertiary:#3A3005;--md-sys-color-tertiary-container:#51461A;--md-sys-color-on-tertiary-container:#F4E2A7;--md-sys-color-error:#FFB4AB;--md-sys-color-on-error:#690005;--md-sys-color-error-container:#93000A;--md-sys-color-on-error-container:#FFDAD6;--md-sys-color-background:#181210;--md-sys-color-on-background:#EDE0DC;--md-sys-color-surface:#181210;--md-sys-color-on-surface:#EDE0DC;--md-sys-color-surface-variant:#53433F;--md-sys-color-on-surface-variant:#D8C2BB;--md-sys-color-surface-container-lowest:#120D0B;--md-sys-color-surface-container-low:#201A18;--md-sys-color-surface-container:#251E1C;--md-sys-color-surface-container-high:#2F2826;--md-sys-color-surface-container-highest:#3B3331;--md-sys-color-surface-dim:#181210;--md-sys-color-surface-bright:#3F3835;--md-sys-color-outline:#A08D87;--md-sys-color-outline-variant:#53433F;--md-sys-color-inverse-surface:#EDE0DC;--md-sys-color-inverse-on-surface:#362F2D;--md-sys-color-shadow:#000000;--md-sys-color-scrim:#000000;--md-sys-color-surface-tint:#FFB59D}"
  }
];

export const DEFAULT_SEED_PRESET = 'default';
