import type { StorybookConfig } from '@storybook/web-components-vite';
import { stencilLoaderStabilityPlugin, stencilDistRestartPlugin } from './stencil-loader-stability.ts';
const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  // SB9+: actions/controls/viewport/interactions are built into core; docs and
  // a11y are the only essentials that remain opt-in addons.
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-a11y',
    'storybook-addon-pseudo-states',
    // Runs every story's play() as a Vitest browser test, replacing
    // @storybook/test-runner. The runner required jest 30 while @awc-ui/core's
    // spec suite pins jest 29, and the two cannot both be the hoisted root — so
    // the runner could not start at all. Vitest removes jest from the Storybook
    // side entirely and dissolves that conflict.
    //
    // Only the sidebar widget comes from this entry. The story-as-test
    // machinery is independent: vitest.config.mts imports `storybookTest` from
    // '@storybook/addon-vitest/vitest-plugin' itself, so `pnpm test:stories` /
    // `test:a11y` and CI keep working with or without this line.
    '@storybook/addon-vitest',
  ],
  framework: {
    name: '@storybook/web-components-vite',
    options: {},
  },
  /**
   * Library coverage lives at /library-coverage/ — generated by
   * `pnpm test:coverage`, which drives the stories in a real browser and remaps
   * V8 onto packages/core/src with monocart.
   *
   * NOT at /coverage/. That URL belongs to the Vitest addon, which regenerates
   * its own istanbul report there whenever its Coverage checkbox is ticked —
   * measuring apps/storybook (the TEST HARNESS), not the components. It cannot
   * be switched off from vitest.config (the addon's own settings win) and it
   * cannot be intercepted from a Vite plugin (its route is registered above the
   * Vite middleware chain — tried, including enforce: 'pre'). So the honest fix
   * is a separate, clearly-named URL, and hiding that checkbox row — see
   * .storybook/addons/library-coverage/register.tsx.
   */
  staticDirs: [
    { from: '../coverage-stories', to: '/library-coverage' },
    /*
     * Copied to the output ROOT so `favicon.svg` overwrites the one Storybook
     * ships. `manager-head.html` also injects a data-URI icon, which is what the
     * dev server serves — but a BUILT manager still emits its own
     * `<link rel="icon" href="./favicon.svg">`, so without this the published
     * Storybook came out wearing Storybook's own mark instead of AWC UI's.
     */
    { from: './static', to: '/' },
  ],
  viteFinal(config) {
    config.plugins ??= [];
    config.plugins.push(stencilLoaderStabilityPlugin());
    config.plugins.push(stencilDistRestartPlugin());

    config.optimizeDeps ??= {};
    config.optimizeDeps.exclude ??= [];
    config.optimizeDeps.exclude.push('@awc-ui/core');

    // Stencil watch rebuilds briefly remove dist/esm/loader.js while regenerating
    // output. Ignore the dist root during file-watch to avoid HMR fetching a half-
    // written loader, but allow Vite to re-fetch component entry chunks once the
    // *.entry.js files settle — otherwise Storybook keeps serving a stale pre-
    // bundled md-list-item (with old ResizeObserver / md-tooltip truncation code)
    // long after Stencil has rebuilt.
    config.server ??= {};
    config.server.watch ??= {};
    const ignored = config.server.watch.ignored;
    const ignoreList = Array.isArray(ignored)
      ? [...ignored]
      : ignored
        ? [ignored]
        : [];
    // NB: loader.js / index*.js were previously ignored here "for stability",
    // but pinning their cached transforms while entry chunks refresh created
    // TWO live Stencil runtimes after any watch rebuild that rotated the
    // runtime chunk hash — every shadow root rendered empty
    // (createElementNS('[object Object]')). The stencil-loader-stability
    // plugin already guards the mid-rebuild deletion window, so the globs are
    // gone for good.
    config.server.watch.ignored = ignoreList;

    return config;
  },
};

export default config;
