import { existsSync } from 'node:fs';
import { readdir, copyFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { StorybookConfig } from '@storybook/web-components-vite';
import { stencilLoaderStabilityPlugin, stencilDistRestartPlugin } from './stencil-loader-stability.ts';

/**
 * Stencil's lazy loader fetches per-component entry chunks at runtime via
 * URLs constructed from import.meta.url — invisible to Rollup, so a static
 * build bundles the loader but emits NONE of the chunks it will request:
 * every component 404s (md-button_7.entry.js …) in a deployed Storybook,
 * while the dev server keeps working because it serves node_modules
 * directly. Copying the chunks next to the BUNDLED loader is not enough
 * either: the copied entries import the copied runtime chunk while
 * registration lives in the bundled one — two live runtimes, and every
 * shadow root renders empty (see the watch-ignore note below for the same
 * failure mode in dev).
 *
 * So for builds the runtime is not bundled at all: define-shim.ts (aliased
 * over @awc-ui/core/define in viteFinal) loads the COPIED lazy output at
 * runtime — one runtime, whose entry fetches resolve inside its own
 * directory. This plugin ships that directory: dist/esm plus the md3 token
 * sheet, under assets/awc-esm/.
 */
function copyStencilLazyRuntime() {
  return {
    name: 'awc-copy-stencil-lazy-runtime',
    apply: 'build' as const,
    async writeBundle(options: { dir?: string }) {
      const coreDist = fileURLToPath(new URL('../../../packages/core/dist', import.meta.url));
      const outDir = join(options.dir ?? '', 'assets', 'awc-esm');
      if (!existsSync(join(coreDist, 'esm')) || !existsSync(join(options.dir ?? '', 'assets'))) return;
      await mkdir(outDir, { recursive: true });
      const files = (await readdir(join(coreDist, 'esm'))).filter((f) => f.endsWith('.js'));
      await Promise.all(files.map((f) => copyFile(join(coreDist, 'esm', f), join(outDir, f))));
      await copyFile(join(coreDist, 'md3', 'md3.css'), join(outDir, 'md3.css'));
    },
  };
}

// ../coverage-stories only exists after `pnpm test:coverage` has run, and
// Storybook hard-fails on a missing staticDirs entry — so a fresh checkout
// (CI's storybook-build job) must not list it. Without it,
// /library-coverage/ simply 404s until a coverage sweep has produced it.
const coverageStoriesDir = fileURLToPath(new URL('../coverage-stories', import.meta.url));

const config: StorybookConfig = {
  stories: ['../src/**/*.stories.@(js|jsx|ts|tsx|mdx)'],
  // SB9+: actions/controls/viewport/interactions are built into core; docs and
  // a11y are the only essentials that remain opt-in addons.
  addons: [
    '@storybook/addon-docs',
    '@storybook/addon-a11y',
    'storybook-addon-pseudo-states',
    // Runs every story's play() as a Vitest browser test, replacing
    // @storybook/test-runner. The runner required jest 30 while @awc-ui/core's
    // spec suite pins jest 29, and the two cannot both be the hoisted root — so
    // the runner could not start at all. Vitest removes jest from the Storybook
    // side entirely and dissolves that conflict.
    //
    // Only the sidebar widget comes from this entry. The story-as-test
    // machinery is independent: vitest.config.mts imports `storybookTest` from
    // '@storybook/addon-vitest/vitest-plugin' itself, so `pnpm test:stories` /
    // `test:a11y` and CI keep working with or without this line.
    '@storybook/addon-vitest',
  ],
  framework: {
    name: '@storybook/web-components-vite',
    options: {},
  },
  /**
   * Library coverage lives at /library-coverage/ — generated by
   * `pnpm test:coverage`, which drives the stories in a real browser and remaps
   * V8 onto packages/core/src with monocart.
   *
   * NOT at /coverage/. That URL belongs to the Vitest addon, which regenerates
   * its own istanbul report there whenever its Coverage checkbox is ticked —
   * measuring apps/storybook (the TEST HARNESS), not the components. It cannot
   * be switched off from vitest.config (the addon's own settings win) and it
   * cannot be intercepted from a Vite plugin (its route is registered above the
   * Vite middleware chain — tried, including enforce: 'pre'). So the honest fix
   * is a separate, clearly-named URL, and hiding that checkbox row — see
   * .storybook/addons/library-coverage/register.tsx.
   */
  staticDirs: [
    ...(existsSync(coverageStoriesDir)
      ? [{ from: '../coverage-stories', to: '/library-coverage' }]
      : []),
    /*
     * Copied to the output ROOT so `favicon.svg` overwrites the one Storybook
     * ships. `manager-head.html` also injects a data-URI icon, which is what the
     * dev server serves — but a BUILT manager still emits its own
     * `<link rel="icon" href="./favicon.svg">`, so without this the published
     * Storybook came out wearing Storybook's own mark instead of AWC UI's.
     */
    { from: './static', to: '/' },
  ],
  viteFinal(config, { configType }) {
    config.plugins ??= [];
    config.plugins.push(stencilLoaderStabilityPlugin());
    config.plugins.push(stencilDistRestartPlugin());

    if (configType === 'PRODUCTION') {
      config.plugins.push(copyStencilLazyRuntime());
      // Swap the lazy-loader entry for the runtime-loading shim — see the
      // comments on copyStencilLazyRuntime()/define-shim.ts.
      config.resolve ??= {};
      const alias = config.resolve.alias;
      const shim = {
        find: '@awc-ui/core/define',
        replacement: fileURLToPath(new URL('./define-shim.ts', import.meta.url)),
      };
      config.resolve.alias = Array.isArray(alias) ? [...alias, shim] : { ...(alias ?? {}), [shim.find]: shim.replacement };
    }

    config.optimizeDeps ??= {};
    config.optimizeDeps.exclude ??= [];
    config.optimizeDeps.exclude.push('@awc-ui/core');

    // Stencil watch rebuilds briefly remove dist/esm/loader.js while regenerating
    // output. Ignore the dist root during file-watch to avoid HMR fetching a half-
    // written loader, but allow Vite to re-fetch component entry chunks once the
    // *.entry.js files settle — otherwise Storybook keeps serving a stale pre-
    // bundled md-list-item (with old ResizeObserver / md-tooltip truncation code)
    // long after Stencil has rebuilt.
    config.server ??= {};
    config.server.watch ??= {};
    const ignored = config.server.watch.ignored;
    const ignoreList = Array.isArray(ignored)
      ? [...ignored]
      : ignored
        ? [ignored]
        : [];
    // NB: loader.js / index*.js were previously ignored here "for stability",
    // but pinning their cached transforms while entry chunks refresh created
    // TWO live Stencil runtimes after any watch rebuild that rotated the
    // runtime chunk hash — every shadow root rendered empty
    // (createElementNS('[object Object]')). The stencil-loader-stability
    // plugin already guards the mid-rebuild deletion window, so the globs are
    // gone for good.
    config.server.watch.ignored = ignoreList;

    return config;
  },
};

export default config;
