<script lang="ts">
import {pictorSearchText} from '@awc-ui/pictor-model';

import {getAssets} from '@awc-ui/showcase-kit/design';
import {createLayer,layerFromAsset,LIVE_COMPONENTS,ORB_ART,WAVE_ART,LANDSCAPE_ART,DEFAULT_SWATCHES} from '@awc-ui/pictor-model';
import PanelTabs from '$lib/editor/PanelTabs.svelte';
import TextControl from '$lib/editor/TextControl.svelte';
import {document} from '$lib/document'; import {t} from '$lib/showcase'; import {navigate} from '$lib/router'; import Link from '$lib/components/Link.svelte';
export let category: any = 'components';
let tab: any = category; const setTab = (value: any) => tab = typeof value === "function" ? value(tab) : value;
$: tab = category;
let query: any = ''; const setQuery = (value: any) => query = typeof value === "function" ? value(query) : value;
$: assets = (() => getAssets().filter(asset => asset.name.toLowerCase().includes(query.toLowerCase())))();
$: insert = (layer: ReturnType<typeof createLayer>) => { $document.commitLayers('create', layers => [...layers, layer], [layer.id]); $document.setTool('select'); };
$: searchMetadata = (item: {name:string;description?:string}) => pictorSearchText([item.name, $t(item.name), item.description ?? '', $t(item.description ?? '')].join(' ')).includes(pictorSearchText(query));
</script>
<div class="studio-insert" data-insert-panel><div class="studio-panel-heading"><span class="material-symbols-outlined" aria-hidden="true">add_circle</span><div><h3>{$t('Your creative toolkit')}</h3><p>{$t('Click anything to make it yours.')}</p></div></div><TextControl live label={$t('Search assets')} value={query} onValue={setQuery}></TextControl><PanelTabs label={$t('Asset type')} value={tab} onValue={setTab} options={[{ value: 'components', label: $t('Live UI') }, { value: 'art', label: $t('Artwork') }, { value: 'color', label: $t('Color') }]}></PanelTabs> {#if tab === 'components'}<div class="studio-callout"><span class="material-symbols-outlined" aria-hidden="true">touch_app</span><p>{$t('Real AWC components. Add one, then enter Present to interact with it.')}</p></div><div class="studio-insert-grid">{#each LIVE_COMPONENTS.filter(searchMetadata) as item}<button class="studio-insert-item" data-insert-component={item.id} on:click={() => insert(createLayer('component', { x: 16, y: 12, w: item.id === 'awc:card' ? 17 : 15, h: item.id === 'awc:card' ? 14 : 5 }, { name: item.name, componentId: item.id, fill: '#BEE7AA' }))}><span class="studio-insert-item__icon material-symbols-outlined" aria-hidden="true">{item.icon}</span><strong>{$t(item.name)}</strong><span>{$t(item.description)}</span><span class="studio-insert-item__plus material-symbols-outlined" aria-hidden="true">add</span></button>{/each}</div>{:else}{#if tab === 'art'}<div class="studio-art-grid">{#each [{ name: 'Orbital sculpture', art: ORB_ART }, { name: 'Electric ribbon', art: WAVE_ART }, { name: 'New horizons', art: LANDSCAPE_ART }].filter(searchMetadata) as item}<button on:click={() => insert(createLayer('image', { x: 14, y: 6, w: 20, h: 20 }, { name: item.name, art: item.art, fill: null }))}><img src={item.art.src} alt="" /><span>{$t(item.name)}</span></button>{/each}</div><p class="studio-label">{$t('FROM YOUR LIBRARY')}</p><div class="studio-art-grid">{#each assets.filter(asset => asset.art).slice(0, 18) as asset}<button on:click={() => insert(layerFromAsset(asset))}><img src={asset.art.src} alt="" loading="lazy" /><span>{asset.name}</span></button>{/each}</div>{:else}<p class="studio-description">{$t('A curated palette for your next composition. Add a color shape, then make it your own in the inspector.')}</p><div class="studio-color-grid">{#each DEFAULT_SWATCHES.filter(color => color.toLowerCase().includes(query.toLowerCase())) as color}<button aria-label={$t('Insert {color} rectangle', {color: color})} on:click={() => insert(createLayer('rect', { x: 16, y: 10, w: 16, h: 12 }, { name: color, fill: color }))}><svg viewBox="0 0 80 64" aria-hidden="true"><rect width="80" height="64" rx="10" fill={color}></rect></svg><span>{color}</span></button>{/each}</div>{/if}{/if} </div>
