<script lang="ts">
import {pictorSearchText, LIVE_COMPONENTS} from '@awc-ui/pictor-model';

import {t} from '$lib/showcase';

import {onMount} from 'svelte';import StudioDialog from '$lib/editor/StudioDialog.svelte';import TextControl from '$lib/editor/TextControl.svelte';
type Entry={tag:string;count:number;markup:string};let open=false,entries:Entry[]=[],query='',selected='',copyStatus='';
function inspectComponents(){const found=new Map<string,Entry>();for(const element of document.querySelectorAll('.shell *')){if(!element.localName.startsWith('md-')||!customElements.get(element.localName)||element.closest('[data-component-lens]'))continue;const entry=found.get(element.localName);if(entry){entry.count++;continue}const clone=element.cloneNode(true) as Element;for(const node of [clone,...clone.querySelectorAll('*')])for(const attribute of [...node.attributes])if(/^(class|id|style|data-.+|s-.+|c-id|hydrated)$/.test(attribute.name))node.removeAttribute(attribute.name);found.set(element.localName,{tag:element.localName,count:1,markup:clone.outerHTML})}return [...found.values()].sort((a,b)=>a.tag.localeCompare(b.tag))}
onMount(()=>{const reveal=()=>{entries=inspectComponents();selected=entries.find(entry=>entry.tag==='md-button')?.tag??entries[0]?.tag??'';query='';copyStatus='';open=true};window.addEventListener('pictor:components',reveal);return()=>window.removeEventListener('pictor:components',reveal)});
const componentName = (tag:string) => {const name=tag.slice(3).replace(/-/g,' ');return name[0].toUpperCase()+name.slice(1)};
$: componentSearch = (entry:Entry) => { const live=LIVE_COMPONENTS.find(item=>item.id==='awc:'+entry.tag.slice(3));return pictorSearchText([entry.tag,componentName(entry.tag),$t(componentName(entry.tag)),live?$t(live.name):'',live?$t(live.description):''].join(' ')) };
$: current=entries.find(entry=>entry.tag===selected);$: filtered=entries.filter(entry=>componentSearch(entry).includes(pictorSearchText(query)));
</script>
<div data-component-lens><StudioDialog {open} onClose={()=>open=false} title={$t('Inside the interface')}><p class="component-lens__intro"><strong>{entries.length} {$t('AWC component types')}</strong> {$t('compose this screen. Explore the elements behind the experience, then bring them into your own application.')}</p><TextControl live label={$t('Find a component')} value={query} onValue={value=>query=value} placeholder={$t('Try button, dialog, slider…')}/><div class="component-lens__layout"><div class="component-lens__list" aria-label={$t('Components on this screen')}>{#each filtered as entry}<button aria-pressed={selected===entry.tag} on:click={()=>{selected=entry.tag;copyStatus=''}}><code>{entry.tag}</code><span>{entry.count}</span></button>{/each}{#if !filtered.length}<p>{$t('No matching components on this screen.')}</p>{/if}</div>{#if current}<section class="component-lens__detail"><span class="component-lens__eyebrow">{$t('LIVE ELEMENT MARKUP')}</span><h3>{current.tag}</h3><p>{current.count} {current.count===1?$t('instance'):$t('instances')} {$t('in this application surface. This HTML shows the first instance; object properties and event handlers belong in your framework code.')}</p><pre tabindex="0" role="region" aria-label={$t('Component HTML')}><code>{current.markup.length>5000?`${current.markup.slice(0,5000)}\n… ${$t('Preview truncated; copy includes the complete element.')}`:current.markup}</code></pre><div class="component-lens__actions"><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="tonal" icon="content_copy" on:click={async()=>{try{await navigator.clipboard.writeText(current.markup);copyStatus='Markup copied'}catch{copyStatus='Clipboard unavailable. Select and copy the preview.'}}}>{$t('Copy HTML')}</md-button><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="text" icon="open_in_new" href={`https://awc-ui.dev/components/${current.tag.slice(3)}/`} target="_blank" rel="noopener noreferrer">{$t('Component API')}</md-button></div><span role="status">{$t(copyStatus)}</span></section>{/if}</div><div class="component-lens__install"><span>{$t('Start with the library')}</span><code>npm i @awc-ui/core</code><a href="https://awc-ui.dev/getting-started/installation/" target="_blank" rel="noopener noreferrer">{$t('Choose your framework →')}</a></div><svelte:fragment slot="actions"><!-- AWC owns keyboard activation inside its shadow control. -->
<!-- svelte-ignore a11y-click-events-have-key-events a11y-no-static-element-interactions -->
<md-button variant="text" on:click={()=>open=false}>{$t('Back to Pictor')}</md-button></svelte:fragment></StudioDialog></div>
