#!/usr/bin/env node
/**
 * Compiles the AssemblyScript modules under packages/core/src/wasm to
 * WebAssembly and base64-inlines each result into a sibling `<name>.wasm.ts`.
 *
 * The generated `.ts` files are COMMITTED so `stencil build`, turbo, and npm
 * consumers never need the `asc` toolchain. Run this whenever a module source
 * changes:
 *   pnpm --filter @awc-ui/core build:wasm
 *
 * `--check` regenerates to a temp string and diffs it against the committed
 * files, exiting non-zero if any is stale (wire into CI to catch
 * un-regenerated edits).
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CORE = join(ROOT, 'packages/core');
const WASM_DIR = join(CORE, 'src/wasm');

// `asc` is a devDependency of @awc-ui/core; resolve it from there so the
// pnpm virtual store layout doesn't matter.
const requireFromCore = createRequire(pathToFileURL(join(CORE, 'package.json')));
const ASC = requireFromCore.resolve('assemblyscript/bin/asc.js');
const ASCONFIG = join(WASM_DIR, 'asconfig.json');

/** AssemblyScript modules to compile: `<name>.ts` → `<name>.wasm.ts`. */
const MODULES = ['engine'];

const checkMode = process.argv.includes('--check');

function compile(name) {
  const tmp = mkdtempSync(join(tmpdir(), 'md3-wasm-'));
  const wasmOut = join(tmp, `${name}.wasm`);
  try {
    execFileSync(
      process.execPath,
      [ASC, join(WASM_DIR, `${name}.ts`), '--config', ASCONFIG, '--outFile', wasmOut],
      { stdio: 'inherit' },
    );
    return readFileSync(wasmOut);
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function renderModule(name, wasmBuffer) {
  const base64 = wasmBuffer.toString('base64');
  return (
    `// GENERATED by scripts/build-wasm.mjs — DO NOT EDIT.\n` +
    `// Source: packages/core/src/wasm/${name}.ts\n` +
    `// Regenerate with: pnpm --filter @awc-ui/core build:wasm\n` +
    `/* eslint-disable */\n` +
    `export const WASM_BASE64 =\n  '${base64}';\n`
  );
}

let stale = false;
for (const name of MODULES) {
  const output = join(WASM_DIR, `${name}.wasm.ts`);
  const wasmBuffer = compile(name);
  const generated = renderModule(name, wasmBuffer);

  if (checkMode) {
    let current = '';
    try {
      current = readFileSync(output, 'utf8');
    } catch {
      /* missing file — treat as stale */
    }
    if (current !== generated) {
      console.error(
        `✗ ${name}.wasm.ts is stale. Run \`pnpm --filter @awc-ui/core build:wasm\` and commit the result.`,
      );
      stale = true;
    } else {
      console.log(`✓ ${name}.wasm.ts is up to date (${wasmBuffer.length} bytes wasm)`);
    }
  } else {
    writeFileSync(output, generated);
    console.log(
      `Wrote ${output} (${wasmBuffer.length} bytes wasm → ${generated.length} bytes base64 module)`,
    );
  }
}
if (checkMode && stale) process.exit(1);
