#!/usr/bin/env bash
set -euo pipefail

# Build pipeline for the documentation site.
#
# Used by .github/workflows/deploy.yml (and reproducible locally).
#
# 1. Build the core component library
# 2. Build Storybook static output (embedded at /storybook/ on the deployed site)
# 3. Generate component doc pages from the Stencil readmes + custom-elements manifest
# 4. Build the Astro docs site (Pagefind index is auto-generated by Starlight)
#
# Output: apps/docs/dist/ — ready to deploy to Netlify.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT"

echo "==> Building core library..."
pnpm --filter @awc-ui/core build

echo ""
echo "==> Building Storybook static site..."
pnpm --filter @awc-ui/storybook exec storybook build -o "$ROOT/apps/docs/public/storybook" --quiet

echo ""
echo "==> Generating component documentation pages..."
node scripts/generate-docs.mjs

echo ""
echo "==> Building Astro docs site..."
pnpm --filter @awc-ui/docs exec astro build

echo ""
echo "==> Done! Output: apps/docs/dist/"
