#!/usr/bin/env bash
set -euo pipefail

# Build pipeline for the documentation site.
#
# Used by .github/workflows/deploy.yml (and reproducible locally).
#
# 1. Build the core component library
# 2. Build Storybook static output (embedded at /storybook/ on the deployed site)
# 3. Generate component doc pages from the Stencil readmes + custom-elements manifest
# 4. Build the six showcase framework builds (embedded at /showcase/ on the site)
# 5. Build the Astro docs site (Pagefind index is auto-generated by Starlight)
#
# Output: apps/docs/dist/ — ready to deploy to Netlify.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$ROOT"

echo "==> Building core library..."
pnpm --filter @awc-ui/core build

echo ""
echo "==> Building theme package..."
# @awc-ui/theme resolves from dist/ since it became publishable — a fresh
# checkout has no dist, and both Storybook's preview and the theme
# generator import the package.
pnpm --filter @awc-ui/theme build

echo ""
echo "==> Building Storybook static site..."
pnpm --filter @awc-ui/storybook exec storybook build -o "$ROOT/apps/docs/public/storybook" --quiet

echo ""
echo "==> Generating component documentation pages..."
node scripts/generate-docs.mjs

echo ""
echo "==> Building the showcase applications..."
# Every static build of every showcase vertical, staged into
# apps/docs/public/showcase/<vertical>/<framework>/. The set comes from
# scripts/lib/showcase-verticals.mjs, so adding a vertical needs no edit here.
# Must run AFTER the core build — each one copies Stencil's lazy runtime out of
# packages/core/dist — and BEFORE astro build,
# which is when public/ is read. Without this the site deploys with every
# /showcase/credit-risk/<framework>/ URL returning a 404, while the docs page
# linking to them says otherwise.
node scripts/build-showcase.mjs

echo ""
echo "==> Syncing the Stencil runtime into apps/docs/public/..."
# Must run AFTER the core build above and BEFORE astro build: the chunk hashes
# rotate every time core is rebuilt, and a stale copy 404s on a shared chunk,
# which fails every lazy element at once and renders the site at zero height.
# `astro build` is invoked directly below rather than through the package's
# `build` script, so this copy does not happen on its own.
node scripts/sync-docs-runtime.mjs

echo ""
echo "==> Building Astro docs site..."
pnpm --filter @awc-ui/docs exec astro build

echo ""
echo "==> Done! Output: apps/docs/dist/"
