/* Auto-generated by Stencil svelte integration */
/* This file re-exports stencil components for Svelte usage */

// All AWC UI components work as native custom elements in Svelte.
// Import defineCustomElements to register them.
export { defineCustomElements } from '@awc-ui/core/loader';
